{{- if .Values.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "gateway-webhook.fullname" . }}
  namespace: {{ include "gateway-webhook.namespace" . }}
  labels:
    {{- include "gateway-webhook.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "gateway-webhook.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.prometheus.serviceMonitor.path }}
      interval: {{ .Values.prometheus.serviceMonitor.interval }}
{{- end }}
