/**
 * E2E Integration Tests for Agent Phone Number Mapping
 *
 * Tests the complete flow of mapping phone numbers to agents.
 * Covers: registration, updates, deactivation, multi-agent scenarios.
 */

import { afterAll, beforeAll, describe, expect, it } from "bun:test";
import { Client } from "pg";
import { v4 as uuidv4 } from "uuid";
import {
  cleanupTestData,
  createTestDataSet,
  type TestDataSet,
} from "../infrastructure/test-data-factory";

const TEST_DB_URL = process.env.DATABASE_URL || "";

describe("Agent Phone Number Mapping E2E Tests", () => {
  let testData: TestDataSet;
  let client: Client;
  let testAgents: string[] = [];

  beforeAll(async () => {
    if (!TEST_DB_URL) {
      throw new Error("DATABASE_URL is required for integration tests");
    }

    testData = await createTestDataSet(TEST_DB_URL, {
      organizationName: "Phone Mapping Test Org",
      creditBalance: 1000,
    });

    client = new Client({ connectionString: TEST_DB_URL });
    await client.connect();
  });

  afterAll(async () => {
    if (!client || !testData) {
      return;
    }

    // Clean up all test agents and phone numbers
    for (const agentId of testAgents) {
      await client.query(
        `DELETE FROM phone_message_log WHERE phone_number_id IN 
         (SELECT id FROM agent_phone_numbers WHERE agent_id = $1)`,
        [agentId],
      );
      await client.query(`DELETE FROM agent_phone_numbers WHERE agent_id = $1`, [agentId]);
      await client.query(`DELETE FROM agents WHERE id = $1`, [agentId]);
    }

    await client.end();
    await cleanupTestData(TEST_DB_URL, testData.organization.id);
  });

  // Helper to create test agent
  async function createTestAgent(name: string): Promise<string> {
    const agentId = uuidv4();
    await client.query(`INSERT INTO agents (id, name, enabled) VALUES ($1, $2, true)`, [
      agentId,
      name,
    ]);
    testAgents.push(agentId);
    return agentId;
  }

  describe("Basic Phone Number Registration", () => {
    it("should register a new phone number for an agent", async () => {
      const agentId = await createTestAgent("Basic Registration Agent");
      const phoneNumber = "+15551000001";

      const result = await client.query(
        `INSERT INTO agent_phone_numbers 
         (organization_id, agent_id, phone_number, friendly_name, provider, phone_type)
         VALUES ($1, $2, $3, 'Main Line', 'twilio', 'sms')
         RETURNING id, phone_number, friendly_name, provider, phone_type, is_active`,
        [testData.organization.id, agentId, phoneNumber],
      );

      expect(result.rows[0]).toBeDefined();
      expect(result.rows[0].phone_number).toBe(phoneNumber);
      expect(result.rows[0].friendly_name).toBe("Main Line");
      expect(result.rows[0].provider).toBe("twilio");
      expect(result.rows[0].phone_type).toBe("sms");
      expect(result.rows[0].is_active).toBe(true);
    });

    it("should auto-generate webhook URL on registration", async () => {
      const agentId = await createTestAgent("Webhook URL Agent");
      const phoneNumber = "+15551000002";

      // Note: webhook_url is generated by the application layer, not DB default
      // This test verifies the field exists and can be set
      const webhookUrl = `https://example.com/api/webhooks/twilio/${testData.organization.id}`;

      const result = await client.query(
        `INSERT INTO agent_phone_numbers 
         (organization_id, agent_id, phone_number, provider, phone_type, webhook_url)
         VALUES ($1, $2, $3, 'twilio', 'sms', $4)
         RETURNING id, webhook_url`,
        [testData.organization.id, agentId, phoneNumber, webhookUrl],
      );

      expect(result.rows[0].webhook_url).toBe(webhookUrl);
    });

    it("should support different providers", async () => {
      const agentId = await createTestAgent("Multi-Provider Agent");

      // Register Twilio number
      const twilioResult = await client.query(
        `INSERT INTO agent_phone_numbers 
         (organization_id, agent_id, phone_number, provider, phone_type)
         VALUES ($1, $2, '+15551000003', 'twilio', 'sms')
         RETURNING id, provider`,
        [testData.organization.id, agentId],
      );
      expect(twilioResult.rows[0].provider).toBe("twilio");

      // Register Blooio number
      const blooioResult = await client.query(
        `INSERT INTO agent_phone_numbers 
         (organization_id, agent_id, phone_number, provider, phone_type)
         VALUES ($1, $2, '+15551000004', 'blooio', 'imessage')
         RETURNING id, provider, phone_type`,
        [testData.organization.id, agentId],
      );
      expect(blooioResult.rows[0].provider).toBe("blooio");
      expect(blooioResult.rows[0].phone_type).toBe("imessage");
    });
  });

  describe("Phone Number Capabilities", () => {
    it("should track SMS-only capabilities", async () => {
      const agentId = await createTestAgent("SMS Only Agent");

      const result = await client.query(
        `INSERT INTO agent_phone_numbers 
         (organization_id, agent_id, phone_number, provider, phone_type,
          can_send_sms, can_receive_sms, can_send_mms, can_receive_mms, can_voice)
         VALUES ($1, $2, '+15551000005', 'twilio', 'sms',
                 true, true, false, false, false)
         RETURNING can_send_sms, can_receive_sms, can_send_mms, can_receive_mms, can_voice`,
        [testData.organization.id, agentId],
      );

      expect(result.rows[0].can_send_sms).toBe(true);
      expect(result.rows[0].can_receive_sms).toBe(true);
      expect(result.rows[0].can_send_mms).toBe(false);
      expect(result.rows[0].can_receive_mms).toBe(false);
      expect(result.rows[0].can_voice).toBe(false);
    });

    it("should track full-featured phone number", async () => {
      const agentId = await createTestAgent("Full Featured Agent");

      const result = await client.query(
        `INSERT INTO agent_phone_numbers 
         (organization_id, agent_id, phone_number, provider, phone_type,
          can_send_sms, can_receive_sms, can_send_mms, can_receive_mms, can_voice)
         VALUES ($1, $2, '+15551000006', 'twilio', 'both',
                 true, true, true, true, true)
         RETURNING can_send_sms, can_receive_sms, can_send_mms, can_receive_mms, can_voice`,
        [testData.organization.id, agentId],
      );

      expect(result.rows[0].can_send_sms).toBe(true);
      expect(result.rows[0].can_receive_sms).toBe(true);
      expect(result.rows[0].can_send_mms).toBe(true);
      expect(result.rows[0].can_receive_mms).toBe(true);
      expect(result.rows[0].can_voice).toBe(true);
    });

    it("should track voice-only capabilities", async () => {
      const agentId = await createTestAgent("Voice Only Agent");

      const result = await client.query(
        `INSERT INTO agent_phone_numbers 
         (organization_id, agent_id, phone_number, provider, phone_type,
          can_send_sms, can_receive_sms, can_voice)
         VALUES ($1, $2, '+15551000007', 'twilio', 'voice',
                 false, false, true)
         RETURNING can_send_sms, can_receive_sms, can_voice`,
        [testData.organization.id, agentId],
      );

      expect(result.rows[0].can_send_sms).toBe(false);
      expect(result.rows[0].can_receive_sms).toBe(false);
      expect(result.rows[0].can_voice).toBe(true);
    });
  });

  describe("Multiple Phone Numbers Per Agent", () => {
    it("should allow multiple phone numbers for a single agent", async () => {
      const agentId = await createTestAgent("Multi-Number Agent");

      // Register multiple numbers
      await client.query(
        `INSERT INTO agent_phone_numbers 
         (organization_id, agent_id, phone_number, friendly_name, provider, phone_type)
         VALUES 
         ($1, $2, '+15551000010', 'Primary Line', 'twilio', 'sms'),
         ($1, $2, '+15551000011', 'Secondary Line', 'twilio', 'sms'),
         ($1, $2, '+15551000012', 'iMessage', 'blooio', 'imessage')`,
        [testData.organization.id, agentId],
      );

      // Query all numbers for this agent
      const result = await client.query(
        `SELECT * FROM agent_phone_numbers WHERE agent_id = $1 ORDER BY phone_number`,
        [agentId],
      );

      expect(result.rows.length).toBe(3);
      expect(result.rows[0].friendly_name).toBe("Primary Line");
      expect(result.rows[1].friendly_name).toBe("Secondary Line");
      expect(result.rows[2].friendly_name).toBe("iMessage");
    });
  });

  describe("Phone Number Updates", () => {
    it("should update phone number friendly name", async () => {
      const agentId = await createTestAgent("Update Name Agent");
      const phoneNumber = "+15551000020";

      const insertResult = await client.query(
        `INSERT INTO agent_phone_numbers 
         (organization_id, agent_id, phone_number, friendly_name, provider, phone_type)
         VALUES ($1, $2, $3, 'Old Name', 'twilio', 'sms')
         RETURNING id`,
        [testData.organization.id, agentId, phoneNumber],
      );

      const phoneId = insertResult.rows[0].id;

      // Update the friendly name
      await client.query(
        `UPDATE agent_phone_numbers 
         SET friendly_name = 'New Name', updated_at = NOW()
         WHERE id = $1`,
        [phoneId],
      );

      const selectResult = await client.query(
        `SELECT friendly_name FROM agent_phone_numbers WHERE id = $1`,
        [phoneId],
      );

      expect(selectResult.rows[0].friendly_name).toBe("New Name");
    });

    it("should update capabilities", async () => {
      const agentId = await createTestAgent("Update Caps Agent");
      const phoneNumber = "+15551000021";

      const insertResult = await client.query(
        `INSERT INTO agent_phone_numbers 
         (organization_id, agent_id, phone_number, provider, phone_type,
          can_send_mms, can_receive_mms)
         VALUES ($1, $2, $3, 'twilio', 'sms', false, false)
         RETURNING id`,
        [testData.organization.id, agentId, phoneNumber],
      );

      const phoneId = insertResult.rows[0].id;

      // Enable MMS capabilities
      await client.query(
        `UPDATE agent_phone_numbers 
         SET can_send_mms = true, can_receive_mms = true, updated_at = NOW()
         WHERE id = $1`,
        [phoneId],
      );

      const selectResult = await client.query(
        `SELECT can_send_mms, can_receive_mms FROM agent_phone_numbers WHERE id = $1`,
        [phoneId],
      );

      expect(selectResult.rows[0].can_send_mms).toBe(true);
      expect(selectResult.rows[0].can_receive_mms).toBe(true);
    });

    it("should track last_message_at timestamp", async () => {
      const agentId = await createTestAgent("Last Message Agent");
      const phoneNumber = "+15551000022";

      const insertResult = await client.query(
        `INSERT INTO agent_phone_numbers 
         (organization_id, agent_id, phone_number, provider, phone_type)
         VALUES ($1, $2, $3, 'twilio', 'sms')
         RETURNING id, last_message_at`,
        [testData.organization.id, agentId, phoneNumber],
      );

      const phoneId = insertResult.rows[0].id;
      expect(insertResult.rows[0].last_message_at).toBeNull();

      // Update last_message_at
      await client.query(`UPDATE agent_phone_numbers SET last_message_at = NOW() WHERE id = $1`, [
        phoneId,
      ]);

      const selectResult = await client.query(
        `SELECT last_message_at FROM agent_phone_numbers WHERE id = $1`,
        [phoneId],
      );

      expect(selectResult.rows[0].last_message_at).not.toBeNull();
    });
  });

  describe("Phone Number Deactivation", () => {
    it("should deactivate phone number without deleting", async () => {
      const agentId = await createTestAgent("Deactivate Agent");
      const phoneNumber = "+15551000030";

      const insertResult = await client.query(
        `INSERT INTO agent_phone_numbers 
         (organization_id, agent_id, phone_number, provider, phone_type, is_active)
         VALUES ($1, $2, $3, 'twilio', 'sms', true)
         RETURNING id`,
        [testData.organization.id, agentId, phoneNumber],
      );

      const phoneId = insertResult.rows[0].id;

      // Deactivate
      await client.query(
        `UPDATE agent_phone_numbers SET is_active = false, updated_at = NOW() WHERE id = $1`,
        [phoneId],
      );

      const selectResult = await client.query(
        `SELECT is_active FROM agent_phone_numbers WHERE id = $1`,
        [phoneId],
      );

      expect(selectResult.rows[0].is_active).toBe(false);
    });

    it("should exclude deactivated numbers from routing", async () => {
      const agentId = await createTestAgent("Inactive Routing Agent");

      // Create one active and one inactive number
      await client.query(
        `INSERT INTO agent_phone_numbers 
         (organization_id, agent_id, phone_number, provider, phone_type, is_active)
         VALUES 
         ($1, $2, '+15551000031', 'twilio', 'sms', true),
         ($1, $2, '+15551000032', 'twilio', 'sms', false)`,
        [testData.organization.id, agentId],
      );

      // Query only active numbers
      const result = await client.query(
        `SELECT phone_number FROM agent_phone_numbers 
         WHERE agent_id = $1 AND is_active = true`,
        [agentId],
      );

      expect(result.rows.length).toBe(1);
      expect(result.rows[0].phone_number).toBe("+15551000031");
    });
  });

  describe("Phone Number Verification", () => {
    it("should track verification status", async () => {
      const agentId = await createTestAgent("Verification Agent");
      const phoneNumber = "+15551000040";

      const insertResult = await client.query(
        `INSERT INTO agent_phone_numbers 
         (organization_id, agent_id, phone_number, provider, phone_type, verified)
         VALUES ($1, $2, $3, 'twilio', 'sms', false)
         RETURNING id, verified`,
        [testData.organization.id, agentId, phoneNumber],
      );

      expect(insertResult.rows[0].verified).toBe(false);

      // Mark as verified
      await client.query(
        `UPDATE agent_phone_numbers 
         SET verified = true, verified_at = NOW()
         WHERE id = $1`,
        [insertResult.rows[0].id],
      );

      const selectResult = await client.query(
        `SELECT verified, verified_at FROM agent_phone_numbers WHERE id = $1`,
        [insertResult.rows[0].id],
      );

      expect(selectResult.rows[0].verified).toBe(true);
      expect(selectResult.rows[0].verified_at).not.toBeNull();
    });
  });

  describe("Rate Limiting Configuration", () => {
    it("should store rate limit settings", async () => {
      const agentId = await createTestAgent("Rate Limit Agent");
      const phoneNumber = "+15551000050";

      const result = await client.query(
        `INSERT INTO agent_phone_numbers 
         (organization_id, agent_id, phone_number, provider, phone_type,
          max_messages_per_minute, max_messages_per_day)
         VALUES ($1, $2, $3, 'twilio', 'sms', '30', '500')
         RETURNING max_messages_per_minute, max_messages_per_day`,
        [testData.organization.id, agentId, phoneNumber],
      );

      expect(result.rows[0].max_messages_per_minute).toBe("30");
      expect(result.rows[0].max_messages_per_day).toBe("500");
    });

    it("should use default rate limits when not specified", async () => {
      const agentId = await createTestAgent("Default Rate Agent");
      const phoneNumber = "+15551000051";

      const result = await client.query(
        `INSERT INTO agent_phone_numbers 
         (organization_id, agent_id, phone_number, provider, phone_type)
         VALUES ($1, $2, $3, 'twilio', 'sms')
         RETURNING max_messages_per_minute, max_messages_per_day`,
        [testData.organization.id, agentId, phoneNumber],
      );

      // Should use defaults
      expect(result.rows[0].max_messages_per_minute).toBe("60");
      expect(result.rows[0].max_messages_per_day).toBe("1000");
    });
  });

  describe("Multi-Organization Isolation", () => {
    it("should isolate phone numbers between organizations", async () => {
      // Create second test organization
      const org2 = await createTestDataSet(TEST_DB_URL, {
        organizationName: "Second Org",
      });

      const agentId1 = await createTestAgent("Org1 Agent");
      const agentId2 = uuidv4();
      await client.query(`INSERT INTO agents (id, name, enabled) VALUES ($1, $2, true)`, [
        agentId2,
        "Org2 Agent",
      ]);

      // Same phone number in different orgs (should be allowed)
      const phoneNumber = "+15551000060";

      await client.query(
        `INSERT INTO agent_phone_numbers 
         (organization_id, agent_id, phone_number, provider, phone_type)
         VALUES ($1, $2, $3, 'twilio', 'sms')`,
        [testData.organization.id, agentId1, phoneNumber],
      );

      await client.query(
        `INSERT INTO agent_phone_numbers 
         (organization_id, agent_id, phone_number, provider, phone_type)
         VALUES ($1, $2, $3, 'twilio', 'sms')`,
        [org2.organization.id, agentId2, phoneNumber],
      );

      // Query for org1 should only return org1's number
      const result1 = await client.query(
        `SELECT * FROM agent_phone_numbers 
         WHERE organization_id = $1 AND phone_number = $2`,
        [testData.organization.id, phoneNumber],
      );
      expect(result1.rows.length).toBe(1);
      expect(result1.rows[0].agent_id).toBe(agentId1);

      // Query for org2 should only return org2's number
      const result2 = await client.query(
        `SELECT * FROM agent_phone_numbers 
         WHERE organization_id = $1 AND phone_number = $2`,
        [org2.organization.id, phoneNumber],
      );
      expect(result2.rows.length).toBe(1);
      expect(result2.rows[0].agent_id).toBe(agentId2);

      // Cleanup org2
      await client.query(`DELETE FROM agent_phone_numbers WHERE organization_id = $1`, [
        org2.organization.id,
      ]);
      await client.query(`DELETE FROM agents WHERE id = $1`, [agentId2]);
      await cleanupTestData(TEST_DB_URL, org2.organization.id);
    });
  });

  describe("Cascade Deletion", () => {
    it("should delete phone numbers when agent is deleted", async () => {
      const agentId = await createTestAgent("Cascade Agent");

      // Register phone numbers
      await client.query(
        `INSERT INTO agent_phone_numbers 
         (organization_id, agent_id, phone_number, provider, phone_type)
         VALUES 
         ($1, $2, '+15551000070', 'twilio', 'sms'),
         ($1, $2, '+15551000071', 'twilio', 'sms')`,
        [testData.organization.id, agentId],
      );

      // Verify numbers exist
      const beforeDelete = await client.query(
        `SELECT COUNT(*) FROM agent_phone_numbers WHERE agent_id = $1`,
        [agentId],
      );
      expect(parseInt(beforeDelete.rows[0].count)).toBe(2);

      // Delete agent (should cascade to phone numbers)
      await client.query(`DELETE FROM agents WHERE id = $1`, [agentId]);

      // Verify numbers are deleted
      const afterDelete = await client.query(
        `SELECT COUNT(*) FROM agent_phone_numbers WHERE agent_id = $1`,
        [agentId],
      );
      expect(parseInt(afterDelete.rows[0].count)).toBe(0);

      // Remove from test agents list since we already deleted it
      testAgents = testAgents.filter((id) => id !== agentId);
    });

    it("should delete message logs when phone number is deleted", async () => {
      const agentId = await createTestAgent("Message Log Cascade Agent");

      // Register phone number
      const phoneResult = await client.query(
        `INSERT INTO agent_phone_numbers 
         (organization_id, agent_id, phone_number, provider, phone_type)
         VALUES ($1, $2, '+15551000080', 'twilio', 'sms')
         RETURNING id`,
        [testData.organization.id, agentId],
      );
      const phoneId = phoneResult.rows[0].id;

      // Create message logs
      await client.query(
        `INSERT INTO phone_message_log 
         (phone_number_id, direction, from_number, to_number, message_body, message_type, status)
         VALUES 
         ($1, 'inbound', '+15559999999', '+15551000080', 'Test 1', 'sms', 'received'),
         ($1, 'outbound', '+15551000080', '+15559999999', 'Reply 1', 'sms', 'sent')`,
        [phoneId],
      );

      // Verify logs exist
      const beforeDelete = await client.query(
        `SELECT COUNT(*) FROM phone_message_log WHERE phone_number_id = $1`,
        [phoneId],
      );
      expect(parseInt(beforeDelete.rows[0].count)).toBe(2);

      // Delete phone number (should cascade to message logs)
      await client.query(`DELETE FROM agent_phone_numbers WHERE id = $1`, [phoneId]);

      // Verify logs are deleted
      const afterDelete = await client.query(
        `SELECT COUNT(*) FROM phone_message_log WHERE phone_number_id = $1`,
        [phoneId],
      );
      expect(parseInt(afterDelete.rows[0].count)).toBe(0);
    });
  });
});
