tasks:
    - name: "init eliza env"
      init: |
          nvm install v23.3.0
          echo "Installing pnpm version 9.15.7 globally..."
          npm i -g pnpm@9.15.7
          git fetch --tags
          git checkout $(git describe --tags --abbrev=0)
      command: pnpm install && pnpm run build
