services:
  slack-nova:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: ["pnpm", "start", "--characters=characters/nova.character.json"]
    environment:
      GOOGLE_GENERATIVE_AI_API_KEY: ${GOOGLE_GENERATIVE_AI_API_KEY}
      SLACK_APP_ID: ${SLACK_APP_ID}
      SLACK_CLIENT_ID: ${SLACK_CLIENT_ID}
      SLACK_CLIENT_SECRET: ${SLACK_CLIENT_SECRET}
      SLACK_SIGNING_SECRET: ${SLACK_SIGNING_SECRET}
      SLACK_BOT_TOKEN: ${SLACK_BOT_TOKEN}
      SLACK_VERIFICATION_TOKEN: ${SLACK_VERIFICATION_TOKEN}
      SLACK_SERVER_PORT: ${SLACK_SERVER_PORT}
      SLACK_BOT_ID: ${SLACK_BOT_ID}
      CHANNEL_ID: ${CHANNEL_ID}
      CHANNEL_MANAGER_ID: ${CHANNEL_MANAGER_ID}
    volumes:
      - data:/app/agent/data
    ports:
      - 3069:3069

volumes:
  data:
