services:
    tee:
        command: ["pnpm", "start", "--character=${CHARACTER_FILE}"]
        build:
            context: .
            dockerfile: Dockerfile
        stdin_open: true
        tty: true
        volumes:
            - /var/run/tappd.sock:/var/run/tappd.sock
            - ./characters:/app/characters
        env_file:
            - .env
        environment:
            - CHARACTER_FILE=${CHARACTER_FILE}
            - NODE_OPTIONS=--max-old-space-size=8192
        ports:
            - "3000"
        restart: always
