#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 NubsCarson and contributors
#
# Push current host build artifacts (elizad release binary + agent/ source)
# into a running QEMU VM via the SSH forward set up by boot.sh, then
# restart the elizad-session.service so the new binaries take effect.
#
# Phase 0 milestone 11d: real implementation. Requires:
#   - VM is up (vm-up).
#   - vm/.ssh/usbeliza_dev_ed25519 exists (generated by build-base.sh).
#   - cargo + bun on the host.

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$repo_root"

ssh_port=2222
ssh_target="eliza@127.0.0.1"
ssh_key="vm/.ssh/usbeliza_dev_ed25519"
ssh_opts=(
    -i "$ssh_key"
    -o StrictHostKeyChecking=no
    -o UserKnownHostsFile=/dev/null
    -o LogLevel=ERROR
    -p "$ssh_port"
)
scp_opts=("${ssh_opts[@]/-p /-P }")  # scp uses -P, ssh uses -p
# Replace the literal single-token `-p PORT` with `-P PORT`.
scp_opts=(
    -i "$ssh_key"
    -o StrictHostKeyChecking=no
    -o UserKnownHostsFile=/dev/null
    -o LogLevel=ERROR
    -P "$ssh_port"
)

if [ ! -f "$ssh_key" ]; then
    echo "error: $ssh_key missing. Re-run 'just vm-build-base' to regenerate." >&2
    exit 1
fi

echo "==> waiting for SSH on localhost:$ssh_port"
if ! vm/scripts/inject.py wait-port "$ssh_port" 30 >/dev/null 2>&1; then
    echo "error: VM SSH forward (localhost:$ssh_port) is not up. Run 'just vm-up' first." >&2
    exit 1
fi

# --- Build host artifacts ---
echo "==> building elizad (release)"
cargo build -p elizad --release

echo "==> bun install in agent/"
( cd agent && bun install --frozen-lockfile )

# --- Push artifacts ---
echo "==> deploying to $ssh_target"
ssh "${ssh_opts[@]}" "$ssh_target" 'sudo install -d -o eliza -g eliza /opt/usbeliza /opt/usbeliza/agent /opt/usbeliza/bin'
scp "${scp_opts[@]}" target/release/elizad "$ssh_target:/tmp/elizad"
ssh "${ssh_opts[@]}" "$ssh_target" 'sudo mv /tmp/elizad /opt/usbeliza/bin/elizad && sudo chmod 755 /opt/usbeliza/bin/elizad && sudo ln -sfn /opt/usbeliza/bin/elizad /usr/local/bin/elizad'

# Agent: ship src + node_modules. We use rsync over ssh.
rsync -a --delete \
    --exclude=node_modules/.cache \
    -e "ssh ${ssh_opts[*]}" \
    agent/ "$ssh_target:/opt/usbeliza/agent/"

# --- Restart agent first (vm-test POSTs to it immediately) ---
# On a fresh snapshot boot the agent service hits start-limit-hit because
# /opt/usbeliza/agent doesn't exist until the rsync above. Reset-failed
# clears the counter so the restart actually starts a new bun.
echo "==> restarting eliza-agent.service"
ssh "${ssh_opts[@]}" "$ssh_target" 'sudo systemctl reset-failed eliza-agent.service 2>/dev/null || true
                                     sudo systemctl restart eliza-agent.service' || true

# Block until /api/status is healthy so callers can POST /api/chat
# immediately without racing the bun cold-start.
echo "==> waiting for /api/status to come back"
ssh "${ssh_opts[@]}" "$ssh_target" '
    for _ in $(seq 1 30); do
        curl -sf http://127.0.0.1:41337/api/status >/dev/null 2>&1 && exit 0
        sleep 1
    done
    echo "warn: agent /api/status never returned 200 within 30s" >&2
    exit 1
' || echo "warn: agent did not become ready; downstream may fail"

# --- Restart the session ---
echo "==> restarting elizad-session.service"
ssh "${ssh_opts[@]}" "$ssh_target" 'sudo systemctl restart elizad-session.service' || true
echo "==> deploy complete"
