/**
 * Clone omnivoice.cpp at the pinned commit, strip its `ggml/` submodule,
 * and copy `src/` + `tools/` + selected `examples/` data into the
 * llama.cpp tree under `<llamaCppRoot>/omnivoice/`.
 *
 * Caller (build-llama-cpp-dflash.mjs):
 *   import { prepareOmnivoiceFusion } from
 *     "./omnivoice-fuse/prepare.mjs";
 *   const { commit, ggmlSubmoduleCommit, sourceCount } =
 *     prepareOmnivoiceFusion({
 *       cacheRoot: "...", // ~/.cache/eliza-dflash
 *       llamaCppRoot: "...", // path to elizaOS/llama.cpp checkout
 *       omnivoiceRef: "38f824023d…",
 *     });
 *
 * Failure modes are hard errors — see omnivoice-fuse/README.md. There
 * is no fallback path.
 */

import { spawnSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

const OMNIVOICE_REPO =
  process.env.MILADY_OMNIVOICE_REMOTE ||
  "https://github.com/ServeurpersoCom/omnivoice.cpp.git";

// Master HEAD as of 2026-05-10. Bump per the runbook in README.md.
export const OMNIVOICE_REF =
  process.env.MILADY_OMNIVOICE_REF || "38f824023d12b21a7c324651b18bd90f16d8bb86";

// The ServeurpersoCom ggml submodule pin we explicitly DO NOT include
// in the fused build. Recorded so verify-symbols.mjs can assert that no
// `omnivoice/ggml` directory is left dangling under the llama.cpp tree.
export const OMNIVOICE_GGML_REF =
  process.env.MILADY_OMNIVOICE_GGML_REF ||
  "0e3980ef205ea3639650f59e54cfeecd7d947700";

// Subdirectory inside the llama.cpp checkout where omnivoice sources
// land. Stable so the CMake graft and the symbol verifier agree.
export const OMNIVOICE_GRAFT_SUBDIR = "omnivoice";

const REQUIRED_PUBLIC_OMNIVOICE_SYMBOLS = Object.freeze([
  "ov_version",
  "ov_last_error",
  "ov_audio_free",
  "ov_init_default_params",
  "ov_tts_default_params",
  "ov_init",
  "ov_free",
  "ov_log_set",
  "ov_synthesize",
  "ov_duration_sec_to_tokens",
]);

function run(cmd, args, opts = {}) {
  const result = spawnSync(cmd, args, {
    stdio: opts.capture ? ["ignore", "pipe", "pipe"] : "inherit",
    cwd: opts.cwd,
    env: { ...process.env, ...opts.env },
    encoding: "utf8",
  });
  if (result.status !== 0) {
    const detail = opts.capture
      ? `\nstdout:\n${result.stdout || ""}\nstderr:\n${result.stderr || ""}`
      : "";
    throw new Error(
      `[omnivoice-fuse] ${cmd} ${args.join(" ")} failed with ${result.status}${detail}`,
    );
  }
  return result.stdout?.trim() ?? "";
}

function copyDirRecursive(src, dst) {
  fs.mkdirSync(dst, { recursive: true });
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    const from = path.join(src, entry.name);
    const to = path.join(dst, entry.name);
    if (entry.isDirectory()) {
      copyDirRecursive(from, to);
    } else if (entry.isFile() || entry.isSymbolicLink()) {
      fs.copyFileSync(from, to);
    }
  }
}

function replaceBetween(source, startMarker, endMarker, replacement) {
  const start = source.indexOf(startMarker);
  if (start < 0) {
    throw new Error(`[omnivoice-fuse] compatibility patch anchor not found: ${startMarker}`);
  }
  const end = source.indexOf(endMarker, start);
  if (end < 0) {
    throw new Error(`[omnivoice-fuse] compatibility patch end anchor not found: ${endMarker}`);
  }
  return source.slice(0, start) + replacement + source.slice(end);
}

function writeMiladyFfiAdapter({ graftRoot, commit }) {
  const ffiHeaderSrc = new URL("./ffi.h", import.meta.url).pathname;
  const ffiHeaderDst = path.join(graftRoot, "src", "ffi.h");
  fs.copyFileSync(ffiHeaderSrc, ffiHeaderDst);
  fs.writeFileSync(
    path.join(graftRoot, "src", "eliza-inference-ffi.cpp"),
    `// Generated by omnivoice-fuse/prepare.mjs.
// C ABI bridge between libelizainference and omnivoice.cpp.

#include "ffi.h"
#include "omnivoice.h"
#include "llama.h"
#include "mtmd.h"
#include "mtmd-helper.h"

#include <algorithm>
#include <atomic>
#include <cerrno>
#include <cctype>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <filesystem>
#include <memory>
#include <mutex>
#include <new>
#include <string>
#include <thread>
#include <vector>

struct EliInferenceContext {
    std::string bundle_dir;
    std::string tts_model_path;
    std::string codec_model_path;
    std::string asr_model_path;
    std::string asr_mmproj_path;
    ov_context * ov = nullptr;
    llama_model * asr_model = nullptr;
    llama_context * asr_lctx = nullptr;
    mtmd_context * asr_mtmd = nullptr;
    llama_sampler * asr_sampler = nullptr;
    int asr_sample_rate = 0;
    int asr_n_batch = 512;
    std::mutex tts_mutex;
    std::mutex asr_mutex;
    // ABI v2: hard-cancel flag for an in-flight TTS forward pass. Set by
    // eliza_inference_cancel_tts (which does NOT hold tts_mutex — it must
    // be able to interrupt a running synthesize) and checked at every
    // chunk boundary by the streaming/batch TTS path.
    std::atomic<bool> tts_cancel{false};
    // ABI v2: native DFlash verifier callback. Registered via
    // eliza_inference_set_verifier_callback; fired by the in-process
    // speculative loop (the unified server path). verifier_mutex guards
    // registration so a re-register can't race a firing.
    std::mutex verifier_mutex;
    eliza_verifier_cb verifier_cb = nullptr;
    void * verifier_user_data = nullptr;
};

// ABI v2: streaming ASR session. Owns a resampled PCM accumulator and
// shares the context's ASR model/mtmd/sampler under ctx->asr_mutex for
// each decode pass. feed() appends; partial()/finish() run a windowed
// decode over the accumulated audio. Re-decoding the whole window each
// time is acceptable for the short conversational utterances Eliza-1
// targets; a future revision can do incremental KV reuse.
struct EliAsrStream {
    EliInferenceContext * ctx = nullptr;
    int sample_rate_hz = 0;
    std::vector<float> pcm;       // resampled to ctx->asr_sample_rate
    bool finished = false;
};

static char * eliza_strdup(const std::string & s) {
    char * out = (char *) std::malloc(s.size() + 1);
    if (!out) return nullptr;
    std::memcpy(out, s.c_str(), s.size() + 1);
    return out;
}

static void eliza_set_error(char ** out_error, const std::string & msg) {
    if (!out_error) return;
    *out_error = eliza_strdup(msg);
}

static bool eliza_is_region(const char * region_name) {
    return region_name &&
        (std::strcmp(region_name, "tts") == 0 ||
         std::strcmp(region_name, "asr") == 0 ||
         std::strcmp(region_name, "text") == 0 ||
         std::strcmp(region_name, "dflash") == 0);
}

static std::vector<std::string> eliza_find_ggufs(const std::filesystem::path & dir) {
    std::vector<std::string> out;
    std::error_code ec;
    if (!std::filesystem::exists(dir, ec) || !std::filesystem::is_directory(dir, ec)) return out;
    for (const auto & entry : std::filesystem::recursive_directory_iterator(dir, ec)) {
        if (ec) break;
        if (!entry.is_regular_file(ec)) continue;
        const auto path = entry.path();
        if (path.extension() == ".gguf") out.push_back(path.string());
    }
    std::sort(out.begin(), out.end());
    return out;
}

static std::string eliza_lower_ascii(std::string value) {
    std::transform(value.begin(), value.end(), value.begin(), [](unsigned char c) {
        return (char) std::tolower(c);
    });
    return value;
}

static bool eliza_pick_voice_files(
    const std::filesystem::path & bundle_dir,
    std::string & tts_model,
    std::string & codec_model) {
    std::vector<std::string> tts = eliza_find_ggufs(bundle_dir / "tts");
    std::vector<std::string> codec = eliza_find_ggufs(bundle_dir / "codec");
    if (tts.empty()) tts = eliza_find_ggufs(bundle_dir / "voice");
    if (tts.empty()) return false;
    tts_model = tts[0];
    if (!codec.empty()) {
        codec_model = codec[0];
    } else if (tts.size() > 1) {
        codec_model = tts[1];
    } else {
        codec_model = tts_model;
    }
    return true;
}

static bool eliza_pick_asr_files(
    const std::filesystem::path & bundle_dir,
    std::string & asr_model,
    std::string & asr_mmproj) {
    const auto asr_dir = bundle_dir / "asr";
    std::error_code ec;
    const auto canonical_model = asr_dir / "eliza-1-asr.gguf";
    const auto canonical_mmproj = asr_dir / "eliza-1-asr-mmproj.gguf";
    if (std::filesystem::is_regular_file(canonical_model, ec) &&
        std::filesystem::is_regular_file(canonical_mmproj, ec)) {
        asr_model = canonical_model.string();
        asr_mmproj = canonical_mmproj.string();
        return true;
    }

    std::vector<std::string> asr = eliza_find_ggufs(asr_dir);
    std::vector<std::string> model_candidates;
    std::vector<std::string> mmproj_candidates;
    for (const auto & candidate : asr) {
        const std::string filename = eliza_lower_ascii(std::filesystem::path(candidate).filename().string());
        if (filename.find("mmproj") != std::string::npos) {
            mmproj_candidates.push_back(candidate);
        } else if (filename.find("tokenizer") == std::string::npos &&
                   filename.find("support") == std::string::npos &&
                   filename.find("vocab") == std::string::npos) {
            model_candidates.push_back(candidate);
        }
    }
    if (asr_model.empty() && model_candidates.size() == 1) {
        asr_model = model_candidates[0];
    }
    if (asr_mmproj.empty() && mmproj_candidates.size() == 1) {
        asr_mmproj = mmproj_candidates[0];
    }
    return !asr_model.empty() && !asr_mmproj.empty();
}

static std::once_flag eliza_llama_backend_once;

static int eliza_thread_count(bool batch) {
    unsigned int hw = std::thread::hardware_concurrency();
    if (hw == 0) hw = 4;
    const unsigned int cap = batch ? 8 : 4;
    return (int) std::max(1u, std::min(hw, cap));
}

static std::vector<float> eliza_resample_linear(
    const float * pcm,
    size_t n_samples,
    int source_rate,
    int target_rate) {
    if (source_rate == target_rate || n_samples <= 1) {
        return std::vector<float>(pcm, pcm + n_samples);
    }
    const double scale = (double) target_rate / (double) source_rate;
    const size_t out_samples = std::max<size_t>(1, (size_t) std::llround((double) n_samples * scale));
    std::vector<float> out(out_samples);
    for (size_t i = 0; i < out_samples; ++i) {
        const double src = (double) i * (double) source_rate / (double) target_rate;
        const size_t lo = std::min((size_t) std::floor(src), n_samples - 1);
        const size_t hi = std::min(lo + 1, n_samples - 1);
        const float t = (float) (src - (double) lo);
        out[i] = pcm[lo] * (1.0f - t) + pcm[hi] * t;
    }
    return out;
}

static std::string eliza_llama_token_piece(const llama_vocab * vocab, llama_token token) {
    char small[256];
    int32_t n = llama_token_to_piece(vocab, token, small, (int32_t) sizeof(small), 0, false);
    if (n > 0) return std::string(small, (size_t) n);
    if (n == 0) return "";
    std::string buf((size_t) -n, '\\0');
    n = llama_token_to_piece(vocab, token, buf.data(), (int32_t) buf.size(), 0, false);
    if (n > 0) return std::string(buf.data(), (size_t) n);
    return "";
}

static std::string eliza_format_asr_prompt(llama_model * model) {
    (void) model;
    // Qwen3-ASR's generation prompt is intentionally minimal: the audio
    // placeholder is the entire user turn and decoding starts immediately
    // at the assistant turn. Extra natural-language instructions cause
    // role-token chatter instead of a clean transcript.
    return std::string("<|im_start|>user\\n") +
        mtmd_default_marker() +
        "<|im_end|>\\n<|im_start|>assistant\\n";
}

static std::string eliza_trim_ascii(std::string value) {
    auto is_space = [](unsigned char c) {
        return c == ' ' || c == '\\n' || c == '\\r' || c == '\\t';
    };
    while (!value.empty() && is_space((unsigned char) value.front())) {
        value.erase(value.begin());
    }
    while (!value.empty() && is_space((unsigned char) value.back())) {
        value.pop_back();
    }
    return value;
}

static std::string eliza_clean_asr_transcript(std::string transcript) {
    const std::string asr_marker = "<asr_text>";
    size_t marker = transcript.find(asr_marker);
    if (marker != std::string::npos) {
        transcript = transcript.substr(marker + asr_marker.size());
    }
    const char * sentinels[] = {
        "<|im_end|>",
        "<|endoftext|>",
        "</s>",
    };
    for (const char * sentinel : sentinels) {
        size_t pos = transcript.find(sentinel);
        if (pos != std::string::npos) {
            transcript = transcript.substr(0, pos);
        }
    }
    return eliza_trim_ascii(transcript);
}

static void eliza_free_asr(EliInferenceContext * ctx) {
    if (!ctx) return;
    if (ctx->asr_sampler) {
        llama_sampler_free(ctx->asr_sampler);
        ctx->asr_sampler = nullptr;
    }
    if (ctx->asr_mtmd) {
        mtmd_free(ctx->asr_mtmd);
        ctx->asr_mtmd = nullptr;
    }
    if (ctx->asr_lctx) {
        llama_free(ctx->asr_lctx);
        ctx->asr_lctx = nullptr;
    }
    if (ctx->asr_model) {
        llama_model_free(ctx->asr_model);
        ctx->asr_model = nullptr;
    }
    ctx->asr_sample_rate = 0;
}

static int eliza_load_tts(EliInferenceContext * ctx, char ** out_error) {
    if (!ctx) {
        eliza_set_error(out_error, "[libelizainference] load_tts: ctx is NULL");
        return ELIZA_ERR_INVALID_ARG;
    }
    std::lock_guard<std::mutex> lock(ctx->tts_mutex);
    if (ctx->ov) return ELIZA_OK;
    if (ctx->tts_model_path.empty()) {
        if (!eliza_pick_voice_files(std::filesystem::path(ctx->bundle_dir), ctx->tts_model_path, ctx->codec_model_path)) {
            eliza_set_error(out_error, std::string("[libelizainference] no TTS GGUF found under ") + (std::filesystem::path(ctx->bundle_dir) / "tts").string());
            return ELIZA_ERR_BUNDLE_INVALID;
        }
    }

    ov_init_params params;
    ov_init_default_params(&params);
    params.model_path = ctx->tts_model_path.c_str();
    params.codec_path = ctx->codec_model_path.c_str();
    params.use_fa = true;
    ctx->ov = ov_init(&params);
    if (!ctx->ov) {
        std::string msg = "[libelizainference] ov_init failed: ";
        msg += ov_last_error();
        eliza_set_error(out_error, msg);
        return ELIZA_ERR_FFI_FAULT;
    }
    return ELIZA_OK;
}

static int eliza_load_asr(EliInferenceContext * ctx, char ** out_error) {
    if (!ctx) {
        eliza_set_error(out_error, "[libelizainference] load_asr: ctx is NULL");
        return ELIZA_ERR_INVALID_ARG;
    }
    std::lock_guard<std::mutex> lock(ctx->asr_mutex);
    if (ctx->asr_model && ctx->asr_lctx && ctx->asr_mtmd && ctx->asr_sampler) {
        return ELIZA_OK;
    }
    if (ctx->asr_model_path.empty() || ctx->asr_mmproj_path.empty()) {
        if (!eliza_pick_asr_files(std::filesystem::path(ctx->bundle_dir), ctx->asr_model_path, ctx->asr_mmproj_path)) {
            eliza_set_error(out_error, std::string("[libelizainference] ASR requires both a text GGUF and mmproj GGUF under ") + (std::filesystem::path(ctx->bundle_dir) / "asr").string());
            return ELIZA_ERR_BUNDLE_INVALID;
        }
    }

    std::call_once(eliza_llama_backend_once, []() {
        llama_backend_init();
    });

    llama_model_params mparams = llama_model_default_params();
    mparams.n_gpu_layers = 99;
    mparams.use_mmap = true;
    ctx->asr_model = llama_model_load_from_file(ctx->asr_model_path.c_str(), mparams);
    if (!ctx->asr_model) {
        eliza_free_asr(ctx);
        eliza_set_error(out_error, std::string("[libelizainference] failed to load ASR model: ") + ctx->asr_model_path);
        return ELIZA_ERR_BUNDLE_INVALID;
    }

    llama_context_params cparams = llama_context_default_params();
    cparams.n_ctx = 8192;
    cparams.n_batch = (uint32_t) ctx->asr_n_batch;
    cparams.n_ubatch = (uint32_t) ctx->asr_n_batch;
    cparams.n_threads = eliza_thread_count(false);
    cparams.n_threads_batch = eliza_thread_count(true);
    cparams.flash_attn_type = LLAMA_FLASH_ATTN_TYPE_AUTO;
    ctx->asr_lctx = llama_init_from_model(ctx->asr_model, cparams);
    if (!ctx->asr_lctx) {
        eliza_free_asr(ctx);
        eliza_set_error(out_error, "[libelizainference] failed to initialize ASR llama context");
        return ELIZA_ERR_FFI_FAULT;
    }

    mtmd_context_params aparams = mtmd_context_params_default();
    aparams.use_gpu = true;
    aparams.print_timings = false;
    aparams.n_threads = eliza_thread_count(true);
    aparams.flash_attn_type = LLAMA_FLASH_ATTN_TYPE_AUTO;
    aparams.warmup = true;
    ctx->asr_mtmd = mtmd_init_from_file(ctx->asr_mmproj_path.c_str(), ctx->asr_model, aparams);
    if (!ctx->asr_mtmd) {
        eliza_free_asr(ctx);
        eliza_set_error(out_error, std::string("[libelizainference] failed to load ASR mmproj: ") + ctx->asr_mmproj_path);
        return ELIZA_ERR_BUNDLE_INVALID;
    }
    if (!mtmd_support_audio(ctx->asr_mtmd)) {
        eliza_free_asr(ctx);
        eliza_set_error(out_error, "[libelizainference] ASR mmproj does not report audio support");
        return ELIZA_ERR_BUNDLE_INVALID;
    }
    ctx->asr_sample_rate = mtmd_get_audio_bitrate(ctx->asr_mtmd);
    if (ctx->asr_sample_rate <= 0) {
        eliza_free_asr(ctx);
        eliza_set_error(out_error, "[libelizainference] ASR mmproj returned an invalid audio sample rate");
        return ELIZA_ERR_BUNDLE_INVALID;
    }

    llama_sampler_chain_params sparams = llama_sampler_chain_default_params();
    ctx->asr_sampler = llama_sampler_chain_init(sparams);
    if (!ctx->asr_sampler) {
        eliza_free_asr(ctx);
        eliza_set_error(out_error, "[libelizainference] failed to initialize ASR sampler");
        return ELIZA_ERR_FFI_FAULT;
    }
    llama_sampler_chain_add(ctx->asr_sampler, llama_sampler_init_greedy());
    return ELIZA_OK;
}

// Run one greedy ASR decode pass over already-resampled mono PCM and
// write a cleaned transcript into out_text. Caller MUST hold
// ctx->asr_mutex and have verified the ASR region is loaded. Shared by
// the batch eliza_inference_asr_transcribe and the streaming-ASR
// session (eliza_inference_asr_stream_partial / _finish). Returns the
// transcript byte count (>= 0) or a negative ELIZA_* code.
static int eliza_asr_decode_locked(
    EliInferenceContext * ctx,
    const std::vector<float> & audio,
    char * out_text,
    size_t max_text_bytes,
    char ** out_error) {
    if (audio.empty()) {
        out_text[0] = '\\0';
        return 0;
    }
    std::unique_ptr<mtmd_bitmap, decltype(&mtmd_bitmap_free)> bitmap(
        mtmd_bitmap_init_from_audio(audio.size(), audio.data()),
        mtmd_bitmap_free);
    if (!bitmap) {
        eliza_set_error(out_error, "[libelizainference] asr decode: failed to create audio bitmap");
        return ELIZA_ERR_FFI_FAULT;
    }

    std::string prompt = eliza_format_asr_prompt(ctx->asr_model);
    mtmd_input_text text = { prompt.c_str(), true, true };
    const mtmd_bitmap * bitmaps[] = { bitmap.get() };
    std::unique_ptr<mtmd_input_chunks, decltype(&mtmd_input_chunks_free)> chunks(
        mtmd_input_chunks_init(),
        mtmd_input_chunks_free);
    if (!chunks) {
        eliza_set_error(out_error, "[libelizainference] asr decode: failed to allocate input chunks");
        return ELIZA_ERR_FFI_FAULT;
    }
    int32_t tok_rc = mtmd_tokenize(ctx->asr_mtmd, chunks.get(), &text, bitmaps, 1);
    if (tok_rc != 0) {
        eliza_set_error(out_error, "[libelizainference] asr decode: mtmd_tokenize failed rc=" + std::to_string(tok_rc));
        return ELIZA_ERR_FFI_FAULT;
    }

    llama_memory_clear(llama_get_memory(ctx->asr_lctx), true);
    llama_sampler_reset(ctx->asr_sampler);

    llama_pos n_past = 0;
    int32_t eval_rc = mtmd_helper_eval_chunks(
        ctx->asr_mtmd,
        ctx->asr_lctx,
        chunks.get(),
        n_past,
        0,
        ctx->asr_n_batch,
        true,
        &n_past);
    if (eval_rc != 0) {
        eliza_set_error(out_error, "[libelizainference] asr decode: mtmd_helper_eval_chunks failed rc=" + std::to_string(eval_rc));
        return ELIZA_ERR_FFI_FAULT;
    }

    const llama_vocab * vocab = llama_model_get_vocab(ctx->asr_model);
    std::string transcript;
    transcript.reserve(std::min<size_t>(max_text_bytes, 256));
    const int max_decode_tokens = std::min<int>(
        4096,
        std::max<int>(
            192,
            64 + (int) (((audio.size() + (size_t) ctx->asr_sample_rate - 1) /
                         (size_t) ctx->asr_sample_rate) * 32)));
    bool completed = false;
    for (int i = 0; i < max_decode_tokens; ++i) {
        llama_token token = llama_sampler_sample(ctx->asr_sampler, ctx->asr_lctx, -1);
        if (llama_vocab_is_eog(vocab, token)) {
            completed = true;
            break;
        }
        std::string piece = eliza_llama_token_piece(vocab, token);
        if (!piece.empty()) {
            if (transcript.size() + piece.size() + 1 > max_text_bytes) {
                eliza_set_error(out_error, "[libelizainference] asr decode: output buffer too small");
                return ELIZA_ERR_INVALID_ARG;
            }
            transcript += piece;
            std::string cleaned_partial = eliza_clean_asr_transcript(transcript);
            if (!cleaned_partial.empty()) {
                const char last = cleaned_partial.back();
                const bool sentence_complete = last == '.' || last == '?' || last == '!';
                if (piece.find('\\n') != std::string::npos ||
                    transcript.find("<|im_start|>") != std::string::npos ||
                    transcript.find("<|im_end|>") != std::string::npos ||
                    sentence_complete) {
                    completed = true;
                    break;
                }
            }
        }
        llama_sampler_accept(ctx->asr_sampler, token);
        llama_batch batch = llama_batch_get_one(&token, 1);
        int32_t decode_rc = llama_decode(ctx->asr_lctx, batch);
        if (decode_rc != 0) {
            eliza_set_error(out_error, "[libelizainference] asr decode: llama_decode failed rc=" + std::to_string(decode_rc));
            return ELIZA_ERR_FFI_FAULT;
        }
    }
    if (!completed) {
        std::string cleaned_partial = eliza_clean_asr_transcript(transcript);
        if (cleaned_partial.empty()) {
            eliza_set_error(out_error, "[libelizainference] asr decode: reached token cap before EOG and produced no transcript");
            return ELIZA_ERR_FFI_FAULT;
        }
        transcript = cleaned_partial;
    } else {
        transcript = eliza_clean_asr_transcript(transcript);
    }

    if (transcript.size() + 1 > max_text_bytes) {
        eliza_set_error(out_error, "[libelizainference] asr decode: output buffer too small after transcript normalization");
        return ELIZA_ERR_INVALID_ARG;
    }
    std::memcpy(out_text, transcript.data(), transcript.size());
    out_text[transcript.size()] = '\\0';
    return (int) transcript.size();
}

// Run one OmniVoice forward pass for text_owned and emit the resulting
// PCM in chunks via on_chunk (then once more with is_final=1). Used by
// both eliza_inference_tts_synthesize_stream (real callback) and
// eliza_inference_tts_synthesize (collects chunks into the caller's
// buffer). Honors ctx->tts_cancel between chunks: returns
// ELIZA_ERR_CANCELLED if the cancel flag is set or on_chunk returns
// non-zero, after a final is_final=1 callback. Caller MUST hold
// ctx->tts_mutex and have verified ctx->ov is loaded.
static int eliza_tts_run_chunked_locked(
    EliInferenceContext * ctx,
    const std::string & text_owned,
    const char * speaker_preset_id,
    eliza_tts_chunk_cb on_chunk,
    void * user_data,
    char ** out_error) {
    ov_tts_params params;
    ov_tts_default_params(&params);
    params.text = text_owned.c_str();
    params.instruct = speaker_preset_id ? speaker_preset_id : "";

    ov_audio audio = {};
    ov_status rc = ov_synthesize(ctx->ov, &params, &audio);
    if (rc != OV_STATUS_OK) {
        std::string msg = "[libelizainference] ov_synthesize failed: ";
        msg += ov_last_error();
        ov_audio_free(&audio);
        eliza_set_error(out_error, msg);
        return rc == OV_STATUS_OOM ? ELIZA_ERR_OOM : ELIZA_ERR_FFI_FAULT;
    }
    if (audio.n_samples < 0) {
        ov_audio_free(&audio);
        eliza_set_error(out_error, "[libelizainference] ov_synthesize returned a negative sample count");
        return ELIZA_ERR_FFI_FAULT;
    }

    // OmniVoice's ov_synthesize is a single blocking forward pass — it
    // does not expose a per-frame callback — so "emit PCM as decoded" is
    // realized by handing the decoded PCM to on_chunk in ~120 ms
    // segments at 24 kHz. That is the granularity the JS phrase-chunker
    // + ring buffer consume on a scheduler tick; finer streaming would
    // require an omnivoice.cpp internal hook (tracked as follow-up).
    const size_t total = (size_t) audio.n_samples;
    const size_t kChunkSamples = 2880; // 120 ms @ 24 kHz
    bool cancelled = ctx->tts_cancel.load();
    for (size_t off = 0; !cancelled && off < total; off += kChunkSamples) {
        const size_t n = std::min(kChunkSamples, total - off);
        int cb_rc = on_chunk(audio.samples + off, n, 0, user_data);
        if (cb_rc != 0 || ctx->tts_cancel.load()) {
            cancelled = true;
            break;
        }
    }
    // Final marker (zero-length tail). Always fired — including for a
    // zero-length synthesis and on cancellation — so the consumer can
    // release per-utterance state.
    on_chunk(audio.samples, 0, 1, user_data);
    ov_audio_free(&audio);
    return cancelled ? ELIZA_ERR_CANCELLED : ELIZA_OK;
}

extern "C" {

const char * eliza_inference_abi_version(void) {
    return "2";
}

EliInferenceContext * eliza_inference_create(
    const char * bundle_dir,
    char ** out_error) {
    if (!bundle_dir || bundle_dir[0] == '\\0') {
        eliza_set_error(out_error, "[libelizainference] bundle_dir is required");
        return nullptr;
    }
    std::filesystem::path root(bundle_dir);
    std::error_code ec;
    if (!std::filesystem::exists(root, ec) || !std::filesystem::is_directory(root, ec)) {
        eliza_set_error(out_error, std::string("[libelizainference] bundle_dir does not exist: ") + bundle_dir);
        return nullptr;
    }

    EliInferenceContext * ctx = new (std::nothrow) EliInferenceContext();
    if (!ctx) {
        eliza_set_error(out_error, "[libelizainference] out of memory allocating context");
        return nullptr;
    }
    ctx->bundle_dir = root.string();

    // Metadata-only: heavy voice weights are intentionally loaded by
    // eliza_inference_mmap_acquire("tts") so voice-off does not keep
    // OmniVoice resident.
    return ctx;
}

void eliza_inference_destroy(EliInferenceContext * ctx) {
    if (!ctx) return;
    {
        std::lock_guard<std::mutex> lock(ctx->tts_mutex);
        ov_free(ctx->ov);
        ctx->ov = nullptr;
    }
    {
        std::lock_guard<std::mutex> lock(ctx->asr_mutex);
        eliza_free_asr(ctx);
    }
    delete ctx;
}

int eliza_inference_mmap_acquire(
    EliInferenceContext * ctx,
    const char * region_name,
    char ** out_error) {
    if (!ctx) {
        eliza_set_error(out_error, "[libelizainference] mmap_acquire: ctx is NULL");
        return ELIZA_ERR_INVALID_ARG;
    }
    if (!eliza_is_region(region_name)) {
        eliza_set_error(out_error, "[libelizainference] mmap_acquire: invalid region");
        return ELIZA_ERR_INVALID_ARG;
    }
    if (std::strcmp(region_name, "tts") == 0) {
        return eliza_load_tts(ctx, out_error);
    }
    if (std::strcmp(region_name, "asr") == 0) {
        return eliza_load_asr(ctx, out_error);
    }
    return ELIZA_OK;
}

int eliza_inference_mmap_evict(
    EliInferenceContext * ctx,
    const char * region_name,
    char ** out_error) {
    if (!ctx) {
        eliza_set_error(out_error, "[libelizainference] mmap_evict: ctx is NULL");
        return ELIZA_ERR_INVALID_ARG;
    }
    if (!eliza_is_region(region_name)) {
        eliza_set_error(out_error, "[libelizainference] mmap_evict: invalid region");
        return ELIZA_ERR_INVALID_ARG;
    }
    if (std::strcmp(region_name, "tts") == 0) {
        std::lock_guard<std::mutex> lock(ctx->tts_mutex);
        if (ctx->ov) {
            ov_free(ctx->ov);
            ctx->ov = nullptr;
        }
    }
    if (std::strcmp(region_name, "asr") == 0) {
        std::lock_guard<std::mutex> lock(ctx->asr_mutex);
        eliza_free_asr(ctx);
    }
    return ELIZA_OK;
}

int eliza_inference_tts_stream_supported(void) {
    return 1;
}

int eliza_inference_tts_synthesize_stream(
    EliInferenceContext * ctx,
    const char * text,
    size_t text_len,
    const char * speaker_preset_id,
    eliza_tts_chunk_cb on_chunk,
    void * user_data,
    char ** out_error) {
    if (!ctx || !on_chunk) {
        eliza_set_error(out_error, "[libelizainference] tts_synthesize_stream: invalid arguments");
        return ELIZA_ERR_INVALID_ARG;
    }
    if (!text || text_len == 0) {
        eliza_set_error(out_error, "[libelizainference] tts_synthesize_stream: text is required");
        return ELIZA_ERR_INVALID_ARG;
    }
    std::lock_guard<std::mutex> lock(ctx->tts_mutex);
    if (!ctx->ov) {
        eliza_set_error(out_error, "[libelizainference] tts_synthesize_stream: TTS region is not acquired; call mmap_acquire(\\\"tts\\\") after arming voice");
        return ELIZA_ERR_INVALID_ARG;
    }
    ctx->tts_cancel.store(false);
    std::string text_owned(text, text_len);
    return eliza_tts_run_chunked_locked(ctx, text_owned, speaker_preset_id, on_chunk, user_data, out_error);
}

int eliza_inference_cancel_tts(
    EliInferenceContext * ctx,
    char ** out_error) {
    if (!ctx) {
        eliza_set_error(out_error, "[libelizainference] cancel_tts: ctx is NULL");
        return ELIZA_ERR_INVALID_ARG;
    }
    // Intentionally does NOT take ctx->tts_mutex — the synthesize call
    // holds it for the duration of the forward pass; we must be able to
    // signal cancellation while it runs. The flag is checked at every
    // chunk boundary.
    ctx->tts_cancel.store(true);
    return ELIZA_OK;
}

int eliza_inference_set_verifier_callback(
    EliInferenceContext * ctx,
    eliza_verifier_cb cb,
    void * user_data,
    char ** out_error) {
    if (!ctx) {
        eliza_set_error(out_error, "[libelizainference] set_verifier_callback: ctx is NULL");
        return ELIZA_ERR_INVALID_ARG;
    }
    std::lock_guard<std::mutex> lock(ctx->verifier_mutex);
    ctx->verifier_cb = cb;
    ctx->verifier_user_data = cb ? user_data : nullptr;
    return ELIZA_OK;
}

int eliza_inference_tts_synthesize(
    EliInferenceContext * ctx,
    const char * text,
    size_t text_len,
    const char * speaker_preset_id,
    float * out_pcm,
    size_t max_samples,
    char ** out_error) {
    if (!ctx || !out_pcm || max_samples == 0) {
        eliza_set_error(out_error, "[libelizainference] tts_synthesize: invalid arguments");
        return ELIZA_ERR_INVALID_ARG;
    }
    if (!text || text_len == 0) {
        eliza_set_error(out_error, "[libelizainference] tts_synthesize: text is required");
        return ELIZA_ERR_INVALID_ARG;
    }

    std::lock_guard<std::mutex> lock(ctx->tts_mutex);
    if (!ctx->ov) {
        eliza_set_error(out_error, "[libelizainference] tts_synthesize: TTS region is not acquired; call mmap_acquire(\\\"tts\\\") after arming voice");
        return ELIZA_ERR_INVALID_ARG;
    }
    ctx->tts_cancel.store(false);

    // Run the same chunked path, collecting the chunks into the caller's
    // buffer. Keeping one decode path means the streaming + batch entries
    // can never diverge.
    struct CollectState {
        float * out;
        size_t cap;
        size_t written;
        bool overflow;
        size_t required;
    } cs = { out_pcm, max_samples, 0, false, 0 };
    auto on_chunk = [](const float * pcm, size_t n, int is_final, void * user_data) -> int {
        auto * st = static_cast<CollectState *>(user_data);
        if (is_final) return 0;
        st->required += n;
        if (st->overflow) return 0;
        if (st->written + n > st->cap) {
            st->overflow = true;
            return 0;
        }
        std::memcpy(st->out + st->written, pcm, n * sizeof(float));
        st->written += n;
        return 0;
    };
    std::string text_owned(text, text_len);
    int rc = eliza_tts_run_chunked_locked(ctx, text_owned, speaker_preset_id, on_chunk, &cs, out_error);
    if (rc < 0) return rc;
    if (cs.overflow) {
        eliza_set_error(out_error,
            "[libelizainference] tts_synthesize: output buffer too small; required samples=" +
            std::to_string(cs.required));
        return ELIZA_ERR_INVALID_ARG;
    }
    return (int) cs.written;
}

int eliza_inference_asr_transcribe(
    EliInferenceContext * ctx,
    const float * pcm,
    size_t n_samples,
    int sample_rate_hz,
    char * out_text,
    size_t max_text_bytes,
    char ** out_error) {
    if (!ctx || !pcm || !out_text || max_text_bytes == 0 || sample_rate_hz <= 0) {
        eliza_set_error(out_error, "[libelizainference] asr_transcribe: invalid arguments");
        return ELIZA_ERR_INVALID_ARG;
    }
    if (n_samples == 0) {
        out_text[0] = '\\0';
        return 0;
    }

    std::lock_guard<std::mutex> lock(ctx->asr_mutex);
    if (!ctx->asr_model || !ctx->asr_lctx || !ctx->asr_mtmd || !ctx->asr_sampler) {
        eliza_set_error(out_error, "[libelizainference] asr_transcribe: ASR region is not acquired; call mmap_acquire(\\\"asr\\\") after arming voice input");
        return ELIZA_ERR_INVALID_ARG;
    }

    std::vector<float> audio = eliza_resample_linear(pcm, n_samples, sample_rate_hz, ctx->asr_sample_rate);
    return eliza_asr_decode_locked(ctx, audio, out_text, max_text_bytes, out_error);
}

/* ---- Streaming ASR (ABI v2) --------------------------------------- */

int eliza_inference_asr_stream_supported(void) {
    return 1;
}

EliAsrStream * eliza_inference_asr_stream_open(
    EliInferenceContext * ctx,
    int sample_rate_hz,
    char ** out_error) {
    if (!ctx) {
        eliza_set_error(out_error, "[libelizainference] asr_stream_open: ctx is NULL");
        return nullptr;
    }
    if (sample_rate_hz <= 0) {
        eliza_set_error(out_error, "[libelizainference] asr_stream_open: sample_rate_hz must be positive");
        return nullptr;
    }
    {
        std::lock_guard<std::mutex> lock(ctx->asr_mutex);
        if (!ctx->asr_model || !ctx->asr_lctx || !ctx->asr_mtmd || !ctx->asr_sampler) {
            eliza_set_error(out_error, "[libelizainference] asr_stream_open: ASR region is not acquired; call mmap_acquire(\\\"asr\\\") after arming voice input");
            return nullptr;
        }
    }
    EliAsrStream * stream = new (std::nothrow) EliAsrStream();
    if (!stream) {
        eliza_set_error(out_error, "[libelizainference] asr_stream_open: out of memory");
        return nullptr;
    }
    stream->ctx = ctx;
    stream->sample_rate_hz = sample_rate_hz;
    return stream;
}

int eliza_inference_asr_stream_feed(
    EliAsrStream * stream,
    const float * pcm,
    size_t n_samples,
    char ** out_error) {
    if (!stream || (!pcm && n_samples > 0)) {
        eliza_set_error(out_error, "[libelizainference] asr_stream_feed: invalid arguments");
        return ELIZA_ERR_INVALID_ARG;
    }
    if (stream->finished) {
        eliza_set_error(out_error, "[libelizainference] asr_stream_feed: session already finished");
        return ELIZA_ERR_INVALID_ARG;
    }
    if (n_samples == 0) return 0;
    std::vector<float> resampled = eliza_resample_linear(
        pcm, n_samples, stream->sample_rate_hz, stream->ctx->asr_sample_rate);
    stream->pcm.insert(stream->pcm.end(), resampled.begin(), resampled.end());
    return (int) n_samples;
}

static int eliza_asr_stream_decode(
    EliAsrStream * stream,
    char * out_text,
    size_t max_text_bytes,
    int * out_tokens,
    size_t * io_n_tokens,
    char ** out_error) {
    if (!stream || !out_text || max_text_bytes == 0) {
        eliza_set_error(out_error, "[libelizainference] asr_stream decode: invalid arguments");
        return ELIZA_ERR_INVALID_ARG;
    }
    EliInferenceContext * ctx = stream->ctx;
    std::lock_guard<std::mutex> lock(ctx->asr_mutex);
    if (!ctx->asr_model || !ctx->asr_lctx || !ctx->asr_mtmd || !ctx->asr_sampler) {
        eliza_set_error(out_error, "[libelizainference] asr_stream decode: ASR region was evicted mid-session");
        return ELIZA_ERR_INVALID_ARG;
    }
    int rc = eliza_asr_decode_locked(ctx, stream->pcm, out_text, max_text_bytes, out_error);
    if (rc < 0) return rc;
    if (out_tokens && io_n_tokens && *io_n_tokens > 0) {
        const llama_vocab * vocab = llama_model_get_vocab(ctx->asr_model);
        const std::string transcript(out_text, (size_t) rc);
        std::vector<llama_token> ids((size_t) transcript.size() + 8);
        int32_t n = llama_tokenize(
            vocab, transcript.c_str(), (int32_t) transcript.size(),
            ids.data(), (int32_t) ids.size(), false, false);
        if (n < 0) {
            ids.resize((size_t) (-n));
            n = llama_tokenize(
                vocab, transcript.c_str(), (int32_t) transcript.size(),
                ids.data(), (int32_t) ids.size(), false, false);
        }
        if (n < 0) n = 0;
        const size_t copy = std::min((size_t) n, *io_n_tokens);
        for (size_t i = 0; i < copy; ++i) out_tokens[i] = (int) ids[i];
        *io_n_tokens = copy;
    } else if (io_n_tokens) {
        *io_n_tokens = 0;
    }
    return rc;
}

int eliza_inference_asr_stream_partial(
    EliAsrStream * stream,
    char * out_text,
    size_t max_text_bytes,
    int * out_tokens,
    size_t * io_n_tokens,
    char ** out_error) {
    return eliza_asr_stream_decode(stream, out_text, max_text_bytes, out_tokens, io_n_tokens, out_error);
}

int eliza_inference_asr_stream_finish(
    EliAsrStream * stream,
    char * out_text,
    size_t max_text_bytes,
    int * out_tokens,
    size_t * io_n_tokens,
    char ** out_error) {
    if (!stream) {
        eliza_set_error(out_error, "[libelizainference] asr_stream_finish: stream is NULL");
        return ELIZA_ERR_INVALID_ARG;
    }
    int rc = eliza_asr_stream_decode(stream, out_text, max_text_bytes, out_tokens, io_n_tokens, out_error);
    stream->finished = true;
    return rc;
}

void eliza_inference_asr_stream_close(EliAsrStream * stream) {
    delete stream;
}

void eliza_inference_free_string(char * str) {
    std::free(str);
}

} // extern "C"
`,
    "utf8",
  );
}

function hasFunctionDeclaration(source, name) {
  return new RegExp(`\\b${name}\\s*\\(`).test(source);
}

function hasFunctionDefinition(source, name) {
  return new RegExp(`(?:^|\\n)[^\\n;{}]*\\b${name}\\s*\\(`).test(source);
}

function inspectPreparedOmnivoiceSurface({ graftRoot }) {
  const srcRoot = path.join(graftRoot, "src");
  const headerPath = path.join(srcRoot, "omnivoice.h");
  const implPath = path.join(srcRoot, "omnivoice.cpp");
  const adapterPath = path.join(srcRoot, "eliza-inference-ffi.cpp");
  for (const file of [headerPath, implPath, adapterPath]) {
    if (!fs.existsSync(file)) {
      throw new Error(
        `[omnivoice-fuse] prepared graft missing ${file}; refusing stub-only fusion`,
      );
    }
  }

  const header = fs.readFileSync(headerPath, "utf8");
  const impl = fs.readFileSync(implPath, "utf8");
  const adapter = fs.readFileSync(adapterPath, "utf8");
  const missingHeaderSymbols = REQUIRED_PUBLIC_OMNIVOICE_SYMBOLS.filter(
    (symbol) => !hasFunctionDeclaration(header, symbol),
  );
  if (missingHeaderSymbols.length > 0) {
    throw new Error(
      `[omnivoice-fuse] prepared omnivoice.h missing required public symbol(s): ${missingHeaderSymbols.join(", ")}. Pin is not compatible with libelizainference ABI v1.`,
    );
  }

  const missingImplSymbols = REQUIRED_PUBLIC_OMNIVOICE_SYMBOLS.filter(
    (symbol) => !hasFunctionDefinition(impl, symbol),
  );
  if (missingImplSymbols.length > 0) {
    throw new Error(
      `[omnivoice-fuse] prepared omnivoice.cpp missing required implementation symbol(s): ${missingImplSymbols.join(", ")}. Refusing to build a header-only or stub-only graft.`,
    );
  }

  const adapterRequiredCalls = [
    "ov_init_default_params",
    "ov_init",
    "ov_free",
    "ov_tts_default_params",
    "ov_synthesize",
    "ov_audio_free",
    "ov_last_error",
    "eliza_inference_asr_transcribe",
    // ABI v2: the adapter must define the full streaming voice surface.
    "eliza_inference_tts_synthesize_stream",
    "eliza_inference_tts_stream_supported",
    "eliza_inference_cancel_tts",
    "eliza_inference_set_verifier_callback",
    "eliza_inference_asr_stream_supported",
    "eliza_inference_asr_stream_open",
    "eliza_inference_asr_stream_feed",
    "eliza_inference_asr_stream_partial",
    "eliza_inference_asr_stream_finish",
    "eliza_inference_asr_stream_close",
    "mtmd_init_from_file",
    "mtmd_tokenize",
    "mtmd_helper_eval_chunks",
    "llama_decode",
    "llama_sampler_sample",
  ];
  const missingAdapterCalls = adapterRequiredCalls.filter(
    (symbol) => !hasFunctionDeclaration(adapter, symbol),
  );
  if (missingAdapterCalls.length > 0) {
    throw new Error(
      `[omnivoice-fuse] generated libelizainference adapter is not wired to OmniVoice call(s): ${missingAdapterCalls.join(", ")}`,
    );
  }

  return {
    header: path.relative(graftRoot, headerPath),
    implementation: path.relative(graftRoot, implPath),
    adapter: path.relative(graftRoot, adapterPath),
    requiredPublicSymbols: [...REQUIRED_PUBLIC_OMNIVOICE_SYMBOLS],
  };
}

function applyMiladyGgmlCompatibility({ graftRoot, commit }) {
  const dacPath = path.join(graftRoot, "src", "dac-decoder.h");
  let source = fs.readFileSync(dacPath, "utf8");
  const loadCtw = `// Load ConvTranspose1d weights in milady ggml's native kernel layout.
// Source-side layout is (IC, OC, K), represented by ggml as ne=(K, OC, IC).
// milady ggml already ships GGML_OP_CONV_TRANSPOSE_1D for CPU/CUDA/Metal/
// Vulkan, while omnivoice's fork used a private col2im_1d op. Keeping the
// native layout lets the fused build share the patched milady ggml without
// adding a second custom op.
static void dac_load_ctw(struct ggml_tensor * dst, const GGUFModel & gf, const std::string & name) {
    struct ggml_tensor * mt = ggml_get_tensor(gf.meta, name.c_str());
    if (!mt) {
        ov_throw("[DAC] tensor '%s' not found (conv_t1 weight)", name.c_str());
    }
    GGML_ASSERT(dst->type == GGML_TYPE_F16);

    const int    K  = (int) mt->ne[0];
    const int    OC = (int) mt->ne[1];
    const int    IC = (int) mt->ne[2];
    const size_t n  = (size_t) IC * (size_t) OC * (size_t) K;

    GGML_ASSERT(dst->ne[0] == K && dst->ne[1] == OC && dst->ne[2] == IC);

    const void * raw = gf_get_data(gf, name.c_str());
    if (mt->type == GGML_TYPE_F16) {
        ggml_backend_tensor_set(dst, raw, 0, n * sizeof(ggml_fp16_t));
        return;
    }

    std::vector<float> f32(n);
    if (mt->type == GGML_TYPE_F32) {
        memcpy(f32.data(), raw, n * sizeof(float));
    } else if (mt->type == GGML_TYPE_BF16) {
        const uint16_t * p = (const uint16_t *) raw;
        for (size_t i = 0; i < n; i++) {
            f32[i] = ggml_bf16_to_fp32(*(const ggml_bf16_t *) &p[i]);
        }
    } else {
        const struct ggml_type_traits * tr = ggml_get_type_traits(mt->type);
        if (!tr || !tr->to_float) {
            ov_throw("[DAC] unsupported conv_t1 weight type %s for '%s'", ggml_type_name(mt->type), name.c_str());
        }
        tr->to_float(raw, f32.data(), (int64_t) n);
    }

    std::vector<ggml_fp16_t> packed(n);
    for (size_t i = 0; i < n; i++) {
        packed[i] = ggml_fp32_to_fp16(f32[i]);
    }
    ggml_backend_tensor_set(dst, packed.data(), 0, n * sizeof(ggml_fp16_t));
}

`;
  source = replaceBetween(
    source,
    "// Pre-permute the ConvTranspose1d weight",
    "// Allocate one snake pair",
    loadCtw,
  );

  const convT = `// ConvTranspose1d using milady ggml's native GGML_OP_CONV_TRANSPOSE_1D.
// The upstream omnivoice fork used a private col2im_1d op with padding.
// milady's native op requires p0=0, so we crop pad samples from both ends
// and then apply output_pad to match the original length contract.
static struct ggml_tensor * dac_conv_t1d(struct ggml_context * ctx,
                                         struct ggml_tensor *  w,
                                         struct ggml_tensor *  b,
                                         struct ggml_tensor *  x,
                                         int                   stride,
                                         int                   pad,
                                         int                   oc,
                                         int                   output_pad) {
    struct ggml_tensor * y = ggml_conv_transpose_1d(ctx, w, x, stride, 0, 1);
    y = ggml_reshape_2d(ctx, y, y->ne[0], y->ne[1]);

    if (pad > 0) {
        const int64_t cropped = y->ne[0] - 2 * (int64_t) pad;
        GGML_ASSERT(cropped > 0);
        GGML_ASSERT(y->ne[1] == oc);
        y = ggml_view_2d(ctx, y, cropped, y->ne[1], y->nb[1], (size_t) pad * y->nb[0]);
        y = ggml_cont(ctx, y);
    }

    if (output_pad > 0) {
        y = ggml_pad(ctx, y, output_pad, 0, 0, 0);
    }

    if (b) {
        struct ggml_tensor * b2d = ggml_reshape_2d(ctx, b, 1, b->ne[0]);
        y                        = ggml_add(ctx, y, b2d);
    }
    return y;
}

`;
  source = replaceBetween(
    source,
    "// ConvTranspose1d via GEMM + col2im_1d",
    "// Residual unit forward:",
    convT,
  );

  source = source.replace(
    "b.ctw = ggml_new_tensor_2d(ctx, GGML_TYPE_F16, b.in_ch, b.kernel * b.out_ch);",
    "b.ctw = ggml_new_tensor_3d(ctx, GGML_TYPE_F16, b.kernel, b.out_ch, b.in_ch);",
  );
  source = source.replace(
    "struct ggml_tensor * ctw;  // [IC, K*OC] bf16",
    "struct ggml_tensor * ctw;  // [K, OC, IC] bf16",
  );
  fs.writeFileSync(dacPath, source, "utf8");

  const codecPath = path.join(graftRoot, "src", "pipeline-codec.cpp");
  let codecSource = fs.readFileSync(codecPath, "utf8");
  const codecBackendAnchor = `    pc->bp                 = bp;
    pc->backend            = bp.backend;
    ggml_backend_t backend = bp.backend;
`;
  if (!codecSource.includes(codecBackendAnchor)) {
    throw new Error(
      `[omnivoice-fuse] compatibility patch anchor not found: pipeline-codec backend selection`,
    );
  }
  codecSource = codecSource.replace(
    codecBackendAnchor,
    `    // Keep the MaskGIT/LM path on the selected accelerator, but pin the
    // audio tokenizer / DAC codec to CPU on Apple Metal. The merged milady
    // ggml Metal DAC decode graph has been observed to stall immediately
    // after "[TTS] Decode"; using CPU here keeps one fused process and one
    // model lifecycle while avoiding the bad Metal codec scheduler path.
    BackendPair codec_bp = bp;
    const char * requested_backend =
        bp.backend ? ggml_backend_name(bp.backend) : "(null)";
    const bool requested_metal =
        requested_backend &&
        (std::strncmp(requested_backend, "MTL", 3) == 0 ||
         std::strstr(requested_backend, "Metal") != nullptr);
    if (requested_metal && bp.cpu_backend) {
        codec_bp.backend = bp.cpu_backend;
        codec_bp.has_gpu = false;
        ov_log(OV_LOG_INFO,
               "[PipelineCodec] Metal codec fallback: requested=%s selected=%s reason=merged-ggml-dac-decode-stall",
               requested_backend, ggml_backend_name(codec_bp.backend));
    }
    pc->bp                 = codec_bp;
    pc->backend            = codec_bp.backend;
    ggml_backend_t backend = codec_bp.backend;
`,
  );
  const codecSchedulerAnchor = "    pc->sched = backend_sched_new(bp, 4096);";
  if (!codecSource.includes(codecSchedulerAnchor)) {
    throw new Error(
      `[omnivoice-fuse] compatibility patch anchor not found: pipeline-codec scheduler backend`,
    );
  }
  codecSource = codecSource.replace(
    codecSchedulerAnchor,
    "    pc->sched = backend_sched_new(codec_bp, 4096);",
  );
  fs.writeFileSync(codecPath, codecSource, "utf8");

  fs.writeFileSync(
    path.join(graftRoot, "src", "version.h"),
    `#pragma once\n#define OMNIVOICE_VERSION "${commit.slice(0, 12)} (milady-fused)"\n`,
    "utf8",
  );
  writeMiladyFfiAdapter({ graftRoot, commit });
}

// Ensure a clone of omnivoice.cpp at OMNIVOICE_REF lives under
// <cacheRoot>/omnivoice.cpp. Returns the resolved HEAD commit.
function ensureOmnivoiceCheckout(cacheRoot, ref) {
  const checkoutDir = path.join(cacheRoot, "omnivoice.cpp");
  if (fs.existsSync(path.join(checkoutDir, ".git"))) {
    run("git", ["fetch", "--depth=1", "origin", ref], { cwd: checkoutDir });
    run("git", ["checkout", "FETCH_HEAD"], { cwd: checkoutDir });
  } else {
    fs.mkdirSync(cacheRoot, { recursive: true });
    // Some refs (raw commit hashes) don't work with `--branch`. Try the
    // tag/branch path first, then fall back to a full clone + checkout
    // by hash. Either way, the commit pin must resolve.
    const looksLikeHash = /^[0-9a-f]{7,40}$/i.test(ref);
    if (looksLikeHash) {
      run("git", ["clone", OMNIVOICE_REPO, checkoutDir]);
      run("git", ["checkout", ref], { cwd: checkoutDir });
    } else {
      run("git", [
        "clone",
        "--depth=1",
        "--branch",
        ref,
        OMNIVOICE_REPO,
        checkoutDir,
      ]);
    }
  }
  const head = run("git", ["rev-parse", "HEAD"], {
    cwd: checkoutDir,
    capture: true,
  });
  return { checkoutDir, head };
}

// Read the omnivoice ggml submodule's recorded commit from the parent
// repo's index, without actually fetching the submodule contents. This
// is the value we explicitly DO NOT use in the fused build — we record
// it for the manifest and verifier.
function readOmnivoiceGgmlSubmoduleCommit(checkoutDir) {
  const result = spawnSync("git", ["ls-tree", "HEAD", "ggml"], {
    cwd: checkoutDir,
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
  });
  if (result.status !== 0) return null;
  const match = /^160000\s+commit\s+([0-9a-f]{40})/.exec(
    result.stdout || "",
  );
  return match ? match[1] : null;
}

// Apply every `omnivoice-fuse/patches/*.patch` to the merged tree, in
// lexical order. Hard error on any failure — there is no fallback.
function applyPatches({ patchesDir, llamaCppRoot }) {
  if (!fs.existsSync(patchesDir)) return [];
  const patches = fs
    .readdirSync(patchesDir)
    .filter((name) => name.endsWith(".patch"))
    .sort();
  const applied = [];
  for (const name of patches) {
    const patchPath = path.join(patchesDir, name);
    const sentinel = path.join(
      llamaCppRoot,
      ".omnivoice-fuse-patch-applied",
      name,
    );
    if (fs.existsSync(sentinel)) {
      applied.push({ name, status: "already-applied" });
      continue;
    }
    run("git", ["apply", "--check", patchPath], { cwd: llamaCppRoot });
    run("git", ["apply", patchPath], { cwd: llamaCppRoot });
    fs.mkdirSync(path.dirname(sentinel), { recursive: true });
    fs.writeFileSync(sentinel, `${new Date().toISOString()}\n`);
    applied.push({ name, status: "applied" });
  }
  return applied;
}

const QWEN3A_MODEL_CPP = `#include "models.h"

ggml_cgraph * clip_graph_qwen3a::build() {
    ggml_tensor * inp = build_inp_raw(1);

    {
        inp = ggml_conv_2d(ctx0, model.conv2d_1_w, inp, 2, 2, 1, 1, 1, 1);
        inp = ggml_add(ctx0, inp, model.conv2d_1_b);
        inp = ggml_gelu_erf(ctx0, inp);

        inp = ggml_conv_2d(ctx0, model.conv2d_2_w, inp, 2, 2, 1, 1, 1, 1);
        inp = ggml_add(ctx0, inp, model.conv2d_2_b);
        inp = ggml_gelu_erf(ctx0, inp);

        inp = ggml_conv_2d(ctx0, model.conv2d_3_w, inp, 2, 2, 1, 1, 1, 1);
        inp = ggml_add(ctx0, inp, model.conv2d_3_b);
        inp = ggml_gelu_erf(ctx0, inp);

        cb(inp, "after_conv_blocks", -1);

        const int64_t n_pos_after_conv = inp->ne[0];
        const int64_t n_mel_after_conv = inp->ne[1];

        inp = ggml_cont(ctx0, ggml_permute(ctx0, inp, 0, 2, 3, 1));
        inp = ggml_reshape_2d(ctx0, inp, n_pos_after_conv, n_mel_after_conv * inp->ne[3]);
        inp = ggml_cont(ctx0, ggml_transpose(ctx0, inp));

        inp = ggml_mul_mat(ctx0, model.conv_out_w, inp);
        if (model.conv_out_b) {
            inp = ggml_add(ctx0, inp, model.conv_out_b);
        }
        cb(inp, "after_conv_out", -1);
    }

    auto n_pos = inp->ne[1];
    ggml_tensor * pos_embd_selected = ggml_view_2d(
        ctx0, model.position_embeddings,
        model.position_embeddings->ne[0], n_pos,
        model.position_embeddings->nb[1], 0);

    ggml_tensor * cur = build_vit(
        inp,
        n_pos,
        NORM_TYPE_NORMAL,
        hparams.ffn_op,
        pos_embd_selected,
        nullptr);

    cb(cur, "after_transformer", -1);

    cur = build_ffn(cur,
        model.mm_1_w, model.mm_1_b,
        nullptr, nullptr,
        model.mm_2_w, model.mm_2_b,
        FFN_GELU_ERF,
        -1);

    cb(cur, "projected", -1);
    ggml_build_forward_expand(gf, cur);
    return gf;
}
`;

function replaceRequired(source, from, to, label) {
  if (!source.includes(from)) {
    throw new Error(`[omnivoice-fuse] qwen3a patch anchor not found: ${label}`);
  }
  return source.replace(from, to);
}

function applyMiladyQwen3AsrMtmdSupport({ llamaCppRoot }) {
  const touched = [];

  const clipImplPath = path.join(llamaCppRoot, "tools", "mtmd", "clip-impl.h");
  let clipImpl = fs.readFileSync(clipImplPath, "utf8");
  if (!clipImpl.includes("PROJECTOR_TYPE_QWEN3A")) {
    clipImpl = replaceRequired(
      clipImpl,
      "    PROJECTOR_TYPE_QWEN2A,\n    PROJECTOR_TYPE_GLMA,",
      "    PROJECTOR_TYPE_QWEN2A,\n    PROJECTOR_TYPE_QWEN3A,\n    PROJECTOR_TYPE_GLMA,",
      "clip-impl enum",
    );
  }
  if (!clipImpl.includes('{ PROJECTOR_TYPE_QWEN3A,    "qwen3a"}')) {
    clipImpl = replaceRequired(
      clipImpl,
      '    { PROJECTOR_TYPE_QWEN2A,    "qwen2a"},\n    { PROJECTOR_TYPE_GLMA,      "glma"},',
      '    { PROJECTOR_TYPE_QWEN2A,    "qwen2a"},\n    { PROJECTOR_TYPE_QWEN3A,    "qwen3a"},\n    { PROJECTOR_TYPE_GLMA,      "glma"},',
      "clip-impl name map",
    );
  }
  if (!clipImpl.includes("#define TN_CONV2D")) {
    clipImpl = replaceRequired(
      clipImpl,
      '#define TN_CONV1D       "a.conv1d.%d.%s"\n#define TN_MM_AUDIO_MLP',
      '#define TN_CONV1D       "a.conv1d.%d.%s"\n#define TN_CONV2D       "a.conv2d.%d.%s"\n#define TN_CONV_OUT     "a.conv_out.%s"\n#define TN_MM_AUDIO_MLP',
      "clip-impl conv2d tensor names",
    );
  }
  if (clipImpl !== fs.readFileSync(clipImplPath, "utf8")) {
    fs.writeFileSync(clipImplPath, clipImpl, "utf8");
    touched.push("tools/mtmd/clip-impl.h");
  }

  const clipModelPath = path.join(llamaCppRoot, "tools", "mtmd", "clip-model.h");
  let clipModel = fs.readFileSync(clipModelPath, "utf8");
  if (!clipModel.includes("conv_out_w")) {
    clipModel = replaceRequired(
      clipModel,
      "    ggml_tensor * conv1d_2_w = nullptr;\n    ggml_tensor * conv1d_2_b = nullptr;\n    ggml_tensor * mm_norm_pre_w = nullptr;",
      "    ggml_tensor * conv1d_2_w = nullptr;\n    ggml_tensor * conv1d_2_b = nullptr;\n    ggml_tensor * conv_out_w = nullptr;\n    ggml_tensor * conv_out_b = nullptr;\n    ggml_tensor * mm_norm_pre_w = nullptr;",
      "clip-model conv_out fields",
    );
  }
  if (!clipModel.includes("// qwen3a")) {
    clipModel = replaceRequired(
      clipModel,
      "    ggml_tensor * mm_norm_mid_w = nullptr;\n\n    // cogvlm",
      "    ggml_tensor * mm_norm_mid_w = nullptr;\n\n    // qwen3a\n    ggml_tensor * conv2d_1_w = nullptr;\n    ggml_tensor * conv2d_1_b = nullptr;\n    ggml_tensor * conv2d_2_w = nullptr;\n    ggml_tensor * conv2d_2_b = nullptr;\n    ggml_tensor * conv2d_3_w = nullptr;\n    ggml_tensor * conv2d_3_b = nullptr;\n\n    // cogvlm",
      "clip-model qwen3a fields",
    );
  }
  if (clipModel !== fs.readFileSync(clipModelPath, "utf8")) {
    fs.writeFileSync(clipModelPath, clipModel, "utf8");
    touched.push("tools/mtmd/clip-model.h");
  }

  const modelsHeaderPath = path.join(llamaCppRoot, "tools", "mtmd", "models", "models.h");
  let modelsHeader = fs.readFileSync(modelsHeaderPath, "utf8");
  if (!modelsHeader.includes("clip_graph_qwen3a")) {
    modelsHeader = replaceRequired(
      modelsHeader,
      "struct clip_graph_kimik25 : clip_graph {",
      "struct clip_graph_qwen3a : clip_graph {\n    clip_graph_qwen3a(clip_ctx * ctx, const clip_image_f32 & img) : clip_graph(ctx, img) {}\n    ggml_cgraph * build() override;\n};\n\nstruct clip_graph_kimik25 : clip_graph {",
      "models.h qwen3a graph declaration",
    );
    fs.writeFileSync(modelsHeaderPath, modelsHeader, "utf8");
    touched.push("tools/mtmd/models/models.h");
  }

  const qwen3aPath = path.join(llamaCppRoot, "tools", "mtmd", "models", "qwen3a.cpp");
  if (!fs.existsSync(qwen3aPath)) {
    fs.writeFileSync(qwen3aPath, QWEN3A_MODEL_CPP, "utf8");
    touched.push("tools/mtmd/models/qwen3a.cpp");
  }

  const mtmdCmakePath = path.join(llamaCppRoot, "tools", "mtmd", "CMakeLists.txt");
  let mtmdCmake = fs.readFileSync(mtmdCmakePath, "utf8");
  if (!mtmdCmake.includes("models/qwen3a.cpp")) {
    mtmdCmake = replaceRequired(
      mtmdCmake,
      "            models/qwen3vl.cpp\n            models/siglip.cpp",
      "            models/qwen3vl.cpp\n            models/qwen3a.cpp\n            models/siglip.cpp",
      "mtmd CMake qwen3a source",
    );
    fs.writeFileSync(mtmdCmakePath, mtmdCmake, "utf8");
    touched.push("tools/mtmd/CMakeLists.txt");
  }

  const clipPath = path.join(llamaCppRoot, "tools", "mtmd", "clip.cpp");
  let clip = fs.readFileSync(clipPath, "utf8");
  if (!clip.includes("clip_graph_qwen3a")) {
    clip = replaceRequired(
      clip,
      "        case PROJECTOR_TYPE_ULTRAVOX:\n        case PROJECTOR_TYPE_VOXTRAL:\n        case PROJECTOR_TYPE_QWEN2A:",
      "        case PROJECTOR_TYPE_QWEN3A:\n            {\n                builder = std::make_unique<clip_graph_qwen3a>(ctx, img);\n            } break;\n        case PROJECTOR_TYPE_ULTRAVOX:\n        case PROJECTOR_TYPE_VOXTRAL:\n        case PROJECTOR_TYPE_QWEN2A:",
      "clip.cpp qwen3a graph dispatch",
    );
  }
  if (!clip.includes("case PROJECTOR_TYPE_QWEN3A:\n                case PROJECTOR_TYPE_GLMA")) {
    clip = replaceRequired(
      clip,
      "                case PROJECTOR_TYPE_QWEN2A:\n                case PROJECTOR_TYPE_GLMA:",
      "                case PROJECTOR_TYPE_QWEN2A:\n                case PROJECTOR_TYPE_QWEN3A:\n                case PROJECTOR_TYPE_GLMA:",
      "clip.cpp qwen3a hparams",
    );
  }
  if (!clip.includes("case PROJECTOR_TYPE_QWEN3A:\n                {\n                    model.conv2d_1_w")) {
    clip = replaceRequired(
      clip,
      "            case PROJECTOR_TYPE_VOXTRAL:\n                {",
      "            case PROJECTOR_TYPE_QWEN3A:\n                {\n                    model.conv2d_1_w = get_tensor(string_format(TN_CONV2D, 1, \"weight\"));\n                    model.conv2d_1_b = get_tensor(string_format(TN_CONV2D, 1, \"bias\"));\n                    model.conv2d_2_w = get_tensor(string_format(TN_CONV2D, 2, \"weight\"));\n                    model.conv2d_2_b = get_tensor(string_format(TN_CONV2D, 2, \"bias\"));\n                    model.conv2d_3_w = get_tensor(string_format(TN_CONV2D, 3, \"weight\"));\n                    model.conv2d_3_b = get_tensor(string_format(TN_CONV2D, 3, \"bias\"));\n                    model.conv_out_w = get_tensor(string_format(TN_CONV_OUT, \"weight\"));\n                    model.conv_out_b = get_tensor(string_format(TN_CONV_OUT, \"bias\"), false);\n                    model.mm_1_w = get_tensor(string_format(TN_MM_AUDIO_MLP, 1, \"weight\"));\n                    model.mm_1_b = get_tensor(string_format(TN_MM_AUDIO_MLP, 1, \"bias\"));\n                    model.mm_2_w = get_tensor(string_format(TN_MM_AUDIO_MLP, 2, \"weight\"));\n                    model.mm_2_b = get_tensor(string_format(TN_MM_AUDIO_MLP, 2, \"bias\"));\n                } break;\n            case PROJECTOR_TYPE_VOXTRAL:\n                {",
      "clip.cpp qwen3a tensor loads",
    );
  }
  if (!clip.includes("case PROJECTOR_TYPE_QWEN3A:\n            {\n                // 3x stride-2 conv2d")) {
    clip = replaceRequired(
      clip,
      "        case PROJECTOR_TYPE_GLMA:\n            {",
      "        case PROJECTOR_TYPE_QWEN3A:\n            {\n                // 3x stride-2 conv2d: each step is floor((n-1)/2)+1\n                int n = img->nx;\n                n = (n - 1) / 2 + 1;\n                n = (n - 1) / 2 + 1;\n                n = (n - 1) / 2 + 1;\n                n_patches = n;\n            } break;\n        case PROJECTOR_TYPE_GLMA:\n            {",
      "clip.cpp qwen3a output token count",
    );
  }
  if (!clip.includes("case PROJECTOR_TYPE_QWEN3A:\n        case PROJECTOR_TYPE_GLMA:\n        case PROJECTOR_TYPE_ULTRAVOX")) {
    clip = replaceRequired(
      clip,
      "        case PROJECTOR_TYPE_QWEN2A:\n        case PROJECTOR_TYPE_GLMA:\n        case PROJECTOR_TYPE_ULTRAVOX:",
      "        case PROJECTOR_TYPE_QWEN2A:\n        case PROJECTOR_TYPE_QWEN3A:\n        case PROJECTOR_TYPE_GLMA:\n        case PROJECTOR_TYPE_ULTRAVOX:",
      "clip.cpp qwen3a input setup",
    );
  }
  if (!clip.includes("case PROJECTOR_TYPE_QWEN3A:\n            return ctx->model.mm_2_w->ne[1];")) {
    clip = replaceRequired(
      clip,
      "        case PROJECTOR_TYPE_QWEN2A:\n            return ctx->model.mm_fc_w->ne[1];\n        case PROJECTOR_TYPE_GLMA:",
      "        case PROJECTOR_TYPE_QWEN2A:\n            return ctx->model.mm_fc_w->ne[1];\n        case PROJECTOR_TYPE_QWEN3A:\n            return ctx->model.mm_2_w->ne[1];\n        case PROJECTOR_TYPE_GLMA:",
      "clip.cpp qwen3a mmproj embedding dim",
    );
  }
  if (!clip.includes("case PROJECTOR_TYPE_QWEN3A:\n        case PROJECTOR_TYPE_GLMA:\n        case PROJECTOR_TYPE_VOXTRAL")) {
    clip = replaceRequired(
      clip,
      "        case PROJECTOR_TYPE_QWEN2A:\n        case PROJECTOR_TYPE_GLMA:\n        case PROJECTOR_TYPE_VOXTRAL:",
      "        case PROJECTOR_TYPE_QWEN2A:\n        case PROJECTOR_TYPE_QWEN3A:\n        case PROJECTOR_TYPE_GLMA:\n        case PROJECTOR_TYPE_VOXTRAL:",
      "clip.cpp qwen3a whisper preprocessor flag",
    );
  }
  if (clip !== fs.readFileSync(clipPath, "utf8")) {
    fs.writeFileSync(clipPath, clip, "utf8");
    touched.push("tools/mtmd/clip.cpp");
  }

  const mtmdPath = path.join(llamaCppRoot, "tools", "mtmd", "mtmd.cpp");
  let mtmd = fs.readFileSync(mtmdPath, "utf8");
  if (!mtmd.includes("case PROJECTOR_TYPE_QWEN3A:\n            case PROJECTOR_TYPE_QWEN25O:")) {
    mtmd = replaceRequired(
      mtmd,
      "            case PROJECTOR_TYPE_QWEN2A:\n            case PROJECTOR_TYPE_QWEN25O:",
      "            case PROJECTOR_TYPE_QWEN2A:\n            case PROJECTOR_TYPE_QWEN3A:\n            case PROJECTOR_TYPE_QWEN25O:",
      "mtmd.cpp qwen3a audio preprocessor",
    );
  }
  if (!mtmd.includes("proj == PROJECTOR_TYPE_QWEN3A")) {
    mtmd = replaceRequired(
      mtmd,
      "        if (proj == PROJECTOR_TYPE_QWEN2A) {",
      "        if (proj == PROJECTOR_TYPE_QWEN2A || proj == PROJECTOR_TYPE_QWEN3A || proj == PROJECTOR_TYPE_QWEN25O) {",
      "mtmd.cpp qwen3a audio special tokens",
    );
  }
  if (mtmd !== fs.readFileSync(mtmdPath, "utf8")) {
    fs.writeFileSync(mtmdPath, mtmd, "utf8");
    touched.push("tools/mtmd/mtmd.cpp");
  }

  return {
    name: "milady-qwen3a-mtmd-backport",
    status: touched.length > 0 ? "applied" : "already-applied",
    files: touched,
  };
}

/**
 * Main entry. Performs the full prepare phase. All errors propagate.
 */
export function prepareOmnivoiceFusion({
  cacheRoot,
  llamaCppRoot,
  omnivoiceRef = OMNIVOICE_REF,
}) {
  if (!cacheRoot) throw new Error("[omnivoice-fuse] cacheRoot is required");
  if (!llamaCppRoot)
    throw new Error("[omnivoice-fuse] llamaCppRoot is required");
  if (!fs.existsSync(path.join(llamaCppRoot, "CMakeLists.txt"))) {
    throw new Error(
      `[omnivoice-fuse] llamaCppRoot=${llamaCppRoot} missing CMakeLists.txt; clone the fork first`,
    );
  }
  if (!fs.existsSync(path.join(llamaCppRoot, "ggml", "CMakeLists.txt"))) {
    throw new Error(
      `[omnivoice-fuse] llamaCppRoot=${llamaCppRoot} missing ggml/CMakeLists.txt; the milady ggml is required for fusion`,
    );
  }

  const { checkoutDir, head } = ensureOmnivoiceCheckout(
    cacheRoot,
    omnivoiceRef,
  );
  const ggmlSubmoduleCommit = readOmnivoiceGgmlSubmoduleCommit(checkoutDir);

  // Validate the omnivoice checkout's surface. Missing pieces => hard
  // error. The runbook requires the operator to investigate, not the
  // build to silently degrade.
  const requiredDirs = ["src", "tools"];
  for (const dir of requiredDirs) {
    const full = path.join(checkoutDir, dir);
    if (!fs.existsSync(full) || !fs.statSync(full).isDirectory()) {
      throw new Error(
        `[omnivoice-fuse] omnivoice checkout at ${checkoutDir} missing required directory '${dir}' — pin ${head} is not usable`,
      );
    }
  }
  // The presence of an entry point we know exists in the pinned commit
  // (and is referenced by every fused build) — sanity check the pin.
  const sentinelHeader = path.join(checkoutDir, "src", "omnivoice.h");
  if (!fs.existsSync(sentinelHeader)) {
    throw new Error(
      `[omnivoice-fuse] omnivoice pin ${head} is missing src/omnivoice.h; refusing to graft an unknown layout`,
    );
  }

  // Stage the merged tree under <llamaCppRoot>/omnivoice/.
  const graftRoot = path.join(llamaCppRoot, OMNIVOICE_GRAFT_SUBDIR);
  // If a previous run left an aborted graft behind, blow it away. The
  // git checkout itself remains untouched — we only own the graft
  // subdirectory.
  fs.rmSync(graftRoot, { recursive: true, force: true });
  fs.mkdirSync(graftRoot, { recursive: true });

  for (const subdir of ["src", "tools"]) {
    copyDirRecursive(
      path.join(checkoutDir, subdir),
      path.join(graftRoot, subdir),
    );
  }
  applyMiladyGgmlCompatibility({ graftRoot, commit: head });
  const sourceSurface = inspectPreparedOmnivoiceSurface({ graftRoot });

  // examples/ is data-only (audio prompts, sample text). Copy on a
  // best-effort basis — the build does not depend on these files. We
  // include them so a developer running llama-omnivoice-server locally
  // has the same demo asset paths the omnivoice CLI tools document.
  const examplesSrc = path.join(checkoutDir, "examples");
  if (fs.existsSync(examplesSrc)) {
    copyDirRecursive(examplesSrc, path.join(graftRoot, "examples"));
  }

  // Hard guarantee: we did NOT bring omnivoice's ggml/ along. The
  // README's "graft, not submodule swap" strategy depends on this.
  const strayGgml = path.join(graftRoot, "ggml");
  if (fs.existsSync(strayGgml)) {
    throw new Error(
      `[omnivoice-fuse] graft staging produced a stray ${strayGgml} — refusing to continue (would create two ggml trees)`,
    );
  }

  // Apply any reconciliation patches keyed to specific drifts.
  const patchesDir = new URL("./patches/", import.meta.url).pathname;
  const qwen3aBackport = applyMiladyQwen3AsrMtmdSupport({ llamaCppRoot });
  const appliedPatches = [
    qwen3aBackport,
    ...applyPatches({ patchesDir, llamaCppRoot }),
  ];

  // Count source files actually grafted, for the manifest.
  let sourceCount = 0;
  const stack = [graftRoot];
  while (stack.length > 0) {
    const dir = stack.pop();
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        stack.push(full);
      } else if (/\.(c|cc|cpp|cxx|h|hpp)$/.test(entry.name)) {
        sourceCount += 1;
      }
    }
  }

  return {
    commit: head,
    ref: omnivoiceRef,
    ggmlSubmoduleCommit,
    graftRoot,
    sourceCount,
    sourceSurface,
    appliedPatches,
  };
}
