/**
 * Clone omnivoice.cpp at the pinned commit, strip its `ggml/` submodule,
 * and copy `src/` + `tools/` + selected `examples/` data into the
 * llama.cpp tree under `<llamaCppRoot>/omnivoice/`.
 *
 * Caller (build-llama-cpp-dflash.mjs):
 *   import { prepareOmnivoiceFusion } from
 *     "./omnivoice-fuse/prepare.mjs";
 *   const { commit, ggmlSubmoduleCommit, sourceCount } =
 *     prepareOmnivoiceFusion({
 *       cacheRoot: "...", // ~/.cache/eliza-dflash
 *       llamaCppRoot: "...", // path to milady-ai/llama.cpp checkout
 *       omnivoiceRef: "38f824023d…",
 *     });
 *
 * Failure modes are hard errors — see omnivoice-fuse/README.md. There
 * is no fallback path.
 */

import { spawnSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

const OMNIVOICE_REPO =
  process.env.MILADY_OMNIVOICE_REMOTE ||
  "https://github.com/ServeurpersoCom/omnivoice.cpp.git";

// Master HEAD as of 2026-05-10. Bump per the runbook in README.md.
export const OMNIVOICE_REF =
  process.env.MILADY_OMNIVOICE_REF || "38f824023d12b21a7c324651b18bd90f16d8bb86";

// The ServeurpersoCom ggml submodule pin we explicitly DO NOT include
// in the fused build. Recorded so verify-symbols.mjs can assert that no
// `omnivoice/ggml` directory is left dangling under the llama.cpp tree.
export const OMNIVOICE_GGML_REF =
  process.env.MILADY_OMNIVOICE_GGML_REF ||
  "0e3980ef205ea3639650f59e54cfeecd7d947700";

// Subdirectory inside the llama.cpp checkout where omnivoice sources
// land. Stable so the CMake graft and the symbol verifier agree.
export const OMNIVOICE_GRAFT_SUBDIR = "omnivoice";

const REQUIRED_PUBLIC_OMNIVOICE_SYMBOLS = Object.freeze([
  "ov_version",
  "ov_last_error",
  "ov_audio_free",
  "ov_init_default_params",
  "ov_tts_default_params",
  "ov_init",
  "ov_free",
  "ov_log_set",
  "ov_synthesize",
  "ov_duration_sec_to_tokens",
]);

function run(cmd, args, opts = {}) {
  const result = spawnSync(cmd, args, {
    stdio: opts.capture ? ["ignore", "pipe", "pipe"] : "inherit",
    cwd: opts.cwd,
    env: { ...process.env, ...opts.env },
    encoding: "utf8",
  });
  if (result.status !== 0) {
    const detail = opts.capture
      ? `\nstdout:\n${result.stdout || ""}\nstderr:\n${result.stderr || ""}`
      : "";
    throw new Error(
      `[omnivoice-fuse] ${cmd} ${args.join(" ")} failed with ${result.status}${detail}`,
    );
  }
  return result.stdout?.trim() ?? "";
}

function copyDirRecursive(src, dst) {
  fs.mkdirSync(dst, { recursive: true });
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    const from = path.join(src, entry.name);
    const to = path.join(dst, entry.name);
    if (entry.isDirectory()) {
      copyDirRecursive(from, to);
    } else if (entry.isFile() || entry.isSymbolicLink()) {
      fs.copyFileSync(from, to);
    }
  }
}

function replaceBetween(source, startMarker, endMarker, replacement) {
  const start = source.indexOf(startMarker);
  if (start < 0) {
    throw new Error(`[omnivoice-fuse] compatibility patch anchor not found: ${startMarker}`);
  }
  const end = source.indexOf(endMarker, start);
  if (end < 0) {
    throw new Error(`[omnivoice-fuse] compatibility patch end anchor not found: ${endMarker}`);
  }
  return source.slice(0, start) + replacement + source.slice(end);
}

function writeMiladyFfiAdapter({ graftRoot, commit }) {
  const ffiHeaderSrc = new URL("./ffi.h", import.meta.url).pathname;
  const ffiHeaderDst = path.join(graftRoot, "src", "ffi.h");
  fs.copyFileSync(ffiHeaderSrc, ffiHeaderDst);
  fs.writeFileSync(
    path.join(graftRoot, "src", "eliza-inference-ffi.cpp"),
    `// Generated by omnivoice-fuse/prepare.mjs.
// C ABI bridge between libelizainference and omnivoice.cpp.

#include "ffi.h"
#include "omnivoice.h"

#include <algorithm>
#include <cerrno>
#include <cstddef>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <filesystem>
#include <new>
#include <string>
#include <vector>

struct EliInferenceContext {
    std::string bundle_dir;
    std::string tts_model_path;
    std::string codec_model_path;
    ov_context * ov = nullptr;
};

static char * eliza_strdup(const std::string & s) {
    char * out = (char *) std::malloc(s.size() + 1);
    if (!out) return nullptr;
    std::memcpy(out, s.c_str(), s.size() + 1);
    return out;
}

static void eliza_set_error(char ** out_error, const std::string & msg) {
    if (!out_error) return;
    *out_error = eliza_strdup(msg);
}

static bool eliza_is_region(const char * region_name) {
    return region_name &&
        (std::strcmp(region_name, "tts") == 0 ||
         std::strcmp(region_name, "asr") == 0 ||
         std::strcmp(region_name, "text") == 0 ||
         std::strcmp(region_name, "dflash") == 0);
}

static std::vector<std::string> eliza_find_ggufs(const std::filesystem::path & dir) {
    std::vector<std::string> out;
    std::error_code ec;
    if (!std::filesystem::exists(dir, ec) || !std::filesystem::is_directory(dir, ec)) return out;
    for (const auto & entry : std::filesystem::recursive_directory_iterator(dir, ec)) {
        if (ec) break;
        if (!entry.is_regular_file(ec)) continue;
        const auto path = entry.path();
        if (path.extension() == ".gguf") out.push_back(path.string());
    }
    std::sort(out.begin(), out.end());
    return out;
}

static bool eliza_pick_voice_files(
    const std::filesystem::path & bundle_dir,
    std::string & tts_model,
    std::string & codec_model) {
    std::vector<std::string> tts = eliza_find_ggufs(bundle_dir / "tts");
    std::vector<std::string> codec = eliza_find_ggufs(bundle_dir / "codec");
    if (tts.empty()) tts = eliza_find_ggufs(bundle_dir / "voice");
    if (tts.empty()) return false;
    tts_model = tts[0];
    if (!codec.empty()) {
        codec_model = codec[0];
    } else if (tts.size() > 1) {
        codec_model = tts[1];
    } else {
        codec_model = tts_model;
    }
    return true;
}

static int eliza_load_tts(EliInferenceContext * ctx, char ** out_error) {
    if (!ctx) {
        eliza_set_error(out_error, "[libelizainference] load_tts: ctx is NULL");
        return ELIZA_ERR_INVALID_ARG;
    }
    if (ctx->ov) return ELIZA_OK;
    if (ctx->tts_model_path.empty()) {
        if (!eliza_pick_voice_files(std::filesystem::path(ctx->bundle_dir), ctx->tts_model_path, ctx->codec_model_path)) {
            eliza_set_error(out_error, std::string("[libelizainference] no TTS GGUF found under ") + (std::filesystem::path(ctx->bundle_dir) / "tts").string());
            return ELIZA_ERR_BUNDLE_INVALID;
        }
    }

    ov_init_params params;
    ov_init_default_params(&params);
    params.model_path = ctx->tts_model_path.c_str();
    params.codec_path = ctx->codec_model_path.c_str();
    params.use_fa = true;
    ctx->ov = ov_init(&params);
    if (!ctx->ov) {
        std::string msg = "[libelizainference] ov_init failed: ";
        msg += ov_last_error();
        eliza_set_error(out_error, msg);
        return ELIZA_ERR_FFI_FAULT;
    }
    return ELIZA_OK;
}

extern "C" {

const char * eliza_inference_abi_version(void) {
    return "1";
}

EliInferenceContext * eliza_inference_create(
    const char * bundle_dir,
    char ** out_error) {
    if (!bundle_dir || bundle_dir[0] == '\\0') {
        eliza_set_error(out_error, "[libelizainference] bundle_dir is required");
        return nullptr;
    }
    std::filesystem::path root(bundle_dir);
    std::error_code ec;
    if (!std::filesystem::exists(root, ec) || !std::filesystem::is_directory(root, ec)) {
        eliza_set_error(out_error, std::string("[libelizainference] bundle_dir does not exist: ") + bundle_dir);
        return nullptr;
    }

    EliInferenceContext * ctx = new (std::nothrow) EliInferenceContext();
    if (!ctx) {
        eliza_set_error(out_error, "[libelizainference] out of memory allocating context");
        return nullptr;
    }
    ctx->bundle_dir = root.string();

    // Metadata-only: heavy voice weights are intentionally loaded by
    // eliza_inference_mmap_acquire("tts") so voice-off does not keep
    // OmniVoice resident.
    return ctx;
}

void eliza_inference_destroy(EliInferenceContext * ctx) {
    if (!ctx) return;
    ov_free(ctx->ov);
    delete ctx;
}

int eliza_inference_mmap_acquire(
    EliInferenceContext * ctx,
    const char * region_name,
    char ** out_error) {
    if (!ctx) {
        eliza_set_error(out_error, "[libelizainference] mmap_acquire: ctx is NULL");
        return ELIZA_ERR_INVALID_ARG;
    }
    if (!eliza_is_region(region_name)) {
        eliza_set_error(out_error, "[libelizainference] mmap_acquire: invalid region");
        return ELIZA_ERR_INVALID_ARG;
    }
    if (std::strcmp(region_name, "tts") == 0) {
        return eliza_load_tts(ctx, out_error);
    }
    if (std::strcmp(region_name, "asr") == 0) {
        eliza_set_error(out_error, "[libelizainference] ASR is not wired in ABI v1");
        return ELIZA_ERR_NOT_IMPLEMENTED;
    }
    return ELIZA_OK;
}

int eliza_inference_mmap_evict(
    EliInferenceContext * ctx,
    const char * region_name,
    char ** out_error) {
    if (!ctx) {
        eliza_set_error(out_error, "[libelizainference] mmap_evict: ctx is NULL");
        return ELIZA_ERR_INVALID_ARG;
    }
    if (!eliza_is_region(region_name)) {
        eliza_set_error(out_error, "[libelizainference] mmap_evict: invalid region");
        return ELIZA_ERR_INVALID_ARG;
    }
    if (std::strcmp(region_name, "tts") == 0 && ctx->ov) {
        ov_free(ctx->ov);
        ctx->ov = nullptr;
    }
    return ELIZA_OK;
}

int eliza_inference_tts_synthesize(
    EliInferenceContext * ctx,
    const char * text,
    size_t text_len,
    const char * speaker_preset_id,
    float * out_pcm,
    size_t max_samples,
    char ** out_error) {
    if (!ctx || !out_pcm || max_samples == 0) {
        eliza_set_error(out_error, "[libelizainference] tts_synthesize: invalid arguments");
        return ELIZA_ERR_INVALID_ARG;
    }
    if (!ctx->ov) {
        eliza_set_error(out_error, "[libelizainference] tts_synthesize: TTS region is not acquired; call mmap_acquire(\\\"tts\\\") after arming voice");
        return ELIZA_ERR_INVALID_ARG;
    }
    if (!text || text_len == 0) {
        eliza_set_error(out_error, "[libelizainference] tts_synthesize: text is required");
        return ELIZA_ERR_INVALID_ARG;
    }

    std::string text_owned(text, text_len);
    ov_tts_params params;
    ov_tts_default_params(&params);
    params.text = text_owned.c_str();
    params.instruct = speaker_preset_id ? speaker_preset_id : "";

    ov_audio audio = {};
    ov_status rc = ov_synthesize(ctx->ov, &params, &audio);
    if (rc != OV_STATUS_OK) {
        std::string msg = "[libelizainference] ov_synthesize failed: ";
        msg += ov_last_error();
        ov_audio_free(&audio);
        eliza_set_error(out_error, msg);
        return rc == OV_STATUS_OOM ? ELIZA_ERR_OOM : ELIZA_ERR_FFI_FAULT;
    }
    if (audio.n_samples < 0 || (size_t) audio.n_samples > max_samples) {
        std::string msg = "[libelizainference] output buffer too small; required samples=" +
            std::to_string(audio.n_samples);
        ov_audio_free(&audio);
        eliza_set_error(out_error, msg);
        return ELIZA_ERR_INVALID_ARG;
    }
    std::memcpy(out_pcm, audio.samples, (size_t) audio.n_samples * sizeof(float));
    int written = audio.n_samples;
    ov_audio_free(&audio);
    return written;
}

int eliza_inference_asr_transcribe(
    EliInferenceContext * ctx,
    const float * pcm,
    size_t n_samples,
    int sample_rate_hz,
    char * out_text,
    size_t max_text_bytes,
    char ** out_error) {
    (void) ctx;
    (void) pcm;
    (void) n_samples;
    (void) sample_rate_hz;
    (void) out_text;
    (void) max_text_bytes;
    eliza_set_error(out_error, "[libelizainference] ASR is not wired in ABI v1");
    return ELIZA_ERR_NOT_IMPLEMENTED;
}

void eliza_inference_free_string(char * str) {
    std::free(str);
}

} // extern "C"
`,
    "utf8",
  );
}

function hasFunctionDeclaration(source, name) {
  return new RegExp(`\\b${name}\\s*\\(`).test(source);
}

function hasFunctionDefinition(source, name) {
  return new RegExp(`(?:^|\\n)[^\\n;{}]*\\b${name}\\s*\\(`).test(source);
}

function inspectPreparedOmnivoiceSurface({ graftRoot }) {
  const srcRoot = path.join(graftRoot, "src");
  const headerPath = path.join(srcRoot, "omnivoice.h");
  const implPath = path.join(srcRoot, "omnivoice.cpp");
  const adapterPath = path.join(srcRoot, "eliza-inference-ffi.cpp");
  for (const file of [headerPath, implPath, adapterPath]) {
    if (!fs.existsSync(file)) {
      throw new Error(
        `[omnivoice-fuse] prepared graft missing ${file}; refusing stub-only fusion`,
      );
    }
  }

  const header = fs.readFileSync(headerPath, "utf8");
  const impl = fs.readFileSync(implPath, "utf8");
  const adapter = fs.readFileSync(adapterPath, "utf8");
  const missingHeaderSymbols = REQUIRED_PUBLIC_OMNIVOICE_SYMBOLS.filter(
    (symbol) => !hasFunctionDeclaration(header, symbol),
  );
  if (missingHeaderSymbols.length > 0) {
    throw new Error(
      `[omnivoice-fuse] prepared omnivoice.h missing required public symbol(s): ${missingHeaderSymbols.join(", ")}. Pin is not compatible with libelizainference ABI v1.`,
    );
  }

  const missingImplSymbols = REQUIRED_PUBLIC_OMNIVOICE_SYMBOLS.filter(
    (symbol) => !hasFunctionDefinition(impl, symbol),
  );
  if (missingImplSymbols.length > 0) {
    throw new Error(
      `[omnivoice-fuse] prepared omnivoice.cpp missing required implementation symbol(s): ${missingImplSymbols.join(", ")}. Refusing to build a header-only or stub-only graft.`,
    );
  }

  const adapterRequiredCalls = [
    "ov_init_default_params",
    "ov_init",
    "ov_free",
    "ov_tts_default_params",
    "ov_synthesize",
    "ov_audio_free",
    "ov_last_error",
  ];
  const missingAdapterCalls = adapterRequiredCalls.filter(
    (symbol) => !hasFunctionDeclaration(adapter, symbol),
  );
  if (missingAdapterCalls.length > 0) {
    throw new Error(
      `[omnivoice-fuse] generated libelizainference adapter is not wired to OmniVoice call(s): ${missingAdapterCalls.join(", ")}`,
    );
  }

  return {
    header: path.relative(graftRoot, headerPath),
    implementation: path.relative(graftRoot, implPath),
    adapter: path.relative(graftRoot, adapterPath),
    requiredPublicSymbols: [...REQUIRED_PUBLIC_OMNIVOICE_SYMBOLS],
  };
}

function applyMiladyGgmlCompatibility({ graftRoot, commit }) {
  const dacPath = path.join(graftRoot, "src", "dac-decoder.h");
  let source = fs.readFileSync(dacPath, "utf8");
  const loadCtw = `// Load ConvTranspose1d weights in milady ggml's native kernel layout.
// Source-side layout is (IC, OC, K), represented by ggml as ne=(K, OC, IC).
// milady ggml already ships GGML_OP_CONV_TRANSPOSE_1D for CPU/CUDA/Metal/
// Vulkan, while omnivoice's fork used a private col2im_1d op. Keeping the
// native layout lets the fused build share the patched milady ggml without
// adding a second custom op.
static void dac_load_ctw(struct ggml_tensor * dst, const GGUFModel & gf, const std::string & name) {
    struct ggml_tensor * mt = ggml_get_tensor(gf.meta, name.c_str());
    if (!mt) {
        ov_throw("[DAC] tensor '%s' not found (conv_t1 weight)", name.c_str());
    }
    GGML_ASSERT(dst->type == GGML_TYPE_F16);

    const int    K  = (int) mt->ne[0];
    const int    OC = (int) mt->ne[1];
    const int    IC = (int) mt->ne[2];
    const size_t n  = (size_t) IC * (size_t) OC * (size_t) K;

    GGML_ASSERT(dst->ne[0] == K && dst->ne[1] == OC && dst->ne[2] == IC);

    const void * raw = gf_get_data(gf, name.c_str());
    if (mt->type == GGML_TYPE_F16) {
        ggml_backend_tensor_set(dst, raw, 0, n * sizeof(ggml_fp16_t));
        return;
    }

    std::vector<float> f32(n);
    if (mt->type == GGML_TYPE_F32) {
        memcpy(f32.data(), raw, n * sizeof(float));
    } else if (mt->type == GGML_TYPE_BF16) {
        const uint16_t * p = (const uint16_t *) raw;
        for (size_t i = 0; i < n; i++) {
            f32[i] = ggml_bf16_to_fp32(*(const ggml_bf16_t *) &p[i]);
        }
    } else {
        const struct ggml_type_traits * tr = ggml_get_type_traits(mt->type);
        if (!tr || !tr->to_float) {
            ov_throw("[DAC] unsupported conv_t1 weight type %s for '%s'", ggml_type_name(mt->type), name.c_str());
        }
        tr->to_float(raw, f32.data(), (int64_t) n);
    }

    std::vector<ggml_fp16_t> packed(n);
    for (size_t i = 0; i < n; i++) {
        packed[i] = ggml_fp32_to_fp16(f32[i]);
    }
    ggml_backend_tensor_set(dst, packed.data(), 0, n * sizeof(ggml_fp16_t));
}

`;
  source = replaceBetween(
    source,
    "// Pre-permute the ConvTranspose1d weight",
    "// Allocate one snake pair",
    loadCtw,
  );

  const convT = `// ConvTranspose1d using milady ggml's native GGML_OP_CONV_TRANSPOSE_1D.
// The upstream omnivoice fork used a private col2im_1d op with padding.
// milady's native op requires p0=0, so we crop pad samples from both ends
// and then apply output_pad to match the original length contract.
static struct ggml_tensor * dac_conv_t1d(struct ggml_context * ctx,
                                         struct ggml_tensor *  w,
                                         struct ggml_tensor *  b,
                                         struct ggml_tensor *  x,
                                         int                   stride,
                                         int                   pad,
                                         int                   oc,
                                         int                   output_pad) {
    struct ggml_tensor * y = ggml_conv_transpose_1d(ctx, w, x, stride, 0, 1);
    y = ggml_reshape_2d(ctx, y, y->ne[0], y->ne[1]);

    if (pad > 0) {
        const int64_t cropped = y->ne[0] - 2 * (int64_t) pad;
        GGML_ASSERT(cropped > 0);
        GGML_ASSERT(y->ne[1] == oc);
        y = ggml_view_2d(ctx, y, cropped, y->ne[1], y->nb[1], (size_t) pad * y->nb[0]);
        y = ggml_cont(ctx, y);
    }

    if (output_pad > 0) {
        y = ggml_pad(ctx, y, output_pad, 0, 0, 0);
    }

    if (b) {
        struct ggml_tensor * b2d = ggml_reshape_2d(ctx, b, 1, b->ne[0]);
        y                        = ggml_add(ctx, y, b2d);
    }
    return y;
}

`;
  source = replaceBetween(
    source,
    "// ConvTranspose1d via GEMM + col2im_1d",
    "// Residual unit forward:",
    convT,
  );

  source = source.replace(
    "b.ctw = ggml_new_tensor_2d(ctx, GGML_TYPE_F16, b.in_ch, b.kernel * b.out_ch);",
    "b.ctw = ggml_new_tensor_3d(ctx, GGML_TYPE_F16, b.kernel, b.out_ch, b.in_ch);",
  );
  source = source.replace(
    "struct ggml_tensor * ctw;  // [IC, K*OC] bf16",
    "struct ggml_tensor * ctw;  // [K, OC, IC] bf16",
  );
  fs.writeFileSync(dacPath, source, "utf8");

  fs.writeFileSync(
    path.join(graftRoot, "src", "version.h"),
    `#pragma once\n#define OMNIVOICE_VERSION "${commit.slice(0, 12)} (milady-fused)"\n`,
    "utf8",
  );
  writeMiladyFfiAdapter({ graftRoot, commit });
}

// Ensure a clone of omnivoice.cpp at OMNIVOICE_REF lives under
// <cacheRoot>/omnivoice.cpp. Returns the resolved HEAD commit.
function ensureOmnivoiceCheckout(cacheRoot, ref) {
  const checkoutDir = path.join(cacheRoot, "omnivoice.cpp");
  if (fs.existsSync(path.join(checkoutDir, ".git"))) {
    run("git", ["fetch", "--depth=1", "origin", ref], { cwd: checkoutDir });
    run("git", ["checkout", "FETCH_HEAD"], { cwd: checkoutDir });
  } else {
    fs.mkdirSync(cacheRoot, { recursive: true });
    // Some refs (raw commit hashes) don't work with `--branch`. Try the
    // tag/branch path first, then fall back to a full clone + checkout
    // by hash. Either way, the commit pin must resolve.
    const looksLikeHash = /^[0-9a-f]{7,40}$/i.test(ref);
    if (looksLikeHash) {
      run("git", ["clone", OMNIVOICE_REPO, checkoutDir]);
      run("git", ["checkout", ref], { cwd: checkoutDir });
    } else {
      run("git", [
        "clone",
        "--depth=1",
        "--branch",
        ref,
        OMNIVOICE_REPO,
        checkoutDir,
      ]);
    }
  }
  const head = run("git", ["rev-parse", "HEAD"], {
    cwd: checkoutDir,
    capture: true,
  });
  return { checkoutDir, head };
}

// Read the omnivoice ggml submodule's recorded commit from the parent
// repo's index, without actually fetching the submodule contents. This
// is the value we explicitly DO NOT use in the fused build — we record
// it for the manifest and verifier.
function readOmnivoiceGgmlSubmoduleCommit(checkoutDir) {
  const result = spawnSync("git", ["ls-tree", "HEAD", "ggml"], {
    cwd: checkoutDir,
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
  });
  if (result.status !== 0) return null;
  const match = /^160000\s+commit\s+([0-9a-f]{40})/.exec(
    result.stdout || "",
  );
  return match ? match[1] : null;
}

// Apply every `omnivoice-fuse/patches/*.patch` to the merged tree, in
// lexical order. Hard error on any failure — there is no fallback.
function applyPatches({ patchesDir, llamaCppRoot }) {
  if (!fs.existsSync(patchesDir)) return [];
  const patches = fs
    .readdirSync(patchesDir)
    .filter((name) => name.endsWith(".patch"))
    .sort();
  const applied = [];
  for (const name of patches) {
    const patchPath = path.join(patchesDir, name);
    const sentinel = path.join(
      llamaCppRoot,
      ".omnivoice-fuse-patch-applied",
      name,
    );
    if (fs.existsSync(sentinel)) {
      applied.push({ name, status: "already-applied" });
      continue;
    }
    run("git", ["apply", "--check", patchPath], { cwd: llamaCppRoot });
    run("git", ["apply", patchPath], { cwd: llamaCppRoot });
    fs.mkdirSync(path.dirname(sentinel), { recursive: true });
    fs.writeFileSync(sentinel, `${new Date().toISOString()}\n`);
    applied.push({ name, status: "applied" });
  }
  return applied;
}

/**
 * Main entry. Performs the full prepare phase. All errors propagate.
 */
export function prepareOmnivoiceFusion({
  cacheRoot,
  llamaCppRoot,
  omnivoiceRef = OMNIVOICE_REF,
}) {
  if (!cacheRoot) throw new Error("[omnivoice-fuse] cacheRoot is required");
  if (!llamaCppRoot)
    throw new Error("[omnivoice-fuse] llamaCppRoot is required");
  if (!fs.existsSync(path.join(llamaCppRoot, "CMakeLists.txt"))) {
    throw new Error(
      `[omnivoice-fuse] llamaCppRoot=${llamaCppRoot} missing CMakeLists.txt; clone the fork first`,
    );
  }
  if (!fs.existsSync(path.join(llamaCppRoot, "ggml", "CMakeLists.txt"))) {
    throw new Error(
      `[omnivoice-fuse] llamaCppRoot=${llamaCppRoot} missing ggml/CMakeLists.txt; the milady ggml is required for fusion`,
    );
  }

  const { checkoutDir, head } = ensureOmnivoiceCheckout(
    cacheRoot,
    omnivoiceRef,
  );
  const ggmlSubmoduleCommit = readOmnivoiceGgmlSubmoduleCommit(checkoutDir);

  // Validate the omnivoice checkout's surface. Missing pieces => hard
  // error. The runbook requires the operator to investigate, not the
  // build to silently degrade.
  const requiredDirs = ["src", "tools"];
  for (const dir of requiredDirs) {
    const full = path.join(checkoutDir, dir);
    if (!fs.existsSync(full) || !fs.statSync(full).isDirectory()) {
      throw new Error(
        `[omnivoice-fuse] omnivoice checkout at ${checkoutDir} missing required directory '${dir}' — pin ${head} is not usable`,
      );
    }
  }
  // The presence of an entry point we know exists in the pinned commit
  // (and is referenced by every fused build) — sanity check the pin.
  const sentinelHeader = path.join(checkoutDir, "src", "omnivoice.h");
  if (!fs.existsSync(sentinelHeader)) {
    throw new Error(
      `[omnivoice-fuse] omnivoice pin ${head} is missing src/omnivoice.h; refusing to graft an unknown layout`,
    );
  }

  // Stage the merged tree under <llamaCppRoot>/omnivoice/.
  const graftRoot = path.join(llamaCppRoot, OMNIVOICE_GRAFT_SUBDIR);
  // If a previous run left an aborted graft behind, blow it away. The
  // git checkout itself remains untouched — we only own the graft
  // subdirectory.
  fs.rmSync(graftRoot, { recursive: true, force: true });
  fs.mkdirSync(graftRoot, { recursive: true });

  for (const subdir of ["src", "tools"]) {
    copyDirRecursive(
      path.join(checkoutDir, subdir),
      path.join(graftRoot, subdir),
    );
  }
  applyMiladyGgmlCompatibility({ graftRoot, commit: head });
  const sourceSurface = inspectPreparedOmnivoiceSurface({ graftRoot });

  // examples/ is data-only (audio prompts, sample text). Copy on a
  // best-effort basis — the build does not depend on these files. We
  // include them so a developer running llama-omnivoice-server locally
  // has the same demo asset paths the omnivoice CLI tools document.
  const examplesSrc = path.join(checkoutDir, "examples");
  if (fs.existsSync(examplesSrc)) {
    copyDirRecursive(examplesSrc, path.join(graftRoot, "examples"));
  }

  // Hard guarantee: we did NOT bring omnivoice's ggml/ along. The
  // README's "graft, not submodule swap" strategy depends on this.
  const strayGgml = path.join(graftRoot, "ggml");
  if (fs.existsSync(strayGgml)) {
    throw new Error(
      `[omnivoice-fuse] graft staging produced a stray ${strayGgml} — refusing to continue (would create two ggml trees)`,
    );
  }

  // Apply any reconciliation patches keyed to specific drifts.
  const patchesDir = new URL("./patches/", import.meta.url).pathname;
  const appliedPatches = applyPatches({ patchesDir, llamaCppRoot });

  // Count source files actually grafted, for the manifest.
  let sourceCount = 0;
  const stack = [graftRoot];
  while (stack.length > 0) {
    const dir = stack.pop();
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        stack.push(full);
      } else if (/\.(c|cc|cpp|cxx|h|hpp)$/.test(entry.name)) {
        sourceCount += 1;
      }
    }
  }

  return {
    commit: head,
    ref: omnivoiceRef,
    ggmlSubmoduleCommit,
    graftRoot,
    sourceCount,
    sourceSurface,
    appliedPatches,
  };
}
