export {
	MESSAGE_SOURCE_AGENT_GREETING,
	MESSAGE_SOURCE_CLIENT_CHAT,
	MESSAGE_SOURCE_CODING_AGENT,
	MESSAGE_SOURCE_SUB_AGENT,
	MESSAGE_SOURCE_TRIGGER_PROMPT,
	MESSAGE_SOURCES,
	type MessageSourceSentinel,
} from "@elizaos/common";
