export {
	type AppShellBackgroundPolicy,
	IMMERSIVE_WALLPAPER_SURFACE,
	type PageLayoutManifest,
	type ResolvedSurfaceManifest,
	resolveSurfaceBackgroundPolicy,
	resolveSurfaceManifest,
	SURFACE_CAPABILITIES,
	SURFACE_ISOLATION_LEVELS,
	type SurfaceCapability,
	type SurfaceIsolationLevel,
	type SurfaceLifecyclePolicy,
	type SurfaceManifest,
	type SurfaceManifestBearer,
	surfaceGrants,
	type ViewHeaderPolicy,
} from "@elizaos/common";
