/**
 * Built-in view declarations for the core first-party shell pages.
 *
 * These views are part of the main shell bundle — no `bundlePath` and no
 * `bundleUrl` are needed. They are registered in the view registry so
 * GET /api/views returns them, the agent can discover and navigate to them
 * by name, and they appear in the view manager.
 */

import type { ViewDeclaration } from "@elizaos/core";

export const BUILTIN_VIEWS: ViewDeclaration[] = [
  {
    id: "tutorial",
    viewKind: "system",
    label: "Tutorial",
    description:
      "Interactive guided tour — learn the chat, switching views, and Settings in 90 seconds",
    icon: "GraduationCap",
    heroImagePath: "assets/view-heroes/tutorial.png",
    path: "/tutorial",
    order: 0,
    tags: ["tutorial", "onboarding", "learn", "guide", "help"],
    visibleInManager: true,
    desktopTabEnabled: true,
    platforms: ["web", "desktop", "ios", "android"],
  },
  {
    id: "help",
    viewKind: "system",
    label: "Help",
    description:
      "Searchable FAQ and knowledge base — what Eliza is and how everything works",
    icon: "LifeBuoy",
    heroImagePath: "assets/view-heroes/help.png",
    path: "/help",
    order: 2,
    tags: ["help", "faq", "knowledge", "support", "questions"],
    visibleInManager: true,
    desktopTabEnabled: true,
    platforms: ["web", "desktop", "ios", "android"],
  },
  {
    id: "camera",
    viewKind: "preview",
    label: "Camera",
    description:
      "Live camera preview with photo capture and front/back switching",
    icon: "Camera",
    heroImagePath: "assets/view-heroes/camera.png",
    path: "/camera",
    order: 3,
    tags: ["camera", "photo", "capture", "video", "vision"],
    visibleInManager: true,
    desktopTabEnabled: true,
    platforms: ["android"],
    nativeOs: true,
  },
  {
    id: "chat",
    viewKind: "system",
    label: "Messages",
    description:
      "Conversations with your agent, inbound messages from every connector",
    icon: "MessageSquare",
    heroImagePath: "assets/view-heroes/chat.png",
    path: "/chat",
    order: 1,
    tags: ["messaging", "conversation", "agent"],
    anticipatoryIntent:
      "Offer to pick up the most recent unfinished thread or summarize new inbound messages across connectors.",
    visibleInManager: true,
    desktopTabEnabled: true,
    platforms: ["web", "desktop", "ios", "android"],
  },
  {
    id: "character",
    viewKind: "system",
    label: "Character",
    description: "Agent identity, personality, style, and knowledge documents",
    icon: "UserRound",
    heroImagePath: "assets/view-heroes/character.png",
    path: "/character",
    order: 50,
    tags: ["identity", "personality", "character"],
    anticipatoryIntent:
      "Offer the single highest-value identity or personality improvement from the current character state (bio, style, examples, or knowledge gaps).",
    visibleInManager: true,
    desktopTabEnabled: true,
  },
  {
    id: "documents",
    viewKind: "system",
    label: "Knowledge",
    description: "Agent knowledge documents, uploads, and retrieval sources",
    icon: "FileText",
    heroImagePath: "assets/view-heroes/character.png",
    path: "/character/documents",
    order: 51,
    tags: ["documents", "knowledge", "files", "uploads", "retrieval"],
    relatedActions: ["OWNER_DOCUMENTS"],
    anticipatoryIntent:
      "Offer to triage recently ingested attachments — tag, rescope, or clean up new knowledge items from the last few days.",
    visibleInManager: true,
    desktopTabEnabled: true,
  },
  {
    id: "automations",
    viewKind: "system",
    label: "Automations",
    description: "Scheduled tasks and recurring workflows",
    icon: "Clock3",
    heroImagePath: "assets/view-heroes/automations.png",
    path: "/automations",
    order: 55,
    tags: ["automation", "tasks", "scheduling"],
    anticipatoryIntent:
      "Offer to draft a new workflow/trigger for a routine the user does by hand, or surface any failed automation runs that need attention.",
    visibleInManager: true,
  },
  {
    id: "plugins-page",
    viewKind: "system",
    label: "Plugins",
    description: "Manage installed plugins, configure credentials",
    icon: "Puzzle",
    heroImagePath: "assets/view-heroes/plugins-page.png",
    path: "/apps/plugins",
    order: 60,
    anticipatoryIntent:
      "Offer the smallest concrete plugin setup or fix — configure credentials for an installed-but-unready plugin, or close a runtime capability gap.",
    tags: [
      "plugins",
      "plugin-browser",
      "plugin browser",
      "plugin-manager",
      "plugin manager",
      "configuration",
      "extensions",
    ],
    relatedActions: ["RUNTIME"],
    visibleInManager: true,
  },
  {
    id: "trajectories",
    viewKind: "developer",
    developerOnly: true,
    label: "Trajectories",
    description: "Agent trajectory logs and training data",
    icon: "GitBranch",
    heroImagePath: "assets/view-heroes/trajectories.png",
    path: "/apps/trajectories",
    order: 70,
    tags: ["training", "logs", "trajectories"],
    visibleInManager: true,
  },
  {
    id: "transcripts",
    viewKind: "system",
    label: "Transcripts",
    description:
      "Recorded voice transcripts — play, scrub, and read with word sync",
    icon: "AudioLines",
    heroImagePath: "assets/view-heroes/transcripts.png",
    path: "/apps/transcripts",
    order: 71,
    tags: ["transcript", "voice", "recording", "audio"],
    anticipatoryIntent:
      "Offer to summarize or extract action items from the most recent voice transcript.",
    visibleInManager: true,
  },
  {
    id: "memories",
    viewKind: "system",
    developerOnly: false,
    label: "Memories",
    description: "Agent memory viewer and management",
    icon: "Brain",
    heroImagePath: "assets/view-heroes/memories.png",
    path: "/apps/memories",
    order: 72,
    tags: ["memory", "knowledge"],
    visibleInManager: true,
  },
  {
    id: "database",
    viewKind: "developer",
    developerOnly: true,
    label: "Database",
    description: "Raw database viewer and query interface",
    icon: "Database",
    heroImagePath: "assets/view-heroes/database.png",
    path: "/apps/database",
    order: 80,
    tags: ["database", "data", "debug"],
    visibleInManager: true,
  },
  {
    id: "logs",
    viewKind: "developer",
    developerOnly: true,
    label: "Logs",
    description: "Runtime logs and agent debug output",
    icon: "FileText",
    heroImagePath: "assets/view-heroes/logs.png",
    path: "/apps/logs",
    order: 81,
    tags: ["logs", "debug", "runtime"],
    visibleInManager: true,
  },
  {
    id: "settings",
    viewKind: "system",
    label: "Settings",
    description: "Configuration, plugins, credentials, and preferences",
    icon: "Settings",
    heroImagePath: "assets/view-heroes/settings.png",
    path: "/settings",
    order: 90,
    tags: ["configuration", "preferences", "plugins"],
    relatedActions: ["RUNTIME"],
    anticipatoryIntent:
      "Offer to finish first-run setup — pick the model and provider, connect the wallet/cloud account, or set the voice — starting with whatever is still unconfigured.",
    visibleInManager: true,
    desktopTabEnabled: true,
  },
  {
    id: "background",
    viewKind: "preview",
    label: "Background",
    description:
      "Set the app background — pick a shader color, upload an image, or generate one",
    icon: "Image",
    heroImagePath: "assets/view-heroes/background.png",
    path: "/background",
    order: 92,
    tags: ["background", "wallpaper", "color", "theme", "appearance", "image"],
    visibleInManager: true,
    desktopTabEnabled: true,
    platforms: ["web", "desktop", "ios", "android"],
  },
];
