/**
 * Pendant insights route: `POST /api/pendant/insights`.
 *
 * Phase 2 of the ambient-memory pendant. Takes a window of accumulated transcript
 * segments and returns a structured {@link PendantInsights} rollup generated by
 * the agent's OWN runtime model (`runtime.useModel(TEXT_LARGE)`) — no bespoke
 * cloud dependency. Mirrors the existing `/api/custom-actions/generate` pattern:
 * validate a zod body → compose a prompt → run the model → parse fail-closed.
 *
 * The generation core ({@link generatePendantInsights}) is a PURE function of a
 * "run the model" callback, so it's unit-tested with a fake model — no server or
 * real runtime needed. The HTTP handler is a thin adapter over it.
 */

import type http from "node:http";
import { type Memory, ModelType, stringToUuid, type UUID } from "@elizaos/core";
import type { ReadJsonBodyOptions } from "@elizaos/shared";
import {
  buildInsightsPrompt,
  composePendantInsights,
  type InsightSourceSegment,
  isEmptyInsights,
  MIN_INSIGHT_SEGMENTS,
  type PendantInsights,
  type PendantInsightsSkipReason,
  PostPendantInsightsRequestSchema,
  parsePendantInsightsModelOutput,
} from "@elizaos/shared";

/** A minimal "call the text model" function, including transport cancellation. */
export type RunTextModel = (
  prompt: string,
  signal?: AbortSignal,
) => Promise<string>;

/** Discriminated result of an insight generation attempt. */
export type GenerateInsightsResult =
  | { ok: true; insights: PendantInsights }
  | { ok: false; skip: PendantInsightsSkipReason }
  | { ok: false; error: string };

/**
 * Generate insights from a window of segments using a caller-supplied model
 * runner. Pure w.r.t. I/O (the runner is injected), so tests drive it with a fake
 * model to exercise good output, malformed output, empty windows, and
 * cancellation. Never throws — always returns a discriminated result.
 */
export async function generatePendantInsights(args: {
  segments: ReadonlyArray<InsightSourceSegment>;
  runModel: RunTextModel;
  priorSummary?: string;
  maxTranscriptChars?: number;
  /** Wall clock injector (tests pass a fixed value); defaults to Date.now. */
  now?: () => number;
  /** Cancellation — when aborted BEFORE the model call, we skip the call entirely. */
  signal?: AbortSignal;
}): Promise<GenerateInsightsResult> {
  const now = args.now ?? Date.now;

  const nonEmpty = args.segments.filter((s) => s.text.trim().length > 0);
  if (nonEmpty.length < MIN_INSIGHT_SEGMENTS) {
    return { ok: false, skip: "too-few-segments" };
  }

  const built = buildInsightsPrompt({
    segments: nonEmpty,
    priorSummary: args.priorSummary,
    maxTranscriptChars: args.maxTranscriptChars,
  });
  if (built.includedSegmentIds.length === 0) {
    return { ok: false, skip: "empty-transcript" };
  }

  // Never spend a model round-trip if the caller already cancelled.
  if (args.signal?.aborted) {
    return { ok: false, error: "cancelled" };
  }

  let raw: string;
  try {
    raw = await args.runModel(built.prompt, args.signal);
  } catch (err) {
    if (args.signal?.aborted) return { ok: false, error: "cancelled" };
    return {
      ok: false,
      error: `model call failed: ${
        err instanceof Error ? err.message : String(err)
      }`,
    };
  }

  // A disconnect that landed while the model was running: drop the result.
  if (args.signal?.aborted) {
    return { ok: false, error: "cancelled" };
  }

  const parsed = parsePendantInsightsModelOutput(raw);
  if (!parsed.ok) {
    return { ok: false, error: parsed.error };
  }

  const insights = composePendantInsights({
    model: parsed.value,
    generatedAt: now(),
    transcriptRange: built.transcriptRange,
    knownSegmentIds: new Set(built.includedSegmentIds),
  });
  return { ok: true, insights };
}

export interface PendantInsightsMemoryRuntime {
  agentId: UUID;
  getMemoryById(id: UUID): Promise<Memory | null>;
  createMemory(
    memory: Memory,
    tableName: string,
    unique?: boolean,
  ): Promise<UUID>;
}

/**
 * Persist a substantive rollup into the same agent's local memory store. The ID
 * is deterministic for the exact transcript window, so a client retry cannot
 * create duplicate notes. Structured fields stay in metadata for future
 * action/follow-up tooling while the text remains searchable by normal memory.
 */
export async function persistPendantInsights(args: {
  runtime: PendantInsightsMemoryRuntime;
  insights: PendantInsights;
  segmentIds: readonly string[];
}): Promise<UUID | null> {
  if (isEmptyInsights(args.insights)) return null;

  const id = stringToUuid(
    `pendant-insights:v${args.insights.schemaVersion}:${args.segmentIds.join("|")}`,
  );
  const memory: Memory = {
    id,
    agentId: args.runtime.agentId,
    entityId: args.runtime.agentId,
    roomId: args.runtime.agentId,
    worldId: args.runtime.agentId,
    createdAt: args.insights.generatedAt,
    unique: true,
    content: {
      text: formatPendantInsightsMemory(args.insights),
      source: "pendant-insights",
    },
    metadata: {
      type: "custom",
      source: "pendant-insights",
      scope: "owner-private",
      timestamp: args.insights.generatedAt,
      tags: ["pendant", "insights", "ambient-memory"],
      schemaVersion: args.insights.schemaVersion,
      insights: args.insights,
      sourceSegmentIds: args.segmentIds,
    },
  };
  const existing = await args.runtime.getMemoryById(id);
  if (existing) return id;
  await args.runtime.createMemory(memory, "messages", true);
  return id;
}

/** Searchable rendering for the agent's existing memory/retrieval path. */
export function formatPendantInsightsMemory(insights: PendantInsights): string {
  const lines = ["Pendant conversation insights"];
  if (insights.summary) lines.push(`Summary: ${insights.summary}`);
  if (insights.actionItems.length > 0) {
    lines.push("Action items:");
    for (const item of insights.actionItems) {
      const details = [
        item.owner ? `owner: ${item.owner}` : "",
        item.dueAt ? `due: ${item.dueAt}` : "",
        `confidence: ${item.confidence}`,
      ].filter(Boolean);
      lines.push(`- ${item.text} (${details.join(", ")})`);
    }
  }
  if (insights.topics.length > 0) {
    lines.push(
      `Topics: ${insights.topics.map((topic) => topic.label).join(", ")}`,
    );
  }
  if (insights.peopleMentioned.length > 0) {
    lines.push(
      `People mentioned: ${insights.peopleMentioned.map((person) => person.name).join(", ")}`,
    );
  }
  if (insights.notableQuotes.length > 0) {
    lines.push("Notable quotes:");
    for (const quote of insights.notableQuotes) {
      lines.push(
        `- ${quote.speaker ? `${quote.speaker}: ` : ""}"${quote.text}"`,
      );
    }
  }
  return lines.join("\n");
}

/** Minimal context the HTTP handler needs (a subset of the misc-route context). */
export interface PendantInsightsRouteContext {
  req: http.IncomingMessage;
  res: http.ServerResponse;
  method: string;
  pathname: string;
  state: {
    runtime:
      | (PendantInsightsMemoryRuntime & { useModel: RunTextModel | unknown })
      | null;
  };
  json: (res: http.ServerResponse, data: unknown, status?: number) => void;
  error: (res: http.ServerResponse, message: string, status?: number) => void;
  readJsonBody: <T extends object>(
    req: http.IncomingMessage,
    res: http.ServerResponse,
    options?: ReadJsonBodyOptions,
  ) => Promise<T | null>;
}

/**
 * Handle `POST /api/pendant/insights`. Returns true when it owns the request.
 * Non-matching method/path returns false so the caller falls through.
 */
export async function handlePendantInsightsRoutes(
  ctx: PendantInsightsRouteContext,
): Promise<boolean> {
  const { req, res, method, pathname, state, json, error, readJsonBody } = ctx;

  if (!(method === "POST" && pathname === "/api/pendant/insights")) {
    return false;
  }

  // Support the full typed request above the server's generic 1 MiB body cap.
  // 5 MiB covers 200 x 3,000-char UTF-8 segments plus JSON escaping overhead.
  const raw = await readJsonBody<Record<string, unknown>>(req, res, {
    maxBytes: 5 * 1024 * 1024,
  });
  if (raw === null) return true; // readJsonBody already responded

  const parsed = PostPendantInsightsRequestSchema.safeParse(raw);
  if (!parsed.success) {
    error(res, parsed.error.issues[0]?.message ?? "Invalid request body", 400);
    return true;
  }

  const runtime = state.runtime;
  if (
    !runtime ||
    typeof (runtime as { useModel?: unknown }).useModel !== "function"
  ) {
    json(res, { ok: false, reason: "runtime-unavailable" });
    return true;
  }

  const controller = new AbortController();
  const abortForDisconnect = (): void => {
    if (!res.writableEnded && !controller.signal.aborted) {
      controller.abort("client-disconnected");
    }
  };
  req.once("aborted", abortForDisconnect);
  res.once("close", abortForDisconnect);

  try {
    const modelRuntime = runtime as {
      useModel: (
        modelType: unknown,
        params: { prompt: string; signal?: AbortSignal },
      ) => Promise<unknown>;
    };
    const runModel: RunTextModel = async (prompt, signal) => {
      // Call as a method, not a detached function, because AgentRuntime.useModel
      // reads instance state. The signal reaches providers that support abort.
      const out = await modelRuntime.useModel(ModelType.TEXT_LARGE, {
        prompt,
        ...(signal ? { signal } : {}),
      });
      return typeof out === "string" ? out : String(out);
    };

    const result = await generatePendantInsights({
      segments: parsed.data.segments,
      runModel,
      priorSummary: parsed.data.priorSummary,
      maxTranscriptChars: parsed.data.maxTranscriptChars,
      signal: controller.signal,
    });

    // The socket is gone. Never attempt to write a late response.
    if (controller.signal.aborted || res.destroyed) return true;

    if (result.ok) {
      try {
        await persistPendantInsights({
          runtime,
          insights: result.insights,
          segmentIds: parsed.data.segments.map((segment) => segment.id),
        });
      } catch (err) {
        error(
          res,
          `failed to persist pendant insights: ${err instanceof Error ? err.message : String(err)}`,
          500,
        );
        return true;
      }
      json(res, { ok: true, insights: result.insights });
      return true;
    }
    if ("skip" in result) {
      json(res, { ok: false, reason: result.skip });
      return true;
    }
    error(res, result.error, 502);
    return true;
  } finally {
    req.off("aborted", abortForDisconnect);
    res.off("close", abortForDisconnect);
  }
}
