# Runtime image generated by scripts/deploy-railway.sh from the package-owned bundle.
FROM oven/bun:1.3.14-alpine AS deps
WORKDIR /app
RUN apk add --no-cache python3 make g++ pkgconf opus-dev
COPY package.json install-portable-opus.mjs ./
RUN bun ./install-portable-opus.mjs /app /app

FROM oven/bun:1.3.14-alpine
WORKDIR /app
ENV NODE_ENV=production
RUN apk add --no-cache ffmpeg opus
RUN addgroup --system --gid 1001 nodejs && adduser --system --uid 1001 gateway
COPY --from=deps /app/node_modules ./node_modules
COPY --from=deps /app/install-portable-opus.mjs /usr/local/lib/install-portable-opus.mjs
COPY dist ./dist
COPY package.json ./
RUN bun /usr/local/lib/install-portable-opus.mjs --smoke-only /app
USER gateway
EXPOSE 3000
HEALTHCHECK --interval=30s --timeout=10s --start-period=8s --retries=3 \
  CMD bun -e "fetch('http://localhost:3000/health').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"
CMD ["bun", "run", "dist/index.js"]
