import { defineConfig } from 'tsup';

export default defineConfig({
  entry: ['src/index.ts'],
  outDir: 'dist',
  tsconfig: './tsconfig.build.json',
  sourcemap: true,
  clean: true,
  format: ['esm'],
  dts: true,
  external: [
    'dotenv',
    'fs',
    'path',
    'crypto',
    'node:fs',
    'node:path',
    'node:crypto',
    'node:http',
    'node:url',
    '@reflink/reflink',
    '@node-llama-cpp',
    '@elizaos/core',
    'https',
    'http',
    'agentkeepalive',
    'fluent-ffmpeg',
    'zod',
    'twilio',
    'express',
    'body-parser',
    'ws',
    'node-cache',
    'multer',
    'axios',
  ],
});
