import { NextRequest, NextResponse } from "next/server";
import { requireAuthOrApiKeyWithOrg } from "@/lib/auth";
import { charactersService } from "@/lib/services/characters";
import { logger } from "@/lib/utils/logger";

export const dynamic = "force-dynamic";

/**
 * POST /api/my-agents/characters/[id]/clone
 * Clones a character to create a new copy owned by the user.
 * Supports both Privy session and API key authentication.
 *
 * @param request - Request body with optional name, username, and makePublic flag.
 * @param params - Route parameters containing the character ID to clone.
 * @returns Cloned character details.
 */
export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  try {
    const { user } = await requireAuthOrApiKeyWithOrg(request);
    const { id } = await params;

    let body: { name?: string; username?: string; makePublic?: boolean } = {};
    try {
      body = await request.json();
    } catch {
      // Empty body is fine
    }

    logger.info("[My Agents API] Cloning character:", {
      characterId: id,
      userId: user.id,
      name: body.name,
      username: body.username,
    });

    // Get the original character
    const original = await charactersService.getById(id);
    if (!original) {
      return NextResponse.json(
        { success: false, error: "Character not found" },
        { status: 404 },
      );
    }

    // Determine the clone's name
    const cloneName = body.name || `${original.name} (Copy)`;

    // Username is auto-generated by charactersService.create if not provided
    // If original has username, suggest a derivative (handled by generateUniqueUsername)

    // Create a clone - username will be auto-generated from the name
    const clonedCharacter = await charactersService.create({
      user_id: user.id,
      organization_id: user.organization_id!,
      name: cloneName,
      username: body.username, // Optional - will auto-generate if not provided
      bio: original.bio,
      system: original.system,
      topics: original.topics,
      adjectives: original.adjectives,
      knowledge: original.knowledge,
      plugins: original.plugins,
      style: original.style,
      settings: original.settings,
      character_data: original.character_data || {},
      avatar_url: original.avatar_url,
      category: original.category,
      tags: original.tags,
      is_public: body.makePublic ?? false,
      is_template: false,
    });

    logger.info("[My Agents API] Character cloned successfully:", {
      originalId: id,
      clonedId: clonedCharacter.id,
      clonedUsername: clonedCharacter.username,
    });

    return NextResponse.json({
      success: true,
      data: {
        character: clonedCharacter,
        message: "Character cloned successfully",
      },
    });
  } catch (error) {
    logger.error("[My Agents API] Error cloning character:", error);

    // Handle username validation errors specially
    const errorMessage =
      error instanceof Error ? error.message : "Failed to clone character";
    const isValidationError =
      errorMessage.includes("username") || errorMessage.includes("Username");

    return NextResponse.json(
      {
        success: false,
        error: errorMessage,
      },
      {
        status: isValidationError
          ? 400
          : error instanceof Error && error.message.includes("not found")
            ? 404
            : 500,
      },
    );
  }
}
