import { describe, expect, test } from "bun:test";
import { existsSync } from "node:fs";
import { join } from "node:path";

describe("plugin-sql integration", () => {
  test("main module is importable", async () => {
    // Verify the index module can be imported without errors
    const mod = await import("../../index.node");
    expect(mod).toBeDefined();
  });

  test("plugin export is defined with correct structure", async () => {
    const { plugin } = await import("../../index.node");
    expect(plugin).toBeDefined();
    expect(typeof plugin.name).toBe("string");
  });

  test("createDatabaseAdapter function is exported", async () => {
    const mod = await import("../../index.node");
    expect(mod.createDatabaseAdapter).toBeDefined();
    expect(typeof mod.createDatabaseAdapter).toBe("function");
  });

  test("RLS functions are exported", async () => {
    const mod = await import("../../index.node");
    expect(mod.installRLSFunctions).toBeDefined();
    expect(typeof mod.installRLSFunctions).toBe("function");
    expect(mod.getOrCreateRlsServer).toBeDefined();
    expect(typeof mod.getOrCreateRlsServer).toBe("function");
    expect(mod.setServerContext).toBeDefined();
    expect(typeof mod.setServerContext).toBe("function");
  });

  test("DatabaseMigrationService is exported", async () => {
    const { DatabaseMigrationService } = await import("../../index.node");
    expect(DatabaseMigrationService).toBeDefined();
    const service = new DatabaseMigrationService();
    expect(service).toBeDefined();
  });

  test("drizzle migration directory exists", () => {
    const drizzleDir = join(import.meta.dir, "..", "..", "..", "drizzle");
    if (existsSync(drizzleDir)) {
      expect(existsSync(drizzleDir)).toBe(true);
    } else {
      // drizzle directory is optional - generated by drizzle-kit
      expect(true).toBe(true);
    }
  });
});
