import type { Action, AgentContext, Provider } from "../types/components";

export const ACTION_CONTEXT_MAP: Record<string, AgentContext[]> = {
	NONE: ["general"],
	IGNORE: ["general"],
	CONTINUE: ["general"],
	REPLY: ["general"],
	HELP: ["general"],
	STATUS: ["general"],
	MODELS: ["general"],
	CONFIGURE: ["general", "system"],
	APP: ["apps"],
	PLUGIN: ["plugins", "system"],
	AUTOMATION_ACTIONS: ["general", "automation"],
	BROWSER_ACTIONS: ["general", "browser"],
	CHARACTER_ACTIONS: ["general", "character"],
	CONNECTOR_ACTIONS: ["general", "connectors"],
	LIFEOPS_ACTIONS: ["general", "lifeops"],
	PHONE_ACTIONS: ["general", "phone"],
	SETTINGS_ACTIONS: ["general", "settings"],
	WALLET_ACTIONS: ["general", "wallet"],
	MODIFY_CHARACTER: ["character", "system"],
	UPDATE_OWNER_NAME: ["character", "settings"],
	SET_USER_NAME: ["character", "settings"],
	SEND_TOKEN: ["wallet"],
	TRANSFER: ["wallet"],
	TRANSFER_TOKEN: ["wallet"],
	CHECK_BALANCE: ["wallet"],
	GET_BALANCE: ["wallet"],
	GET_RECEIVE_ADDRESS: ["wallet"],
	PREPARE_SWAP: ["wallet"],
	PREPARE_TRANSFER: ["wallet"],
	EXECUTE_TRADE: ["wallet"],
	CROSS_CHAIN_TRANSFER: ["wallet"],
	SWAP_TOKEN: ["wallet", "automation"],
	SWAP: ["wallet", "automation"],
	SWAP_SOLANA: ["wallet", "automation"],
	BRIDGE_TOKEN: ["wallet"],
	APPROVE_TOKEN: ["wallet"],
	SIGN_MESSAGE: ["wallet"],
	SIGN_WITH_ELIZA_WALLET: ["wallet"],
	APPROVE_ELIZA_WALLET_REQUEST: ["wallet"],
	REJECT_ELIZA_WALLET_REQUEST: ["wallet"],
	DEPLOY_CONTRACT: ["wallet", "code"],
	CREATE_GOVERNANCE_PROPOSAL: ["wallet", "social"],
	GOV_PROPOSE: ["wallet", "social"],
	VOTE_ON_PROPOSAL: ["wallet", "social"],
	GOV_VOTE: ["wallet", "social"],
	GOV_QUEUE: ["wallet", "social"],
	GOV_EXECUTE: ["wallet", "social"],
	STAKE: ["wallet"],
	UNSTAKE: ["wallet"],
	CLAIM_REWARDS: ["wallet"],
	GET_TOKEN_PRICE: ["wallet", "knowledge"],
	GET_PORTFOLIO: ["wallet"],
	CREATE_WALLET: ["wallet"],
	IMPORT_WALLET: ["wallet"],
	SEARCH_KNOWLEDGE: ["knowledge"],
	ADD_KNOWLEDGE: ["knowledge"],
	REMEMBER: ["knowledge"],
	RECALL: ["knowledge"],
	LEARN_FROM_EXPERIENCE: ["knowledge"],
	SEARCH_WEB: ["knowledge", "browser"],
	WEB_SEARCH: ["knowledge", "browser"],
	SUMMARIZE: ["knowledge"],
	ANALYZE: ["knowledge"],
	CREATE_TASK: ["code", "automation"],
	BROWSER_SESSION: ["browser"],
	BROWSER_ACTION: ["browser"],
	MANAGE_ELIZA_BROWSER_WORKSPACE: ["browser"],
	MANAGE_LIFEOPS_BROWSER: ["browser", "lifeops"],
	BROWSER_BRIDGE_INSTALL: ["browser"],
	BROWSER_BRIDGE_REVEAL_FOLDER: ["browser"],
	BROWSER_BRIDGE_OPEN_MANAGER: ["browser"],
	BROWSER_BRIDGE_REFRESH: ["browser"],
	BROWSE: ["browser"],
	SCREENSHOT: ["browser", "media"],
	NAVIGATE: ["browser"],
	CLICK: ["browser"],
	TYPE_TEXT: ["browser"],
	EXTRACT_PAGE: ["browser", "knowledge"],
	SPAWN_AGENT: ["code", "automation"],
	SEND_TO_AGENT: ["code", "automation"],
	LIST_AGENTS: ["code", "automation"],
	STOP_AGENT: ["code", "automation"],
	TASK_HISTORY: ["code", "automation"],
	TASK_CONTROL: ["code", "automation"],
	TASK_SHARE: ["code", "automation"],
	PROVISION_WORKSPACE: ["code", "automation"],
	FINALIZE_WORKSPACE: ["code", "automation"],
	KILL_AGENT: ["code", "automation"],
	UPDATE_AGENT: ["code", "system"],
	RUN_SCRIPT: ["code", "automation"],
	REVIEW_CODE: ["code"],
	GENERATE_CODE: ["code"],
	EXECUTE_TASK: ["code", "automation"],
	CREATE_SUBTASK: ["code", "automation"],
	COMPLETE_TASK: ["code", "automation"],
	CANCEL_TASK: ["code", "automation"],
	GENERATE_IMAGE: ["media"],
	DESCRIBE_IMAGE: ["media", "knowledge"],
	DESCRIBE_VIDEO: ["media", "knowledge"],
	DESCRIBE_AUDIO: ["media", "knowledge"],
	TEXT_TO_SPEECH: ["media"],
	TRANSCRIBE: ["media", "knowledge"],
	UPLOAD_FILE: ["media"],
	CREATE_CRON: ["automation"],
	UPDATE_CRON: ["automation"],
	DELETE_CRON: ["automation"],
	LIST_CRONS: ["automation"],
	PAUSE_CRON: ["automation"],
	RUN_CRON: ["automation"],
	CREATE_TRIGGER_TASK: ["automation"],
	UPDATE_TRIGGER_TASK: ["automation"],
	DELETE_TRIGGER_TASK: ["automation"],
	RUN_TRIGGER_NOW: ["automation"],
	CREATE_WORKFLOW: ["automation"],
	DELETE_WORKFLOW: ["automation"],
	TOGGLE_WORKFLOW_ACTIVE: ["automation"],
	PROMOTE_TASK_TO_WORKFLOW: ["automation"],
	MANAGE_TASKS: ["automation"],
	CREATE_N8N_WORKFLOW: ["automation"],
	ACTIVATE_N8N_WORKFLOW: ["automation"],
	DEACTIVATE_N8N_WORKFLOW: ["automation"],
	DELETE_N8N_WORKFLOW: ["automation"],
	GET_N8N_EXECUTIONS: ["automation"],
	TRIGGER_WEBHOOK: ["automation"],
	SCHEDULE: ["automation"],
	SEND_MESSAGE: ["social", "phone"],
	OWNER_SEND_MESSAGE: ["social", "phone", "lifeops"],
	OWNER_INBOX: ["social", "knowledge", "lifeops"],
	OWNER_RELATIONSHIP: ["character", "social", "lifeops"],
	OWNER_CALENDAR: ["automation", "social", "lifeops"],
	RUN_MORNING_CHECKIN: ["automation", "lifeops"],
	RUN_NIGHT_CHECKIN: ["automation", "lifeops"],
	UPDATE_OWNER_PROFILE: ["character", "social", "lifeops"],
	ADD_CONTACT: ["phone", "social"],
	UPDATE_CONTACT: ["phone", "social"],
	GET_CONTACT: ["phone", "social"],
	SEARCH_CONTACTS: ["phone", "social"],
	READ_MESSAGES: ["phone", "social", "knowledge"],
	READ_CHANNEL: ["social", "knowledge"],
	CALL_USER: ["phone", "social", "lifeops"],
	CALL_EXTERNAL: ["phone", "social", "lifeops"],
	LIFE: ["lifeops"],
	LIFEOPS_COMPUTER_USE: ["lifeops", "browser", "system"],
	COMPUTE_TRAVEL_BUFFER: ["lifeops"],
	BOOK_TRAVEL: ["lifeops"],
	GENERATE_DOSSIER: ["lifeops", "knowledge"],
	SUBSCRIPTIONS: ["lifeops"],
	EMAIL_UNSUBSCRIBE: ["lifeops", "social"],
	OWNER_SCHEDULE: ["lifeops", "automation"],
	SCHEDULING: ["lifeops", "automation"],
	PROPOSE_MEETING_TIMES: ["lifeops", "automation"],
	CHECK_AVAILABILITY: ["lifeops", "automation"],
	UPDATE_MEETING_PREFERENCES: ["lifeops", "settings"],
	HEALTH: ["lifeops"],
	SCREEN_TIME: ["lifeops"],
	GET_ACTIVITY_REPORT: ["lifeops"],
	GET_TIME_ON_APP: ["lifeops"],
	GET_TIME_ON_SITE: ["lifeops"],
	BLOCK_WEBSITES: ["lifeops", "automation"],
	UNBLOCK_WEBSITES: ["lifeops", "automation"],
	GET_WEBSITE_BLOCK_STATUS: ["lifeops"],
	REQUEST_WEBSITE_BLOCKING_PERMISSION: ["lifeops"],
	BLOCK_APPS: ["lifeops", "automation"],
	UNBLOCK_APPS: ["lifeops", "automation"],
	GET_APP_BLOCK_STATUS: ["lifeops"],
	APPROVE_REQUEST: ["lifeops"],
	REJECT_REQUEST: ["lifeops"],
	REQUEST_FIELD_FILL: ["lifeops", "browser"],
	ADD_AUTOFILL_WHITELIST: ["lifeops", "settings"],
	LIST_AUTOFILL_WHITELIST: ["lifeops"],
	PASSWORD_MANAGER: ["lifeops", "settings"],
	CROSS_PLATFORM_GATEWAY: ["lifeops", "social"],
	PUBLISH_DEVICE_INTENT: ["lifeops", "automation"],
	CHAT_THREAD_CONTROL: ["lifeops", "social"],
	CALENDAR_ACTION: ["lifeops", "automation"],
	ELEVATE_TRUST: ["social", "system"],
	REVOKE_TRUST: ["social", "system"],
	BLOCK_USER: ["social", "system"],
	UNBLOCK_USER: ["social", "system"],
	MANAGE_PLUGINS: ["system"],
	MANAGE_SECRETS: ["system"],
	SHELL_EXEC: ["system", "code"],
	RESTART: ["system"],
	CONFIGURE_RUNTIME: ["system"],
	UPDATE_IDENTITY: ["settings", "character"],
	UPDATE_AI_PROVIDER: ["settings"],
	TOGGLE_CAPABILITY: ["settings"],
	TOGGLE_AUTO_TRAINING: ["settings"],
	TOGGLE_CONNECTOR: ["connectors"],
	SAVE_CONNECTOR_CONFIG: ["connectors"],
	DISCONNECT_CONNECTOR: ["connectors"],
	LIST_CONNECTORS: ["connectors"],
	OAUTH_CONNECT: ["system", "social"],
	SEARCH_ACTIONS: ["system", "knowledge"],
	FINISH: ["general"],
};

export const PROVIDER_CONTEXT_MAP: Record<string, AgentContext[]> = {
	time: ["general"],
	boredom: ["general"],
	facts: ["general", "knowledge"],
	knowledge: ["knowledge"],
	entities: ["social"],
	relationships: ["social"],
	recentMessages: ["general"],
	worldInfo: ["general"],
	roleInfo: ["general"],
	settings: ["system"],
	"page-scoped-context": [
		"page",
		"browser",
		"wallet",
		"character",
		"automation",
		"apps",
		"connectors",
		"plugins",
		"settings",
		"lifeops",
		"phone",
	],
	available_apps: ["apps"],
	app_browser_workspace: ["browser"],
	walletBalance: ["wallet"],
	walletPortfolio: ["wallet"],
	tokenPrices: ["wallet", "knowledge"],
	chainInfo: ["wallet"],
	wallet: ["wallet"],
	"get-balance": ["wallet"],
	"solana-wallet": ["wallet"],
	CODING_AGENT_EXAMPLES: ["code", "automation"],
	ACTIVE_WORKSPACE_CONTEXT: ["code", "automation"],
	contacts: ["social"],
	trustScores: ["social"],
	platformIdentity: ["social"],
	cronJobs: ["automation"],
	taskList: ["automation", "code"],
	agentConfig: ["system"],
	pluginList: ["system"],
};

function normalizeContexts(
	contexts: AgentContext[] | undefined,
): AgentContext[] {
	return Array.isArray(contexts)
		? contexts.filter((context): context is AgentContext => Boolean(context))
		: [];
}

export function resolveActionContexts(action: Action): AgentContext[] {
	const declared = normalizeContexts(action.contexts);
	if (declared.length > 0) {
		return declared;
	}

	return ACTION_CONTEXT_MAP[action.name.toUpperCase()] ?? ["general"];
}

export function resolveProviderContexts(provider: Provider): AgentContext[] {
	const declared = normalizeContexts(provider.contexts);
	if (declared.length > 0) {
		return declared;
	}

	return (
		PROVIDER_CONTEXT_MAP[provider.name] ??
		PROVIDER_CONTEXT_MAP[provider.name.toLowerCase()] ??
		PROVIDER_CONTEXT_MAP[provider.name.toUpperCase()] ?? ["general"]
	);
}
