export {
	type ConnectorIdentityMetadataMapping,
	type ConnectorSourceDefinition,
	type ConnectorSourceKind,
	type ConnectorSourceMetadata,
	expandConnectorSourceFilter,
	getConnectorIdentityMetadataMapping,
	getConnectorSourceAliases,
	getConnectorSourceMetadata,
	getConnectorWorldIdMetadataKeys,
	isPassiveConnectorSource,
	LEGACY_DISCORD_CONNECTOR_SOURCE_METADATA,
	LEGACY_DISCORD_CONNECTOR_SOURCE_OWNER,
	normalizeConnectorSource,
	registerConnectorSourceAliases,
	registerConnectorSourceDefinitions,
	registerConnectorSourceMetadata,
	unregisterConnectorSourceMetadataOwner,
} from "@elizaos/common";
