/**
 * Generate per-developer dev secrets for the local supabase-storage container
 * defined in cloud/docker-compose.yml.
 *
 * Outputs to stdout the four env vars required by that compose file:
 *   LOCAL_STORAGE_DB_PASSWORD
 *   LOCAL_STORAGE_JWT_SECRET
 *   LOCAL_STORAGE_ANON_KEY        (HS256 JWT signed with the secret, role=anon)
 *   LOCAL_STORAGE_SERVICE_KEY     (HS256 JWT signed with the secret, role=service_role)
 *
 * Append to cloud/.env:
 *   bun packages/scripts/gen-local-storage-env.ts >> ../.env
 *   # or, run from cloud/:
 *   bun packages/scripts/gen-local-storage-env.ts >> .env
 *
 * Each invocation generates fresh values. Never reuse these for any publicly
 * reachable host — the supabase-storage container is intended for localhost
 * dev only.
 *
 * Note: Uses console.log intentionally as this is a CLI script meant for
 * shell-redirected output.
 */
import crypto from "crypto";

function base64url(buf: Buffer | string): string {
  const b = typeof buf === "string" ? Buffer.from(buf) : buf;
  return b.toString("base64").replace(/=+$/, "").replace(/\+/g, "-").replace(/\//g, "_");
}

function signHS256(secret: string, payload: object): string {
  const header = { alg: "HS256", typ: "JWT" };
  const encHeader = base64url(JSON.stringify(header));
  const encPayload = base64url(JSON.stringify(payload));
  const signingInput = `${encHeader}.${encPayload}`;
  const sig = crypto.createHmac("sha256", secret).update(signingInput).digest();
  return `${signingInput}.${base64url(sig)}`;
}

const dbPassword = crypto.randomBytes(24).toString("base64url");
const jwtSecret = crypto.randomBytes(48).toString("base64url");
const anonKey = signHS256(jwtSecret, { role: "anon", iss: "supabase-local-dev" });
const serviceKey = signHS256(jwtSecret, { role: "service_role", iss: "supabase-local-dev" });

console.log("# --- generated by gen-local-storage-env.ts ---");
console.log(`LOCAL_STORAGE_DB_PASSWORD=${dbPassword}`);
console.log(`LOCAL_STORAGE_JWT_SECRET=${jwtSecret}`);
console.log(`LOCAL_STORAGE_ANON_KEY=${anonKey}`);
console.log(`LOCAL_STORAGE_SERVICE_KEY=${serviceKey}`);
