/**
 * Builds the inference listener with a fresh key generated by the private dstack
 * guest service. Key material stays in this CVM process and is never returned by
 * the public listener. Guest socket confinement is a measured deployment duty.
 */
import {
  createPrivateKey,
  createPublicKey,
  X509Certificate,
} from "node:crypto";
import { lstat } from "node:fs/promises";
import { request } from "node:http";
import { isAbsolute } from "node:path";
import type { Server } from "node:tls";
import { ElizaError } from "@elizaos/core";
import { z } from "zod";
import {
  type AttestedInferenceServerConfig,
  createAttestedInferenceServer,
} from "./tee-attested-inference.ts";

/** IssueCert v1 generates its own fresh key; no caller key or CSR is accepted. */
export async function createDstackAttestedInferenceServer(
  config: Omit<AttestedInferenceServerConfig, "key" | "cert"> & {
    dnsName: string;
  },
): Promise<Server> {
  const socketPath = config.guestSocketPath;
  if (!isAbsolute(socketPath) || !(await lstat(socketPath)).isSocket())
    throw new ElizaError("TLS identity requires a confined guest Unix socket", {
      code: "TEE_TLS_IDENTITY_REJECTED",
    });
  const dnsName = z
    .string()
    .regex(
      /^(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?\.)*[a-zA-Z0-9](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?$/,
    )
    .parse(config.dnsName);
  const signal = AbortSignal.timeout(config.timeoutMs ?? 60000);
  const identity = await new Promise<{
    key: string;
    certificate_chain: string[];
  }>((resolve, reject) => {
    const body = JSON.stringify({
      subject: dnsName,
      alt_names: [dnsName],
      usage_ra_tls: true,
      usage_server_auth: true,
      usage_client_auth: false,
      with_app_info: true,
    });
    const req = request(
      {
        socketPath,
        path: "/v1/IssueCert",
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Content-Length": Buffer.byteLength(body),
        },
        signal,
      },
      (res) => {
        if (res.statusCode !== 200) {
          res.destroy();
          reject(
            new ElizaError("Guest certificate issuance rejected", {
              code: "TEE_TLS_IDENTITY_REJECTED",
            }),
          );
          return;
        }
        const chunks: Buffer[] = [];
        let size = 0;
        res.on("data", (chunk: Buffer) => {
          size += chunk.length;
          if (size > 1024 * 1024)
            req.destroy(
              new ElizaError(
                "Guest certificate response exceeds protocol limit",
                { code: "TEE_TLS_IDENTITY_REJECTED" },
              ),
            );
          else chunks.push(chunk);
        });
        res.on("error", reject);
        res.on("end", () => {
          try {
            resolve(
              z
                .object({
                  key: z.string().min(1),
                  certificate_chain: z.array(z.string().min(1)).min(1),
                })
                .parse(JSON.parse(Buffer.concat(chunks).toString("utf8"))),
            );
          } catch (error) {
            // error-policy:J3 Malformed private replies never create a listener.
            reject(
              new ElizaError("Invalid guest certificate response", {
                code: "TEE_TLS_IDENTITY_REJECTED",
                cause: error,
              }),
            );
          }
        });
      },
    );
    req.on("error", reject);
    req.end(body);
  });
  const key = createPrivateKey(identity.key);
  const leaf = new X509Certificate(identity.certificate_chain[0]);
  if (
    !createPublicKey(key)
      .export({ type: "spki", format: "der" })
      .equals(leaf.publicKey.export({ type: "spki", format: "der" })) ||
    leaf.checkHost(dnsName) === undefined
  )
    throw new ElizaError(
      "Guest certificate identity does not match its key or DNS name",
      { code: "TEE_TLS_IDENTITY_REJECTED" },
    );
  return createAttestedInferenceServer({
    ...config,
    key: identity.key,
    cert: identity.certificate_chain.join("\n"),
  });
}
