/** Public surface of @elizaos/evidence: schema, bundle builder, provenance, ingestors. */

export {
  type AddArtifactOptions,
  type BundleProvenance,
  type CreateBundleOptions,
  createBundle,
  EvidenceBundle,
  type FinalizeResult,
  formatRunId,
  type VerifyIssue,
  type VerifyReport,
  verifyBundle,
} from "./bundle.ts";
export { canonicalJson, canonicalJsonBytes } from "./canonical.ts";
export {
  EvidenceError,
  type EvidenceErrorOptions,
  EvidenceValidationError,
  type ValidationIssue,
} from "./errors.ts";
export {
  type IngestResult,
  ingestAllSilos,
  ingestNamedSilo,
  SILO_NAMES,
} from "./ingest.ts";
export {
  buildEnvFingerprint,
  collectGitProvenance,
  type GitProvenance,
  type ProcessFacts,
  resolveRunnerKind,
} from "./provenance.ts";
export {
  ARTIFACT_KINDS,
  type ArtifactEntry,
  type ArtifactKind,
  type BundleManifest,
  type BundleMeta,
  isBundleRelativePath,
  parseManifest,
  parseMeta,
  RUNNER_KINDS,
  type RunnerKind,
  TIERS,
  type Tier,
} from "./schema.ts";

// Tiered heuristic analyzer registry (#14542): OCR engines, colour/brand/diff
// heuristics, perceptual hash, aria-tree ops, video keyframes, and the runner
// that fans them over a bundle into per-subject `analysis.json`.
export {
  ANALYZERS,
  type AnalysisDocument,
  type Analyzer,
  type AnalyzeOptions,
  type AnalyzerContext,
  type AnalyzerExpectations,
  type AnalyzerFragment,
  type AnalyzerInput,
  type AnalyzerResult,
  type AnalyzerStatus,
  type AnalyzeResult,
  analyzeArtifacts,
  analyzersForKind,
  analyzersForTier,
  AppleVisionOcrEngine,
  type AriaDiffEntry,
  type AriaNode,
  type AriaTreeData,
  ariaTreeAnalyzer,
  type BaselineResolver,
  BRAND_THRESHOLDS,
  type BrandCheck,
  type BrandData,
  brandColorFractions,
  brandRulesAnalyzer,
  type ChangeData,
  type ChangedRegion,
  changeMetric,
  classifyColor,
  clusterRegions,
  type ColorBucket,
  type ColorFractions,
  colorCornersAnalyzer,
  colorFractionsFromRaw,
  colorPaletteAnalyzer,
  CORNER_POSITIONS,
  type CornerPosition,
  type CornersData,
  type CornerSwatch,
  cornerSwatches,
  diffAriaSnapshots,
  diffChangeAnalyzer,
  diffRegionAnalyzer,
  dominantPalette,
  evaluateBrand,
  evaluateRegionExpectations,
  extractKeyframes,
  ffmpegAvailable,
  getAnalyzer,
  hammingDistance,
  isSameScreen,
  type KeyframeRecord,
  type KeyframesData,
  makeOcrAnalyzer,
  normalizeAriaSnapshot,
  type OcrAvailable,
  type OcrData,
  type OcrEngine,
  type OcrRecognition,
  type OcrUnavailable,
  ocrTesseractAnalyzer,
  ocrUnlimitedAnalyzer,
  type PaletteData,
  type PaletteSwatch,
  parseAriaSnapshot,
  type PerceptualHashData,
  perceptualHash,
  perceptualHashAnalyzer,
  type PruneOptions,
  pruneAriaSnapshot,
  type RegionAssertion,
  type RegionDiffData,
  type RegionExpectation,
  round4,
  SAME_SCREEN_THRESHOLD,
  type SubjectAnalysis,
  TesseractOcrEngine,
  tierRunnable,
  UnlimitedOcrEngine,
  videoKeyframesAnalyzer,
} from "./analyzers/index.ts";
