/**
 * SkunkScanAI Investigation Engine
 *
 * Universal investigation data models.
 *
 * These models are intentionally blockchain-independent so that the
 * Investigation Engine can support Solana, Ethereum, Base, BNB,
 * Bitcoin and future blockchain connectors.
 */

export type InvestigationStatus =
  | "draft"
  | "active"
  | "paused"
  | "completed"
  | "archived";

export type InvestigationPriority =
  | "low"
  | "medium"
  | "high"
  | "critical";

export type InvestigationChain =
  | "solana"
  | "ethereum"
  | "base"
  | "bnb"
  | "bitcoin"
  | "xrp"
  | "stellar"
  | "cosmos"
  | "sui"
  | "aptos"
  | "unknown";

export type InvestigationSubjectType =
  | "wallet"
  | "transaction"
  | "token"
  | "entity"
  | "contract"
  | "protocol"
  | "exchange"
  | "bridge"
  | "unknown";

export type InvestigationEvidenceType =
  | "wallet_profile"
  | "transaction"
  | "funding"
  | "portfolio"
  | "risk"
  | "label"
  | "activity"
  | "whale"
  | "relationship"
  | "external_reference"
  | "investigator_note"
  | "unknown";

export type InvestigationFindingSeverity =
  | "informational"
  | "low"
  | "medium"
  | "high"
  | "critical";

export type InvestigationConfidenceLevel =
  | "low"
  | "medium"
  | "high"
  | "unknown";

/**
 * A wallet, transaction, token, entity or other object being investigated.
 */
export interface InvestigationSubject {
  id: string;
  type: InvestigationSubjectType;
  chain: InvestigationChain;
  identifier: string;
  label?: string;
  description?: string;
  addedAt: string;
  metadata?: Record<string, unknown>;
}

/**
 * A single piece of evidence collected during an investigation.
 */
export interface InvestigationEvidence {
  id: string;
  type: InvestigationEvidenceType;
  subjectId?: string;
  title: string;
  description: string;
  source: string;
  observedAt?: string;
  collectedAt: string;
  confidence: InvestigationConfidenceLevel;
  data?: Record<string, unknown>;
}

/**
 * An analytical conclusion derived from one or more evidence items.
 */
export interface InvestigationFinding {
  id: string;
  title: string;
  description: string;
  severity: InvestigationFindingSeverity;
  confidence: InvestigationConfidenceLevel;
  evidenceIds: string[];
  limitations: string[];
  createdAt: string;
  updatedAt: string;
}

/**
 * A note manually added by an investigator or generated by the platform.
 */
export interface InvestigationNote {
  id: string;
  author: string;
  content: string;
  createdAt: string;
  updatedAt?: string;
}

/**
 * Records changes made during an investigation.
 *
 * This will later support the Investigation Replay feature.
 */
export interface InvestigationAuditEvent {
  id: string;
  action:
    | "investigation_created"
    | "investigation_updated"
    | "status_changed"
    | "subject_added"
    | "subject_removed"
    | "evidence_added"
    | "finding_added"
    | "note_added"
    | "report_generated";
  description: string;
  actor: string;
  createdAt: string;
  metadata?: Record<string, unknown>;
}

/**
 * Main SkunkScanAI investigation case.
 */
export interface InvestigationCase {
  id: string;
  title: string;
  description?: string;

  status: InvestigationStatus;
  priority: InvestigationPriority;

  subjects: InvestigationSubject[];
  evidence: InvestigationEvidence[];
  findings: InvestigationFinding[];
  notes: InvestigationNote[];
  auditTrail: InvestigationAuditEvent[];

  tags: string[];

  createdBy: string;
  createdAt: string;
  updatedAt: string;
  completedAt?: string;

  metadata?: Record<string, unknown>;
}

/**
 * Input required when creating a new investigation.
 */
export interface CreateInvestigationInput {
  title: string;
  description?: string;
  priority?: InvestigationPriority;
  createdBy?: string;
  tags?: string[];
}

/**
 * High-level investigation statistics.
 */
export interface InvestigationSummary {
  investigationId: string;
  status: InvestigationStatus;
  priority: InvestigationPriority;

  subjectCount: number;
  evidenceCount: number;
  findingCount: number;
  noteCount: number;

  criticalFindingCount: number;
  highFindingCount: number;

  chains: InvestigationChain[];

  createdAt: string;
  updatedAt: string;
}
