/**
 * SkunkScanAI Investigation Engine
 *
 * Universal investigation data models.
 *
 * These models are intentionally blockchain-independent so that the
 * Investigation Engine can support Solana, Ethereum, Base, BNB,
 * Bitcoin and future blockchain connectors.
 */

/**
 * Version of the universal Investigation Engine data structure.
 *
 * This is separate from the application version so stored investigations
 * can be migrated safely when the investigation schema changes.
 */
export type InvestigationSchemaVersion = "1.0";

/**
 * Describes how an investigation was created.
 */
export type InvestigationOrigin =
  | "api"
  | "web_app"
  | "scheduled"
  | "manual"
  | "system"
  | "unknown";

/**
 * Describes the type of investigation execution.
 */
export type InvestigationRunType =
  | "initial"
  | "refresh"
  | "reanalysis"
  | "comparison"
  | "unknown";

export type InvestigationStatus =
  | "draft"
  | "active"
  | "paused"
  | "completed"
  | "archived";

export type InvestigationPriority =
  | "low"
  | "medium"
  | "high"
  | "critical";

export type InvestigationChain =
  | "solana"
  | "ethereum"
  | "base"
  | "bnb"
  | "bitcoin"
  | "xrp"
  | "stellar"
  | "cosmos"
  | "sui"
  | "aptos"
  | "unknown";

export type InvestigationSubjectType =
  | "wallet"
  | "transaction"
  | "token"
  | "entity"
  | "contract"
  | "protocol"
  | "exchange"
  | "bridge"
  | "unknown";

export type InvestigationEvidenceType =
  | "wallet_profile"
  | "transaction"
  | "funding"
  | "portfolio"
  | "risk"
  | "label"
  | "activity"
  | "whale"
  | "relationship"
  | "external_reference"
  | "investigator_note"
  | "unknown";

export type InvestigationFindingSeverity =
  | "informational"
  | "low"
  | "medium"
  | "high"
  | "critical";

export type InvestigationConfidenceLevel =
  | "low"
  | "medium"
  | "high"
  | "unknown";

/**
 * Metadata describing one execution of an investigation.
 *
 * This supports investigation refreshes, reanalysis, historical comparison,
 * performance monitoring and future persistent investigation storage.
 */
export interface InvestigationExecution {
  runId: string;
  runType: InvestigationRunType;
  startedAt: string;
  completedAt?: string;
  durationMs?: number;
  successful: boolean;
  errorMessage?: string;
  engineVersion?: string;
  metadata?: Record<string, unknown>;
}

/**
 * A wallet, transaction, token, entity or other object being investigated.
 */
export interface InvestigationSubject {
  id: string;
  type: InvestigationSubjectType;
  chain: InvestigationChain;
  identifier: string;
  label?: string;
  description?: string;
  addedAt: string;
  metadata?: Record<string, unknown>;
}

/**
 * A single piece of evidence collected during an investigation.
 */
export interface InvestigationEvidence {
  id: string;
  type: InvestigationEvidenceType;
  subjectId?: string;
  title: string;
  description: string;
  source: string;
  observedAt?: string;
  collectedAt: string;
  confidence: InvestigationConfidenceLevel;
  data?: Record<string, unknown>;
}

/**
 * An analytical conclusion derived from one or more evidence items.
 */
export interface InvestigationFinding {
  id: string;
  title: string;
  description: string;
  severity: InvestigationFindingSeverity;
  confidence: InvestigationConfidenceLevel;
  evidenceIds: string[];
  limitations: string[];
  createdAt: string;
  updatedAt: string;
}

/**
 * A note manually added by an investigator or generated by the platform.
 */
export interface InvestigationNote {
  id: string;
  author: string;
  content: string;
  createdAt: string;
  updatedAt?: string;
}

/**
 * Records changes made during an investigation.
 *
 * This will later support the Investigation Replay feature.
 */
export interface InvestigationAuditEvent {
  id: string;
  action:
    | "investigation_created"
    | "investigation_updated"
    | "investigation_refreshed"
    | "investigation_reanalyzed"
    | "status_changed"
    | "subject_added"
    | "subject_removed"
    | "evidence_added"
    | "finding_added"
    | "note_added"
    | "report_generated";
  description: string;
  actor: string;
  createdAt: string;
  metadata?: Record<string, unknown>;
}

/**
 * Main SkunkScanAI investigation case.
 */
export interface InvestigationCase {
  id: string;
  title: string;
  description?: string;

  /**
   * Version of the InvestigationCase data schema.
   */
  schemaVersion?: InvestigationSchemaVersion;

  /**
   * Revision number of this investigation.
   *
   * Revision 1 represents the initial investigation. The number increases
   * whenever the investigation is refreshed or materially updated.
   */
  revision?: number;

  /**
   * Describes where the investigation request originated.
   */
  origin?: InvestigationOrigin;

  status: InvestigationStatus;
  priority: InvestigationPriority;

  subjects: InvestigationSubject[];
  evidence: InvestigationEvidence[];
  findings: InvestigationFinding[];
  notes: InvestigationNote[];
  auditTrail: InvestigationAuditEvent[];

  /**
   * Historical execution records for the investigation.
   */
  executions?: InvestigationExecution[];

  tags: string[];

  createdBy: string;
  createdAt: string;
  updatedAt: string;
  completedAt?: string;

  /**
   * Most recent successful investigation execution time.
   */
  lastRunAt?: string;

  metadata?: Record<string, unknown>;
}

/**
 * Input required when creating a new investigation.
 */
export interface CreateInvestigationInput {
  title: string;
  description?: string;
  priority?: InvestigationPriority;
  createdBy?: string;
  tags?: string[];
  origin?: InvestigationOrigin;
}

/**
 * High-level investigation statistics.
 */
export interface InvestigationSummary {
  investigationId: string;
  status: InvestigationStatus;
  priority: InvestigationPriority;

  schemaVersion?: InvestigationSchemaVersion;
  revision?: number;
  origin?: InvestigationOrigin;

  subjectCount: number;
  evidenceCount: number;
  findingCount: number;
  noteCount: number;
  executionCount?: number;

  criticalFindingCount: number;
  highFindingCount: number;

  chains: InvestigationChain[];

  createdAt: string;
  updatedAt: string;
  lastRunAt?: string;
}
