// Compatibility exports for app packages that still import app UI helpers from
// @elizaos/app-core. The implementations live in @elizaos/ui.

export type {
  AppDetailExtensionComponent,
  AppDetailExtensionProps,
  AppOperatorSurfaceComponent,
  AppOperatorSurfaceFocus,
  AppOperatorSurfaceProps,
  AppOperatorSurfaceVariant,
  AppRunHealthState,
  AppRunSummary,
  AppRunViewerAttachment,
  AppSessionJsonValue,
  BabylonActivityItem,
  BabylonAgentGoal,
  BabylonAgentStatus,
  BabylonChatMessage,
  BabylonPredictionMarket,
  BabylonTeamAgent,
  BabylonWallet,
  GameOperatorAction,
  GameOperatorEvent,
  GameOperatorShellProps,
  OverlayApp,
  OverlayAppContext,
  SelectedAppRun,
  SurfaceTone,
} from "@elizaos/ui";
export {
  Button,
  client,
  ElizaClient,
  formatDetailTimestamp,
  GameOperatorShell,
  getAppDetailExtension,
  getAppOperatorSurface,
  Input,
  PagePanel,
  registerDetailExtension,
  registerOperatorSurface,
  registerOverlayApp,
  Spinner,
  SurfaceBadge,
  SurfaceCard,
  SurfaceEmptyState,
  SurfaceGrid,
  SurfaceSection,
  selectLatestRunForApp,
  toneForHealthState,
  toneForStatusText,
  toneForViewerAttachment,
  useApp,
} from "@elizaos/ui";
