from elizaos_plugin_github.config import GitHubConfig
from elizaos_plugin_github.error import (
    BranchExistsError,
    BranchNotFoundError,
    ClientNotInitializedError,
    ConfigError,
    FileNotFoundError,
    GitHubApiError,
    GitHubError,
    InvalidArgumentError,
    IssueNotFoundError,
    MergeConflictError,
    MissingSettingError,
    NetworkError,
    PermissionDeniedError,
    PullRequestNotFoundError,
    RateLimitedError,
    RepositoryNotFoundError,
    TimeoutError,
    ValidationError,
)
from elizaos_plugin_github.service import GitHubService
from elizaos_plugin_github.types import (
    CreateBranchParams,
    CreateCommentParams,
    CreateCommitParams,
    CreateIssueParams,
    CreatePullRequestParams,
    CreateReviewParams,
    FileChange,
    GitHubBranch,
    GitHubComment,
    GitHubCommit,
    GitHubDirectoryEntry,
    GitHubEventType,
    GitHubFileContent,
    GitHubIssue,
    GitHubLabel,
    GitHubMilestone,
    GitHubPullRequest,
    GitHubRepository,
    GitHubReview,
    GitHubUser,
    IssueState,
    ListIssuesParams,
    ListPullRequestsParams,
    MergePullRequestParams,
    PullRequestState,
    RepositoryRef,
    ReviewState,
    UpdateIssueParams,
    UpdatePullRequestParams,
)

__all__ = [
    # Config
    "GitHubConfig",
    # Errors
    "GitHubError",
    "ClientNotInitializedError",
    "ConfigError",
    "MissingSettingError",
    "InvalidArgumentError",
    "RepositoryNotFoundError",
    "BranchNotFoundError",
    "FileNotFoundError",
    "IssueNotFoundError",
    "PullRequestNotFoundError",
    "PermissionDeniedError",
    "RateLimitedError",
    "MergeConflictError",
    "BranchExistsError",
    "ValidationError",
    "GitHubApiError",
    "NetworkError",
    "TimeoutError",
    # Types
    "RepositoryRef",
    "FileChange",
    "IssueState",
    "GitHubIssue",
    "CreateIssueParams",
    "UpdateIssueParams",
    "ListIssuesParams",
    "PullRequestState",
    "GitHubPullRequest",
    "CreatePullRequestParams",
    "UpdatePullRequestParams",
    "ListPullRequestsParams",
    "MergePullRequestParams",
    "ReviewState",
    "GitHubReview",
    "CreateReviewParams",
    "GitHubComment",
    "CreateCommentParams",
    "GitHubBranch",
    "CreateBranchParams",
    "GitHubCommit",
    "CreateCommitParams",
    "GitHubFileContent",
    "GitHubDirectoryEntry",
    "GitHubRepository",
    "GitHubUser",
    "GitHubLabel",
    "GitHubMilestone",
    "GitHubEventType",
    # Service
    "GitHubService",
]

__version__ = "1.0.0"
PLUGIN_NAME = "github"
PLUGIN_DESCRIPTION = "GitHub integration for elizaOS agents"
