import type { Action, AgentContext, Provider } from "../types/components";

export const ACTION_CONTEXT_MAP: Record<string, AgentContext[]> = {
	NONE: ["general"],
	IGNORE: ["general"],
	CONTINUE: ["general"],
	REPLY: ["general"],
	HELP: ["general"],
	STATUS: ["general"],
	MODELS: ["general"],
	CONFIGURE: ["general", "settings"],
	APP: ["connectors"],
	PLUGIN: ["connectors", "admin"],
	AUTOMATION_ACTIONS: ["general", "automation"],
	BROWSER_ACTIONS: ["general", "browser"],
	CHARACTER_ACTIONS: ["general", "settings"],
	CONNECTOR_ACTION: ["connectors"],
	CONNECTOR_ACTIONS: ["general", "connectors"],
	LIFEOPS_ACTIONS: ["general", "tasks", "automation"],
	PHONE_ACTIONS: ["general", "messaging"],
	SETTINGS_ACTIONS: ["general", "settings"],
	WALLET_ACTION: ["wallet"],
	WALLET_ACTIONS: ["general", "wallet"],
	MODIFY_CHARACTER: ["settings", "admin"],
	UPDATE_OWNER_NAME: ["settings"],
	SET_USER_NAME: ["settings"],
	SEND_TOKEN: ["wallet"],
	TRANSFER: ["wallet"],
	TRANSFER_TOKEN: ["wallet"],
	CHECK_BALANCE: ["wallet"],
	GET_BALANCE: ["wallet"],
	GET_RECEIVE_ADDRESS: ["wallet"],
	PREPARE_SWAP: ["wallet"],
	PREPARE_TRANSFER: ["wallet"],
	EXECUTE_TRADE: ["wallet"],
	CROSS_CHAIN_TRANSFER: ["wallet"],
	SWAP_TOKEN: ["wallet", "automation"],
	SWAP: ["wallet", "automation"],
	SWAP_SOLANA: ["wallet", "automation"],
	BRIDGE_TOKEN: ["wallet"],
	APPROVE_TOKEN: ["wallet"],
	SIGN_MESSAGE: ["wallet"],
	SIGN_WITH_ELIZA_WALLET: ["wallet"],
	APPROVE_ELIZA_WALLET_REQUEST: ["wallet"],
	REJECT_ELIZA_WALLET_REQUEST: ["wallet"],
	DEPLOY_CONTRACT: ["wallet", "code"],
	CREATE_GOVERNANCE_PROPOSAL: ["wallet", "social_posting"],
	GOV_PROPOSE: ["wallet", "social_posting"],
	VOTE_ON_PROPOSAL: ["wallet", "social_posting"],
	GOV_VOTE: ["wallet", "social_posting"],
	GOV_QUEUE: ["wallet", "social_posting"],
	GOV_EXECUTE: ["wallet", "social_posting"],
	STAKE: ["wallet"],
	UNSTAKE: ["wallet"],
	CLAIM_REWARDS: ["wallet"],
	GET_TOKEN_PRICE: ["wallet", "knowledge"],
	GET_PORTFOLIO: ["wallet"],
	CREATE_WALLET: ["wallet"],
	IMPORT_WALLET: ["wallet"],
	SEARCH_KNOWLEDGE: ["knowledge"],
	SEARCH: ["knowledge", "browser"],
	ADD_KNOWLEDGE: ["knowledge"],
	REMEMBER: ["knowledge"],
	RECALL: ["knowledge"],
	LEARN_FROM_EXPERIENCE: ["knowledge"],
	SEARCH_WEB: ["knowledge", "browser"],
	WEB_SEARCH: ["knowledge", "browser"],
	SUMMARIZE: ["knowledge"],
	ANALYZE: ["knowledge"],
	CREATE_TASK: ["automation"],
	START_CODING_TASK: ["code", "automation"],
	BROWSER_SESSION: ["browser"],
	BROWSER_ACTION: ["browser"],
	MANAGE_ELIZA_BROWSER_WORKSPACE: ["browser"],
	MANAGE_LIFEOPS_BROWSER: ["browser"],
	BROWSER_BRIDGE_INSTALL: ["browser"],
	BROWSER_BRIDGE_REVEAL_FOLDER: ["browser"],
	BROWSER_BRIDGE_OPEN_MANAGER: ["browser"],
	BROWSER_BRIDGE_REFRESH: ["browser"],
	BROWSE: ["browser"],
	SCREENSHOT: ["browser", "media"],
	NAVIGATE: ["browser"],
	CLICK: ["browser"],
	TYPE_TEXT: ["browser"],
	EXTRACT_PAGE: ["browser", "knowledge"],
	SPAWN_AGENT: ["code", "automation"],
	SEND_TO_AGENT: ["code", "automation"],
	LIST_AGENTS: ["code", "automation"],
	STOP_AGENT: ["code", "automation"],
	TASK_HISTORY: ["code", "automation"],
	TASK_CONTROL: ["code", "automation"],
	TASK_SHARE: ["code", "automation"],
	PROVISION_WORKSPACE: ["code", "automation"],
	FINALIZE_WORKSPACE: ["code", "automation"],
	KILL_AGENT: ["code", "automation"],
	UPDATE_AGENT: ["code", "admin"],
	RUN_SCRIPT: ["code", "automation"],
	REVIEW_CODE: ["code"],
	GENERATE_CODE: ["code"],
	EXECUTE_TASK: ["code", "automation"],
	CREATE_SUBTASK: ["code", "automation"],
	COMPLETE_TASK: ["code", "automation"],
	CANCEL_TASK: ["code", "automation"],
	GENERATE_IMAGE: ["media"],
	DESCRIBE_IMAGE: ["media", "knowledge"],
	DESCRIBE_VIDEO: ["media", "knowledge"],
	DESCRIBE_AUDIO: ["media", "knowledge"],
	TEXT_TO_SPEECH: ["media"],
	TRANSCRIBE: ["media", "knowledge"],
	UPLOAD_FILE: ["media"],
	CREATE_CRON: ["automation"],
	UPDATE_CRON: ["automation"],
	DELETE_CRON: ["automation"],
	LIST_CRONS: ["automation"],
	PAUSE_CRON: ["automation"],
	RUN_CRON: ["automation"],
	CREATE_TRIGGER_TASK: ["automation"],
	UPDATE_TRIGGER_TASK: ["automation"],
	DELETE_TRIGGER_TASK: ["automation"],
	RUN_TRIGGER_NOW: ["automation"],
	CREATE_WORKFLOW: ["automation"],
	DELETE_WORKFLOW: ["automation"],
	TOGGLE_WORKFLOW_ACTIVE: ["automation"],
	PROMOTE_TASK_TO_WORKFLOW: ["automation"],
	MANAGE_TASKS: ["automation"],
	CREATE_N8N_WORKFLOW: ["automation"],
	ACTIVATE_N8N_WORKFLOW: ["automation"],
	DEACTIVATE_N8N_WORKFLOW: ["automation"],
	DELETE_N8N_WORKFLOW: ["automation"],
	GET_N8N_EXECUTIONS: ["automation"],
	TRIGGER_WEBHOOK: ["automation"],
	SCHEDULE: ["calendar", "automation"],
	SEND_MESSAGE: ["messaging", "connectors"],
	TRIAGE_MESSAGES: ["messaging", "knowledge"],
	SEARCH_MESSAGES: ["messaging", "knowledge"],
	DRAFT_REPLY: ["messaging"],
	DRAFT_FOLLOWUP: ["messaging", "tasks"],
	SEND_DRAFT: ["messaging", "connectors"],
	LIST_INBOX: ["messaging", "knowledge"],
	MANAGE_MESSAGE: ["messaging"],
	SCHEDULE_DRAFT_SEND: ["messaging", "automation"],
	RESPOND_TO_MESSAGE: ["messaging", "connectors"],
	RELATIONSHIP: ["contacts", "messaging", "knowledge"],
	CALENDAR: ["calendar", "automation"],
	CHECKIN: ["tasks", "health", "automation"],
	PROFILE: ["contacts", "settings"],
	ADD_CONTACT: ["contacts"],
	UPDATE_CONTACT: ["contacts"],
	GET_CONTACT: ["contacts"],
	SEARCH_CONTACTS: ["contacts"],
	READ_MESSAGES: ["messaging", "knowledge"],
	READ_CHANNEL: ["messaging", "knowledge"],
	SUMMARIZE_CONVERSATION: ["messaging", "knowledge"],
	CHAT_WITH_ATTACHMENTS: ["messaging", "knowledge", "media"],
	READ_ATTACHMENT: ["knowledge", "media"],
	DOWNLOAD_MEDIA: ["messaging", "media"],
	TRANSCRIBE_MEDIA: ["messaging", "knowledge", "media"],
	LIST_CHANNELS: ["messaging"],
	SERVER_INFO: ["messaging"],
	VOICE_CALL: ["messaging", "connectors"],
	LIFE: ["tasks", "health"],
	COMPUTER_USE: ["browser", "admin"],
	COMPUTE_TRAVEL_BUFFER: ["calendar", "tasks"],
	BOOK_TRAVEL: ["calendar", "payments"],
	SUBSCRIPTIONS: ["subscriptions", "payments"],
	HEALTH: ["health"],
	SCREEN_TIME: ["screen_time"],
	WEBSITE_BLOCK: ["automation", "settings"],
	APP_BLOCK: ["automation", "settings"],
	RESOLVE_REQUEST: ["tasks"],
	AUTOFILL: ["browser", "settings", "secrets"],
	PASSWORD_MANAGER: ["settings", "secrets"],
	DEVICE_INTENT: ["automation", "connectors"],
	CHAT_THREAD: ["messaging"],
	PAYMENTS: ["payments"],
	X: ["social_posting", "messaging"],
	CONNECTOR: ["connectors"],
	TOGGLE_FEATURE: ["settings"],
	ELEVATE_TRUST: ["contacts", "admin"],
	REVOKE_TRUST: ["contacts", "admin"],
	BLOCK_USER: ["messaging", "admin"],
	UNBLOCK_USER: ["messaging", "admin"],
	MANAGE_PLUGINS: ["connectors", "admin"],
	MANAGE_SECRETS: ["secrets", "admin"],
	SHELL_EXEC: ["terminal", "code", "admin"],
	RESTART: ["admin"],
	CONFIGURE_RUNTIME: ["settings", "admin"],
	UPDATE_IDENTITY: ["settings"],
	UPDATE_AI_PROVIDER: ["settings"],
	TOGGLE_CAPABILITY: ["settings"],
	TOGGLE_AUTO_TRAINING: ["settings"],
	TOGGLE_CONNECTOR: ["connectors"],
	SAVE_CONNECTOR_CONFIG: ["connectors"],
	DISCONNECT_CONNECTOR: ["connectors"],
	LIST_CONNECTORS: ["connectors"],
	OAUTH_CONNECT: ["connectors"],
	SEARCH_ACTIONS: ["knowledge", "connectors"],
	FINISH: ["general"],
};

export const PROVIDER_CONTEXT_MAP: Record<string, AgentContext[]> = {
	time: ["general"],
	boredom: ["general"],
	facts: ["general", "knowledge"],
	knowledge: ["knowledge"],
	entities: ["contacts"],
	relationships: ["contacts"],
	recentMessages: ["general"],
	worldInfo: ["general"],
	roleInfo: ["general"],
	settings: ["settings"],
	"page-scoped-context": [
		"browser",
		"wallet",
		"automation",
		"connectors",
		"settings",
		"tasks",
		"messaging",
	],
	available_apps: ["connectors"],
	app_browser_workspace: ["browser"],
	walletBalance: ["wallet"],
	walletPortfolio: ["wallet"],
	tokenPrices: ["wallet", "knowledge"],
	chainInfo: ["wallet"],
	wallet: ["wallet"],
	"get-balance": ["wallet"],
	"solana-wallet": ["wallet"],
	CODING_AGENT_EXAMPLES: ["code", "automation"],
	ACTIVE_WORKSPACE_CONTEXT: ["code", "automation"],
	contacts: ["contacts"],
	trustScores: ["contacts"],
	platformIdentity: ["messaging"],
	cronJobs: ["automation"],
	taskList: ["automation", "code"],
	agentConfig: ["settings", "admin"],
	pluginList: ["connectors", "admin"],
	pluginConfigurationStatus: ["connectors", "admin"],
	pluginState: ["connectors", "admin"],
	registryPlugins: ["connectors", "admin"],
	webSearch: ["knowledge", "browser"],
	imessageContacts: ["contacts", "messaging", "connectors"],
	imessageChatContext: ["messaging", "connectors"],
	bluebubblesChatContext: ["messaging", "connectors"],
	slackChannelState: ["messaging", "connectors"],
	twitchChannelState: ["messaging", "connectors"],
	signalConversationState: ["messaging", "connectors"],
	lineChatContext: ["messaging", "connectors"],
	googleChatUserContext: ["messaging", "connectors"],
	googleChatSpaceState: ["messaging", "connectors"],
	PLATFORM_CHAT_CONTEXT: ["messaging", "connectors"],
	PLATFORM_USER_CONTEXT: ["messaging", "connectors"],
	crossChannelContext: ["messaging", "connectors"],
};

function normalizeContexts(
	contexts: AgentContext[] | undefined,
): AgentContext[] {
	return Array.isArray(contexts)
		? contexts.filter((context): context is AgentContext => Boolean(context))
		: [];
}

export function resolveActionContexts(action: Action): AgentContext[] {
	const declared = normalizeContexts(action.contexts);
	if (declared.length > 0) {
		return declared;
	}

	return ACTION_CONTEXT_MAP[action.name.toUpperCase()] ?? ["general"];
}

export function resolveProviderContexts(provider: Provider): AgentContext[] {
	const declared = normalizeContexts(provider.contexts);
	if (declared.length > 0) {
		return declared;
	}

	return (
		PROVIDER_CONTEXT_MAP[provider.name] ??
		PROVIDER_CONTEXT_MAP[provider.name.toLowerCase()] ??
		PROVIDER_CONTEXT_MAP[provider.name.toUpperCase()] ?? ["general"]
	);
}
