# E2B Template Configuration for ElizaOS AutoCoder Agents

# Template ID (will be set during template upload)
template_id = "eliza-autocoder-base"

# Template name
template_name = "ElizaOS AutoCoder Base Agent"

# Template description
template_description = "Base template for ElizaOS autocoder agents with full Eliza runtime"

# Runtime configuration
[runtime]
# Base image
dockerfile = "Dockerfile"

# Memory limit (in MB)
memory_mb = 2048

# CPU limit (in millicores, 1000 = 1 CPU)
cpu_millicores = 1000

# Timeout for the sandbox (in seconds)
timeout_seconds = 3600

# Environment variables
[env]
NODE_ENV = "production"
ELIZA_LOG_LEVEL = "info"

# Port configuration
[ports]
# Agent communication port
8080 = { name = "agent-comm", description = "Agent communication websocket" }
# Health check port
8081 = { name = "health", description = "Health check endpoint" }

# Volume mounts
[volumes]
"/home/agent/workspace" = { name = "workspace", description = "Agent workspace for code" }
"/home/agent/.eliza" = { name = "config", description = "Agent configuration" } 