"""
E2E Test Configuration and Fixtures

Provides fixtures for full pipeline testing including:
- Trajectory generation
- Database operations
- Scoring validation
- Schema verification
"""

import sys

sys.path.insert(0, ".")

import json
import os
import shutil
import socket
import subprocess
import tempfile
import time
from dataclasses import dataclass
from pathlib import Path
from urllib.request import urlopen

import pytest

from src.training.rewards import BehaviorMetrics

FEED_ROOT = Path(__file__).resolve().parents[5]
ENGINE_ROOT = FEED_ROOT / "packages" / "engine"


def _find_free_port() -> int:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.bind(("127.0.0.1", 0))
        return int(sock.getsockname()[1])


def _wait_for_bridge(url: str, process: subprocess.Popen[str] | None) -> None:
    deadline = time.time() + 60
    last_error: Exception | None = None
    while time.time() < deadline:
        if process is not None and process.poll() is not None:
            output = process.stdout.read() if process.stdout else ""
            raise RuntimeError(f"Simulation bridge exited before becoming healthy.\n{output}")
        try:
            with urlopen(f"{url}/health", timeout=2) as response:
                if response.status == 200:
                    return
        except Exception as exc:
            last_error = exc
        time.sleep(1)
    raise RuntimeError(f"Timed out waiting for simulation bridge at {url}: {last_error}")


@pytest.fixture(scope="session")
def simulation_bridge_url() -> str:
    """Provide a live bridge URL, starting a local bridge if needed."""
    configured_url = os.getenv("SIMULATION_BRIDGE_URL")
    if configured_url:
        _wait_for_bridge(configured_url.rstrip("/"), None)
        return configured_url.rstrip("/")

    port = _find_free_port()
    url = f"http://127.0.0.1:{port}"
    simulation_data_path = tempfile.mkdtemp(prefix="simulation-bridge-")
    env = os.environ.copy()
    env["SIMULATION_BRIDGE_PORT"] = str(port)
    env["SIMULATION_DATA_PATH"] = simulation_data_path
    process = subprocess.Popen(
        ["bun", "run", "src/services/simulation-bridge-server.ts"],
        cwd=ENGINE_ROOT,
        env=env,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
    )
    try:
        _wait_for_bridge(url, process)
    except RuntimeError as exc:
        process.terminate()
        process.wait(timeout=5)
        pytest.skip(f"Simulation bridge unavailable: {exc}")
    try:
        yield url
    finally:
        process.terminate()
        try:
            process.wait(timeout=10)
        except subprocess.TimeoutExpired:
            process.kill()
            process.wait(timeout=10)
        shutil.rmtree(simulation_data_path, ignore_errors=True)


@dataclass
class E2ETrajectory:
    """Full trajectory structure for E2E testing"""

    trajectory_id: str
    agent_id: str
    window_id: str
    scenario_id: str
    archetype: str
    steps_json: str
    final_pnl: float
    episode_length: int
    total_reward: float
    is_training_data: bool = True

    def to_dict(self) -> dict:
        """Convert to dictionary format"""
        return {
            "trajectoryId": self.trajectory_id,
            "agentId": self.agent_id,
            "windowId": self.window_id,
            "scenarioId": self.scenario_id,
            "archetype": self.archetype,
            "stepsJson": self.steps_json,
            "finalPnL": self.final_pnl,
            "episodeLength": self.episode_length,
            "totalReward": self.total_reward,
            "isTrainingData": self.is_training_data,
        }

    def to_json_file_format(self) -> dict:
        """Convert to JSON file format (as generated by TypeScript)"""
        return {
            "trajectory": self.to_dict(),
            "metadata": {
                "generatedAt": "2024-01-01T00:00:00Z",
                "version": "1.0.0",
            },
        }


def create_step(
    step_number: int,
    action_type: str = "trade",
    pnl: float = 0.0,
    balance: float = 10000.0,
    archetype: str | None = None,
    has_llm_call: bool = True,
) -> dict:
    """Create a realistic step for testing"""
    step = {
        "stepNumber": step_number,
        "timestamp": 1704067200000 + step_number * 1000,
        "environmentState": {
            "agentBalance": balance,
            "agentPnL": pnl,
            "agentPoints": 100 + step_number * 10,
            "openPositions": 1 if action_type == "trade" else 0,
            "timestamp": 1704067200000 + step_number * 1000,
        },
        "action": {
            "actionType": action_type,
            "parameters": {
                "ticker": "BTC",
                "amount": 100,
                "confidence": 0.8,
            },
            "success": True,
            "result": {
                "positionId": f"pos-{step_number:03d}",
                "pnl": pnl,
            },
        },
        "reward": pnl / 1000.0,
    }

    # Add archetype to action parameters if provided
    if archetype:
        step["action"]["parameters"]["archetype"] = archetype
        step["action"]["result"]["archetype"] = archetype

    if has_llm_call:
        step["llmCalls"] = [
            {
                "model": "gpt-4",
                "purpose": "action",
                "systemPrompt": "You are a trading agent in Feed prediction markets.",
                "userPrompt": f"Step {step_number}: Analyze market and decide action.",
                "response": f"<thinking>Analyzing step {step_number}...</thinking>\nAction: {action_type}",
                "reasoning": f"Based on market analysis at step {step_number}, executing {action_type}.",
                "temperature": 0.7,
                "maxTokens": 1000,
                "latencyMs": 450,
            }
        ]

    return step


def create_trajectory(
    trajectory_id: str,
    archetype: str = "trader",
    num_steps: int = 10,
    final_pnl: float = 500.0,
    include_archetype_in_steps: bool = False,
    step_archetype: str | None = None,
) -> E2ETrajectory:
    """Create a complete trajectory for testing

    Args:
        trajectory_id: Unique ID for trajectory
        archetype: Archetype at trajectory level (can be empty for batch mode)
        num_steps: Number of steps to generate
        final_pnl: Final PnL value
        include_archetype_in_steps: If True, include archetype in step action params
        step_archetype: Override archetype for steps (useful when trajectory archetype is empty)
    """
    steps = []
    pnl_per_step = final_pnl / num_steps

    # Determine what archetype to use in steps
    archetype_for_steps = step_archetype if step_archetype else archetype

    for i in range(num_steps):
        current_pnl = pnl_per_step * (i + 1)
        step = create_step(
            step_number=i,
            action_type="trade" if i % 3 != 0 else "analyze",
            pnl=current_pnl,
            balance=10000.0 + current_pnl,
            archetype=archetype_for_steps if include_archetype_in_steps else None,
        )
        steps.append(step)

    return E2ETrajectory(
        trajectory_id=trajectory_id,
        agent_id=f"agent-{trajectory_id}",
        window_id="2024-01-01T00:00",
        scenario_id="scenario-001",
        archetype=archetype,
        steps_json=json.dumps(steps),
        final_pnl=final_pnl,
        episode_length=num_steps,
        total_reward=final_pnl / 1000.0,
    )


@pytest.fixture
def temp_trajectory_dir():
    """Create temporary directory for trajectory files"""
    with tempfile.TemporaryDirectory() as tmpdir:
        yield Path(tmpdir)


@pytest.fixture
def sample_trajectories() -> list[E2ETrajectory]:
    """Create a diverse set of test trajectories"""
    return [
        create_trajectory("traj-001", archetype="trader", final_pnl=500.0),
        create_trajectory("traj-002", archetype="degen", final_pnl=1500.0),
        create_trajectory("traj-003", archetype="whale", final_pnl=2000.0),
        create_trajectory("traj-004", archetype="influencer", final_pnl=-200.0),
        create_trajectory("traj-005", archetype="analyst", final_pnl=300.0),
        # Trajectory without archetype at top level (batch recording mode)
        create_trajectory(
            "traj-006",
            archetype="",  # Will be empty at trajectory level
            final_pnl=400.0,
            include_archetype_in_steps=True,  # But present in steps
            step_archetype="trader",  # Archetype is in step action params
        ),
    ]


@pytest.fixture
def trajectories_in_files(temp_trajectory_dir, sample_trajectories) -> Path:
    """Write sample trajectories to JSON files"""
    for traj in sample_trajectories:
        file_path = temp_trajectory_dir / f"{traj.trajectory_id}.json"
        file_path.write_text(json.dumps(traj.to_json_file_format(), indent=2))

    return temp_trajectory_dir


@pytest.fixture
def database_url():
    """Get database URL or skip if not available"""
    url = os.getenv("DATABASE_URL")
    if not url:
        pytest.skip("DATABASE_URL not set - skipping DB E2E tests")
    return url


@pytest.fixture
def behavior_metrics_factory():
    """Factory for creating BehaviorMetrics with various profiles"""

    def create_metrics(profile: str = "default") -> BehaviorMetrics:
        profiles = {
            "default": BehaviorMetrics(
                trades_executed=5,
                profitable_trades=3,
                total_pnl=500.0,
                episode_length=10,
            ),
            "high_trader": BehaviorMetrics(
                trades_executed=20,
                profitable_trades=15,
                total_pnl=2000.0,
                win_rate=0.75,
                episode_length=50,
            ),
            "social_influencer": BehaviorMetrics(
                trades_executed=3,
                profitable_trades=2,
                total_pnl=100.0,
                dms_initiated=20,
                posts_created=10,
                comments_made=50,
                followers_gained=100,
                episode_length=30,
            ),
            "risky_degen": BehaviorMetrics(
                trades_executed=50,
                profitable_trades=20,
                total_pnl=5000.0,
                largest_win=3000.0,
                largest_loss=-1500.0,
                pnl_variance=1000000.0,
                episode_length=100,
            ),
        }
        return profiles.get(profile, profiles["default"])

    return create_metrics
