version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-vector
    restart: unless-stopped

    # -------- credentials & defaults --------
    environment:
      MYSQL_ROOT_PASSWORD: rootsecret
      MYSQL_DATABASE: mydb # created on first boot
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mysecret
      TZ: UTC

    # -------- persistence --------
    volumes:
      - mysql_vector_data:/var/lib/mysql

    # -------- networking --------
    ports:
      - '3306:3306'

    # -------- optional extra server flags --------
    command: >
      --default-authentication-plugin=mysql_native_password
      --innodb-buffer-pool-size=1G
      --log_bin=vector-binlog
      --skip_ssl

volumes:
  mysql_vector_data:
