import {scrubIncomingMessageTextForStorage} from '../security/incoming-message-security';
import {expect,test} from 'vitest';
import {SecretSwapSession,isSecretSwapUnbounded} from '../security/secret-swap';
import {GuardedStreamScanner} from '../security/guarded-stream';
for(const value of ['q7"CredentialTailZ8','q7\nCredentialTailZ8','q7\\CredentialTailZ8','🔐 CredentialTailZ8'])for(const layers of [1,2,4])test(`encoded credential ${JSON.stringify(value)} layers ${layers}`,()=>{
 let input='Public 🔐 prefix '+JSON.stringify({password:value});for(let i=0;i<layers;i++)input=JSON.stringify({text:input,public:'Keep ordinary text'});
 const s=new SecretSwapSession(),wire=s.substituteText(input);expect(wire).not.toContain('CredentialTailZ8');expect(()=>JSON.parse(wire)).not.toThrow();expect(s.restoreText(wire)).toBe(input);expect(s.restoreUserReplyText(wire)).not.toContain('CredentialTailZ8');expect(s.substituteText(wire)).toBe(wire);
});
test('encoded URI authority is protected',()=>{const input=JSON.stringify({text:'URL https://user:q7@CredentialTailZ8@example.invalid/path'}),s=new SecretSwapSession(),wire=s.substituteText(input);expect(wire).not.toContain('CredentialTailZ8');expect(s.restoreText(wire)).toBe(input);});
test('escaped ordinary text remains unchanged',()=>{const input=JSON.stringify({text:'Public "quotation" with a \\ path and 🔐 emoji\nNew line.'});expect(new SecretSwapSession().substituteText(input)).toBe(input);});
test('excessive encoding depth fails closed',()=>{let input='Public "text"';for(let i=0;i<12;i++)input=JSON.stringify({text:input});try{new SecretSwapSession().substituteText(input);throw Error('Expected bounded rejection');}catch(e){expect(isSecretSwapUnbounded(e)).toBe(true);}});
test('every encoded stream split excludes the credential suffix',()=>{const input=JSON.stringify({text:'Draft '+JSON.stringify({password:'q7"CredentialTailZ8'})});for(let split=1;split<input.length;split++){const s=new SecretSwapSession(),scanner=new GuardedStreamScanner({secretSession:s}),parts=[scanner.push('Public padding '.repeat(100)+input.slice(0,split)),scanner.push(input.slice(split)),scanner.flush()];expect(parts.map(p=>p.safe).join('')).not.toContain('CredentialTailZ8');expect(parts.map(p=>p.visible).join('')).not.toContain('CredentialTailZ8');}});

test('escaped JSON fragments without outer quotes protect the complete credential',()=>{let input=JSON.stringify({password:'q7"CredentialTailZ8'});for(let depth=0;depth<3;depth++){input=JSON.stringify(input).slice(1,-1);const text='User message: '+input+' End.',s=new SecretSwapSession(),wire=s.substituteText(text);expect(wire).not.toContain('CredentialTailZ8');expect(s.restoreText(wire)).toBe(text);}});

for(const credential of ['password="q7 CredentialTailZ8"',JSON.stringify({password:'q7"CredentialTailZ8'}),JSON.stringify({password:'q7\nCredentialTailZ8'}),'https://user:q7@CredentialTailZ8@example.invalid/path'])test(`incoming storage and model compose safely: ${credential}`,()=>{const contact='alpha.redaction.probe@example.invalid',input='Contact '+contact+'. Unrelated credential: '+credential,stored=scrubIncomingMessageTextForStorage(input);expect(stored).not.toContain('CredentialTailZ8');expect(stored).toContain(contact);expect(stored).not.toContain('__ELIZA_');expect(scrubIncomingMessageTextForStorage(stored)).toBe(stored);const session=new SecretSwapSession(),wire=session.substituteText(JSON.stringify({text:stored}));expect(wire).not.toContain('CredentialTailZ8');expect(wire).not.toContain(contact);});
test('storage preserves JSON container syntax beside credential labels',()=>{expect(scrubIncomingMessageTextForStorage('Credential: '+JSON.stringify({password:'q7"CredentialTailZ8'}))).toBe('Credential: {"password":"***"}');expect(scrubIncomingMessageTextForStorage('Credential: '+JSON.stringify([{password:'q7"CredentialTailZ8'}]))).toBe('Credential: [{"password":"***"}]');});
test('a quoted brace password is protected without consuming container braces',()=>{expect(scrubIncomingMessageTextForStorage(JSON.stringify({password:'{',public:'ordinary'}))).toBe('{"password":"***","public":"ordinary"}');});
