/** Typed source facade; the shared build bundles the pure implementations for browser consumers. */
export {
  BGE_SMALL_VECTOR_SPACE,
  type ConnectorIdentityMetadataMapping,
  type ConnectorSourceDefinition,
  type ConnectorSourceKind,
  type ConnectorSourceMetadata,
  DEFAULT_NOTIFICATION_CATEGORY,
  DEFAULT_NOTIFICATION_PRIORITY,
  ElizaError,
  expandConnectorSourceFilter,
  formatError,
  getConnectorIdentityMetadataMapping,
  getConnectorSourceAliases,
  getConnectorSourceMetadata,
  getConnectorWorldIdMetadataKeys,
  getRecentMessagesData,
  identifyEmbeddingVector,
  isConnectorConfigured,
  isElizaError,
  isInferenceTraceId,
  isPassiveConnectorSource,
  isTruthyEnvValue,
  isWechatConfigured,
  MESSAGE_SOURCE_AGENT_GREETING,
  MESSAGE_SOURCE_CLIENT_CHAT,
  MESSAGE_SOURCE_CODING_AGENT,
  normalizeConnectorSource,
  normalizeEffectReceipts,
  ROLE_RANK,
  registerConnectorSourceAliases,
  registerConnectorSourceDefinitions,
  registerConnectorSourceMetadata,
  replaceIndexedNameTokens,
  replaceNameTokens,
  resolveEnvAlias,
  roleRank,
  satisfiesRoleGate,
  stripUnclaimedInteractionMarkup,
  tailWellFormed,
  tierForPriority,
  toWellFormedUnicode,
  truncateWellFormed,
  unregisterConnectorSourceMetadataOwner,
} from "@elizaos/core";
export {
  IMMERSIVE_WALLPAPER_SURFACE,
  resolveSurfaceBackgroundPolicy,
  resolveSurfaceManifest,
  surfaceGrants,
} from "./views/surface-manifest.js";
export { toSwarmActivity } from "./views/swarm-activity.js";
export {
  dedupeModalities,
  isViewKindEnabled,
  isViewVisible,
  resolveViewKind,
} from "./views/view-kind.js";
