export const GECKO_TERMINAL_API_BASE = "https://api.geckoterminal.com/api/v2";
export const GECKO_TERMINAL_NETWORK = "bsc";

export const DEFAULT_DISCOVERY_INTERVAL_MS = 15 * 60 * 1000;
export const DEFAULT_NEW_POOLS_LIMIT = 20;
export const DEFAULT_TRENDING_POOLS_LIMIT = 10;
export const DEFAULT_MAX_CANDIDATES = 12;
export const DEFAULT_MEMO_TOP_COUNT = 3;
export const DEFAULT_REPORTS_DIR = ".elizaok/reports";
export const DEFAULT_RUN_ON_STARTUP = true;
export const DEFAULT_DASHBOARD_ENABLED = true;
export const DEFAULT_DASHBOARD_PORT = 4048;
export const DEFAULT_GOO_LOOKBACK_BLOCKS = 25_000;
export const DEFAULT_GOO_MAX_AGENTS = 20;
export const DEFAULT_GOO_MEMO_TOP_COUNT = 3;
export const DEFAULT_HISTORY_LIMIT = 24;
export const DEFAULT_TREASURY_PAPER_CAPITAL_USD = 10_000;
export const DEFAULT_TREASURY_MAX_ACTIVE_POSITIONS = 5;
export const DEFAULT_TREASURY_RESERVE_PCT = 35;
export const DEFAULT_TREASURY_TAKE_PROFIT_RULES =
  "30:20,60:25,100:30,200:35,400:40";
export const DEFAULT_TREASURY_STOP_LOSS_PCT = -18;
export const DEFAULT_TREASURY_EXIT_SCORE_THRESHOLD = 48;
export const DEFAULT_TREASURY_TRAILING_STOP_PCT = 15;
export const DEFAULT_TREASURY_TRAILING_STOP_ACTIVATE_PCT = 25;
export const DEFAULT_EXECUTION_MODE = "paper";
export const DEFAULT_EXECUTION_ROUTER = "fourmeme";
export const DEFAULT_EXECUTION_ENABLED = false;
export const DEFAULT_EXECUTION_DRY_RUN = true;
export const DEFAULT_EXECUTION_LIVE_CONFIRM_PHRASE =
  "I_UNDERSTAND_ELIZAOK_LIVE";
export const DEFAULT_EXECUTION_MAX_BUY_BNB = 0.02;
export const DEFAULT_EXECUTION_MAX_DAILY_DEPLOY_BNB = 0.04;
export const DEFAULT_EXECUTION_MAX_SLIPPAGE_BPS = 500;
export const DEFAULT_EXECUTION_MAX_ACTIVE_POSITIONS = 3;
export const DEFAULT_EXECUTION_MAX_BUYS_PER_CYCLE = 1;
export const DEFAULT_EXECUTION_DRY_RUN_COOLDOWN_MS = 60 * 60 * 1000;
export const DEFAULT_EXECUTION_MIN_ENTRY_MCAP_USD = 10_000;
export const DEFAULT_EXECUTION_MAX_ENTRY_MCAP_USD = 100_000;
export const DEFAULT_EXECUTION_MIN_LIQUIDITY_USD = 15_000;
export const DEFAULT_EXECUTION_MIN_VOLUME_M5_USD = 2_000;
export const DEFAULT_EXECUTION_MIN_VOLUME_H1_USD = 6_000;
export const DEFAULT_EXECUTION_MIN_BUYERS_M5 = 8;
export const DEFAULT_EXECUTION_MIN_NET_BUYS_M5 = 3;
export const DEFAULT_EXECUTION_MIN_POOL_AGE_MINUTES = 2;
export const DEFAULT_EXECUTION_MAX_POOL_AGE_MINUTES = 180;
export const DEFAULT_EXECUTION_MAX_PRICE_CHANGE_H1_PCT = 180;
export const DEFAULT_EXECUTION_ALLOWED_QUOTE_ONLY = true;
export const DEFAULT_EXECUTION_KOL_ENABLED = false;
export const DEFAULT_EXECUTION_KOL_MIN_HOLDER_COUNT = 10;
export const DEFAULT_EXECUTION_KOL_PUBLIC_SOURCE_ENABLED = true;
export const DEFAULT_EXECUTION_KOL_PUBLIC_TOKEN_LIMIT = 12;
export const DEFAULT_EXECUTION_KOL_PUBLIC_LOOKBACK_BLOCKS = 1_500;
export const DEFAULT_EXECUTION_KOL_PUBLIC_MIN_TOKEN_HITS = 2;
export const DEFAULT_EXECUTION_KOL_PUBLIC_WALLET_LIMIT = 50;
export const DEFAULT_EXECUTION_KOL_PUBLIC_CACHE_PATH =
  ".elizaok/reports/public-kol-wallets.json";
export const WBNB_ADDRESS = "0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c";
export const DEFAULT_DISTRIBUTION_ENABLED = false;
export const DEFAULT_DISTRIBUTION_SNAPSHOT_PATH =
  ".elizaok/holder-snapshot.json";
export const DEFAULT_DISTRIBUTION_MIN_ELIGIBLE_BALANCE = 1000;
export const DEFAULT_DISTRIBUTION_MAX_RECIPIENTS = 50;
export const DEFAULT_DISTRIBUTION_POOL_PCT = 65;
export const DEFAULT_DISTRIBUTION_START_BLOCK = 0;
export const DEFAULT_DISTRIBUTION_EXECUTION_ENABLED = false;
export const DEFAULT_DISTRIBUTION_EXECUTION_DRY_RUN = true;
export const DEFAULT_DISTRIBUTION_EXECUTION_AUTO_SELECT_ASSET = true;
export const DEFAULT_DISTRIBUTION_EXECUTION_LIVE_CONFIRM =
  "I_UNDERSTAND_ELIZAOK_AIRDROP_LIVE";
export const DEFAULT_DISTRIBUTION_EXECUTION_MAX_RECIPIENTS_PER_RUN = 20;
export const DEFAULT_DISTRIBUTION_REQUIRE_VERIFIED_WALLET = true;
export const DEFAULT_DISTRIBUTION_REQUIRE_POSITIVE_PNL = true;
export const DEFAULT_DISTRIBUTION_REQUIRE_TAKE_PROFIT_HIT = false;
export const DEFAULT_DISTRIBUTION_MIN_WALLET_QUOTE_USD = 10;
export const DEFAULT_DISTRIBUTION_MIN_PORTFOLIO_SHARE_PCT = 5;

export const TARGET_EARLY_MCAP_USD = 50_000;
export const DEFAULT_QUOTE_TOKEN_ADDRESSES = new Set([
  "0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c",
  "0x0000000000000000000000000000000000000000",
]);

export const ELIZAOK_SCAN_RUNS_TABLE = "elizaok_scan_runs";
export const ELIZAOK_CANDIDATE_TABLE = "elizaok_candidate_snapshots";
export const ELIZAOK_MEMO_TABLE = "elizaok_scan_memos";
export const ELIZAOK_GOO_TABLE = "elizaok_goo_candidates";
