/* polarquant.h - Public API for the on-device PolarQuant Q4 quant block.
 *
 * Reference C scalar implementation of:
 *
 *   block_q4_polar  -- the GGML quant block layout (see polar_block.h).
 *   quantize_row_q4_polar_ref     - encoder (per-block L2 + WHT + Lloyd-Max).
 *   dequantize_row_q4_polar_ref   - decoder (centroid LUT + inverse WHT).
 *   ggml_vec_dot_q4_polar_q8_0_ref - matmul kernel (mirrors q4_K x q8_K).
 *
 * The block format is locked here -- see polar_block.h for the layout.
 * Centroids live in polar_centroids.h and are committed to the tree
 * (regenerated bit-for-bit by scripts/gen_centroids.py).
 *
 * This is the scalar reference; NEON / AVX2 / Metal kernels are
 * separate files added in a follow-up.  See README.md for the
 * integration path into Apothic-AI/llama.cpp-1bit-turboquant.
 */

#ifndef POLARQUANT_POLARQUANT_H
#define POLARQUANT_POLARQUANT_H

#include <stdint.h>

#include "polarquant/polar_centroids.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Number of weights per block.  Locked to 128: the Walsh-Hadamard
 * rotation is a fixed in-place butterfly for size 128, the centroids
 * are precomputed for that block size, and the block size matches
 * what polar_quantize() in polar_quant.py produces by default.
 */
#define QK_POLAR 128

/* Optional 1-bit QJL residual sign per block.  16 bytes when on. */
#define QJL_RESIDUAL_BYTES (QK_POLAR / 8)

/* Magnitude of the QJL residual correction along the random projection
 * direction.  Must match polar_quant._QJL_CORRECTION_MAGNITUDE.
 */
#define POLAR_QJL_CORRECTION_MAGNITUDE 0.5f

/* Deterministic seed for the per-block random sign vector used by the
 * QJL correction.  Must match polar_quant._QJL_SEED.  The sign vector
 * itself is generated by polar_qjl_signs() (see below).
 */
#define POLAR_QJL_SEED 42

/* Half-precision scalar.  We mirror llama.cpp's typedef: a 16-bit
 * unsigned integer holding an IEEE-754 binary16 bit pattern.  See
 * polar_block.h::polar_fp16_to_fp32 for the conversion the reference
 * kernels use.
 */
typedef uint16_t polar_fp16_t;

#include "polarquant/polar_block.h"  /* defines block_q4_polar */

/* ----- in-place fp32 Walsh-Hadamard transform of size QK_POLAR ----- */

/* Iterative Cooley-Tukey-style butterfly. Self-inverse up to scaling
 * by 1/sqrt(QK_POLAR), which we fold into the per-block norm scale.
 */
void polar_hadamard_inplace(float * x);

/* ----- reference encoder / decoder / dot-product ----- */

/* Encode k floats (k must be a positive multiple of QK_POLAR) into
 * (k / QK_POLAR) consecutive block_q4_polar entries at y.
 *
 * use_qjl: when non-zero, populates the qjl[] residual bits and the
 * decoder applies the +/- correction in dequantize_row_q4_polar_ref.
 */
void quantize_row_q4_polar_ref(
    const float * x,
    block_q4_polar * y,
    int64_t k,
    int use_qjl);

/* Decode k floats from (k / QK_POLAR) consecutive block_q4_polar
 * entries at x into the destination y[0..k-1].
 *
 * use_qjl: when non-zero, applies the QJL residual correction.  Must
 * match the value used at encode time; the qjl[] payload is otherwise
 * ignored (and may be uninitialized).
 */
void dequantize_row_q4_polar_ref(
    const block_q4_polar * x,
    float * y,
    int64_t k,
    int use_qjl);

/* Reference dot product against a row of block_q8_0 (the standard
 * llama.cpp activation block: int8 codes + per-block fp32 scale, 32
 * elements per block).
 *
 * n  : number of weights consumed (must be a positive multiple of
 *      QK_POLAR and a positive multiple of 32 -- in practice both,
 *      since QK_POLAR=128 covers that constraint).
 * s  : scalar output, *s = <x, y> in fp32.
 * x  : (n / QK_POLAR) PolarQuant blocks.
 * y  : (n / 32) Q8_0 blocks.
 *
 * Structural template: ggml_vec_dot_q4_K_q8_K from llama.cpp.
 * use_qjl flag matches the encoder.
 */
void ggml_vec_dot_q4_polar_q8_0_ref(
    int n,
    float * s,
    const block_q4_polar * x,
    const struct block_q8_0 * y,
    int use_qjl);

/* Generate the per-block random +/-1 sign vector used by the QJL
 * correction.  Encoder and decoder must agree byte-for-byte; we use a
 * simple xorshift32 PRNG seeded with POLAR_QJL_SEED so the output is
 * platform-independent (NumPy's default_rng is not portable across
 * versions, so we deliberately do not depend on it here).
 *
 * The Python reference uses torch.randint with a Generator seeded at
 * 42.  We reproduce *the same* +/-1 sequence by reseeding our own
 * xorshift32 and reading 128 bits.  See polar_block.h for the impl.
 */
void polar_qjl_signs(float * out);

#ifdef __cplusplus
}
#endif

#endif /* POLARQUANT_POLARQUANT_H */
