global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'auton8n-monitor'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them
rule_files:
  - "alerts/*.yml"

# Scrape configurations
scrape_configs:
  # Scrape AutoN8n metrics
  - job_name: 'auton8n'
    static_configs:
      - targets: ['auton8n:9090']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape Node Exporter if available
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # Scrape Redis Exporter if available
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121'] 