import {
  checkOrderScoringTemplate,
  getAccountAccessStatusTemplate,
  getActiveOrdersTemplate,
  getBestPriceTemplate,
  getMarketTemplate,
  getMidpointPriceTemplate,
  getOrderBookDepthTemplate,
  getOrderBookTemplate,
  getOrderDetailsTemplate,
  getPriceHistoryTemplate,
  getSamplingMarketsTemplate,
  getSimplifiedMarketsTemplate,
  getSpreadTemplate,
  getTradeHistoryTemplate,
  orderTemplate,
  retrieveAllMarketsTemplate,
  setupWebsocketTemplate,
} from "./generated/prompts/typescript/prompts.js";

export {
  retrieveAllMarketsTemplate,
  getSimplifiedMarketsTemplate,
  getSamplingMarketsTemplate,
  getMarketTemplate,
  orderTemplate,
  getOrderBookTemplate,
  getOrderBookDepthTemplate,
  getBestPriceTemplate,
  getMidpointPriceTemplate,
  getSpreadTemplate,
  getOrderDetailsTemplate,
  getPriceHistoryTemplate,
  checkOrderScoringTemplate,
  getActiveOrdersTemplate,
  getTradeHistoryTemplate,
  getAccountAccessStatusTemplate,
  setupWebsocketTemplate,
};
