services:
  docs:
    build:
      context: ../../..
      dockerfile: docker/targets/docs/Dockerfile
    image: elizaos:docs
    container_name: elizaos-docs
    ports:
      - "3000:3000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3