export {
  checkOrderScoringTemplate,
  getAccountAccessStatusTemplate,
  getActiveOrdersTemplate,
  getBestPriceTemplate,
  getMarketTemplate,
  getMidpointPriceTemplate,
  getOrderBookDepthTemplate,
  getOrderBookTemplate,
  getOrderDetailsTemplate,
  getPriceHistoryTemplate,
  getSamplingMarketsTemplate,
  getSimplifiedMarketsTemplate,
  getSpreadTemplate,
  getTradeHistoryTemplate,
  orderTemplate,
  retrieveAllMarketsTemplate,
  setupWebsocketTemplate,
} from "../generated/prompts/typescript/prompts.js";
