# Re-export from centralized prompts
from elizaos.prompts import (
    INITIAL_SUMMARIZATION_TEMPLATE,
    LONG_TERM_EXTRACTION_TEMPLATE,
    UPDATE_SUMMARIZATION_TEMPLATE,
)

__all__ = [
    "INITIAL_SUMMARIZATION_TEMPLATE",
    "UPDATE_SUMMARIZATION_TEMPLATE",
    "LONG_TERM_EXTRACTION_TEMPLATE",
]
