#!/usr/bin/env python3
"""rot-integration-check gate (W1).

Fail-closed gate for the E1 root-of-trust integration top
(rtl/security/rot/e1_rot_top.sv) per docs/security/tee-plan/02-root-of-trust.md
S8. Writes build/reports/rot_integration.json in the eliza.gate_status.v1 shape.

PASS requires ALL of:
  (a) the OpenTitan pin manifest resolves: the checkout is present and its HEAD
      matches external/opentitan/pin-manifest.json (Apache-2.0, Earl Grey tag);
  (b) e1_rot_top elaborates clean under Verilator -- the spine-only build, the
      Ibex-instantiated build, and the integrated build with every real
      OpenTitan crypto block (e1_rot_ot_<block> harness) instantiated;
  (c) the cocotb reset-release + mailbox tests pass.

It reports the real-vs-shim block inventory and FAILS CLOSED (status BLOCKED)
for every crypto/security block that is shimmed rather than truly elaborated,
naming the missing dependency. This is the project's fail-closed law (CLAUDE.md
/ AGENTS.md): a shimmed crypto block must not be reported as integrated. Each
crypto block is reported REAL only when its harness elaborates clean per-run
from a filelist generated by scripts/gen_ot_flist.py. Even with all 9 blocks
real, the gate stays BLOCKED on the crossbar/sideband data path being unwired
(the block TL ports are tied idle): no functional crypto / secure-boot result
is produced, so no such claim is permitted.

If Verilator or cocotb is unavailable, or the OpenTitan checkout is absent, the
gate reports BLOCKED with the missing dependency and exits non-zero.
"""

from __future__ import annotations

import datetime as _dt
import json
import shutil
import subprocess
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REPORT = ROOT / "build/reports/rot_integration.json"
OT_MANIFEST = ROOT / "external/opentitan/pin-manifest.json"
OT_CHECKOUT = ROOT / "external/opentitan/opentitan"
IBEX_FLIST = ROOT / "verify/cocotb/integration/ibex_pmc_min.f"
COCOTB_RESULTS = ROOT / "verify/cocotb/rot/results.xml"
GEN_FLIST = ROOT / "scripts/gen_ot_flist.py"
OT_BLOCKS_RTL = ROOT / "rtl/security/rot/e1_rot_ot_blocks.sv"
FLIST_DIR = ROOT / "build/rot_ot/flists"

# Upstream OpenTitan Verilator lint waivers. These are the warning classes
# OpenTitan itself waives in each block's hw/ip/<blk>/lint/<blk>.vlt; applying
# them lets the vendored RTL elaborate clean without modifying the read-only
# upstream tree. They are diagnostics-only (no functional masking).
OT_WAIVERS = [
    "-Wall",
    "-Wno-WIDTHEXPAND",
    "-Wno-WIDTHTRUNC",
    "-Wno-UNUSEDPARAM",
    "-Wno-UNUSEDSIGNAL",
    "-Wno-UNUSEDGENVAR",
    "-Wno-UNOPTFLAT",
    "-Wno-CASEINCOMPLETE",
    "-Wno-LATCH",
    "-Wno-PINMISSING",
    "-Wno-PINCONNECTEMPTY",
    "-Wno-DECLFILENAME",
    "-Wno-ASCRANGE",
    "-Wno-MULTIDRIVEN",
    "-Wno-CMPCONST",
    "-Wno-SYNCASYNCNET",
    "-Wno-TIMESCALEMOD",
    "-Wno-CONSTRAINTIGN",
    "-Wno-ALWCOMBORDER",
    "-Wno-SYMRSVDWORD",
]

# OpenTitan crypto/security blocks integrated for real. Each maps the inventory
# name to its FuseSoC VLNV (for gen_ot_flist.py), the e1_rot_ot_<harness> module
# that wraps the vendored IP, and the E1_ROT_INSTANTIATE_<DEFINE> that gates it
# into e1_rot_top. A block is reported REAL only if its harness elaborates clean
# under Verilator with the generated filelist (proven per-run, not asserted).
CRYPTO_BLOCKS = [
    {
        "name": "rom_ctrl",
        "vlnv": "lowrisc:ip:rom_ctrl",
        "harness": "e1_rot_ot_rom_ctrl",
        "define": "E1_ROT_INSTANTIATE_ROM_CTRL",
    },
    {
        "name": "keymgr",
        "vlnv": "lowrisc:ip:keymgr",
        "harness": "e1_rot_ot_keymgr",
        "define": "E1_ROT_INSTANTIATE_KEYMGR",
    },
    {
        "name": "kmac",
        "vlnv": "lowrisc:ip:kmac",
        "harness": "e1_rot_ot_kmac",
        "define": "E1_ROT_INSTANTIATE_KMAC",
    },
    {
        "name": "hmac",
        "vlnv": "lowrisc:ip:hmac",
        "harness": "e1_rot_ot_hmac",
        "define": "E1_ROT_INSTANTIATE_HMAC",
    },
    {
        "name": "aes",
        "vlnv": "lowrisc:ip:aes",
        "harness": "e1_rot_ot_aes",
        "define": "E1_ROT_INSTANTIATE_AES",
    },
    {
        "name": "csrng",
        "vlnv": "lowrisc:ip:csrng",
        "harness": "e1_rot_ot_csrng",
        "define": "E1_ROT_INSTANTIATE_CSRNG",
    },
    {
        "name": "edn",
        "vlnv": "lowrisc:ip:edn",
        "harness": "e1_rot_ot_edn",
        "define": "E1_ROT_INSTANTIATE_EDN",
    },
    {
        "name": "entropy_src",
        "vlnv": "lowrisc:ip:entropy_src",
        "harness": "e1_rot_ot_entropy_src",
        "define": "E1_ROT_INSTANTIATE_ENTROPY_SRC",
    },
    {
        "name": "alert_handler",
        "vlnv": "lowrisc:ip:alert_handler",
        "harness": "e1_rot_ot_alert_handler",
        "define": "E1_ROT_INSTANTIATE_ALERT_HANDLER",
    },
]

# Spine RTL (no Ibex) -- this is the scope that elaborates clean stand-alone.
SPINE_SOURCES = [
    "rtl/security/rot/e1_rot_tlul_pkg.sv",
    "rtl/security/otp/e1_otp_map.sv",
    "rtl/security/rot/e1_rot_crypto_shim.sv",
    "rtl/security/rot/e1_rot_mailbox.sv",
    "rtl/security/rot/e1_rot_reset_seq.sv",
    "rtl/security/rot/e1_rot_top.sv",
]

# Missing dependency reported for any crypto block whose real RTL fails to
# elaborate in the gate's flow (i.e. would fall back to the fail-closed shim).
MISSING_OT_DEP = (
    "OpenTitan block RTL did not elaborate clean under Verilator from the "
    "generated filelist (scripts/gen_ot_flist.py); falls back to the "
    "fail-closed e1_rot_crypto_shim"
)

# Spine blocks that are real by construction (E1-owned RTL or FuseSoC-staged
# Ibex), proven by the spine/Ibex elaborate checks and the cocotb contracts.
SPINE_BLOCKS = [
    {
        "name": "ibex_rv32imc",
        "detail": "lowRISC ibex_top from the FuseSoC-staged tree "
        "(external/ibex/ibex/build, shared with the PMC lane); "
        "elaborated under E1_ROT_INSTANTIATE_IBEX.",
    },
    {
        "name": "rot_sram_maskrom",
        "detail": "E1 behavioral RoT instruction/data SRAM + mask-ROM region in e1_rot_top.sv.",
    },
    {
        "name": "e1_otp_map",
        "detail": "W4 OTP controller (rtl/security/otp/e1_otp_map.sv), "
        "instantiated for real with 2-of-3 majority + parity fault.",
    },
    {
        "name": "e1_rot_mailbox",
        "detail": "AP<->RoT TL-UL mailbox; round-trip + AP-isolation proven by cocotb.",
    },
    {
        "name": "e1_rot_reset_seq",
        "detail": "Cold-boot reset sequencer; fail-closed reset-release proven by cocotb.",
    },
    {
        "name": "e1_lc_ctrl",
        "detail": "W5 lifecycle binding: the OTP lifecycle one-hot drives the "
        "reset-release SCRAP gating directly; the W5 controller binds by "
        "name under E1_ROT_HAVE_LC_CTRL when present.",
    },
]

EXPECTED_COCOTB_TESTS = (
    "rot_released_first_cores_held",
    "cores_released_on_verified_boot",
    "cores_stay_in_reset_when_not_verified",
    "scrap_latches_halt_and_never_releases",
    "mailbox_request_response_roundtrip",
    "ap_cannot_write_response_bank",
)


def _verilator() -> str | None:
    v = shutil.which("verilator")
    if v:
        return v
    oss = ROOT / "external/oss-cad-suite/bin/verilator"
    return str(oss) if oss.is_file() else None


def _now() -> str:
    return _dt.datetime.now(_dt.UTC).isoformat()


def check_pin() -> dict:
    """Resolve the OpenTitan pin manifest: checkout present and HEAD == pin."""
    if not OT_MANIFEST.is_file():
        return {
            "id": "opentitan_pin",
            "status": "blocked",
            "detail": f"manifest missing: {OT_MANIFEST.relative_to(ROOT)}",
        }
    manifest = json.loads(OT_MANIFEST.read_text())
    if manifest.get("license") != "Apache-2.0":
        return {
            "id": "opentitan_pin",
            "status": "fail",
            "detail": "OpenTitan license must be Apache-2.0",
        }
    if not OT_CHECKOUT.is_dir():
        return {
            "id": "opentitan_pin",
            "status": "blocked",
            "detail": "external/opentitan/opentitan absent; run scripts/bootstrap_opentitan.sh",
        }
    try:
        head = subprocess.check_output(
            ["git", "-C", str(OT_CHECKOUT), "rev-parse", "HEAD"], text=True, stderr=subprocess.PIPE
        ).strip()
    except subprocess.CalledProcessError as exc:
        return {
            "id": "opentitan_pin",
            "status": "blocked",
            "detail": f"rev-parse failed: {exc.stderr.strip()}",
        }
    pin = manifest.get("upstream_commit_pinned", "")
    if head != pin:
        return {
            "id": "opentitan_pin",
            "status": "fail",
            "detail": f"HEAD={head[:12]} != pin={pin[:12]}",
        }
    for rel in manifest.get("minimum_required_files", []):
        if not (ROOT / rel).is_file():
            return {
                "id": "opentitan_pin",
                "status": "blocked",
                "detail": f"missing required file {rel}",
            }
    return {
        "id": "opentitan_pin",
        "status": "pass",
        "detail": f"HEAD={head[:12]} matches pin ({manifest['upstream_tag_pinned']})",
    }


def _lint(verilator: str, sources: list[str], extra: list[str]) -> tuple[bool, str]:
    cmd = [
        verilator,
        "--lint-only",
        "-Wall",
        "-Wno-DECLFILENAME",
        "-Wno-UNUSEDPARAM",
        *extra,
        *[str(ROOT / s) for s in sources],
        "--top-module",
        "e1_rot_top",
    ]
    proc = subprocess.run(cmd, capture_output=True, text=True, cwd=ROOT)
    warns = [ln for ln in proc.stderr.splitlines() if "%Warning" in ln or "%Error" in ln]
    return (proc.returncode == 0 and not warns), "\n".join(warns[:8])


def check_elaborate_spine(verilator: str) -> dict:
    ok, msg = _lint(verilator, SPINE_SOURCES, [])
    if ok:
        return {
            "id": "elaborate_spine",
            "status": "pass",
            "detail": "e1_rot_top spine (Ibex undefined) lints clean",
        }
    return {"id": "elaborate_spine", "status": "fail", "detail": f"spine lint failed: {msg}"}


def check_elaborate_ibex(verilator: str) -> dict:
    if not IBEX_FLIST.is_file():
        return {
            "id": "elaborate_ibex",
            "status": "blocked",
            "detail": f"{IBEX_FLIST.relative_to(ROOT)} missing; run scripts/bootstrap_ibex.sh",
        }
    incdirs, ibex_src = [], []
    for line in IBEX_FLIST.read_text().splitlines():
        line = line.strip()
        if line.startswith("+incdir+"):
            incdirs.append("+incdir+" + str(ROOT / line[len("+incdir+") :]))
        elif line and not line.startswith(("#", "+")):
            ibex_src.append(str(ROOT / line))
    missing = [p for p in ibex_src if not Path(p).is_file()]
    if missing:
        return {
            "id": "elaborate_ibex",
            "status": "blocked",
            "detail": f"{len(missing)} staged Ibex source(s) absent; run "
            "scripts/bootstrap_ibex.sh (e.g. {})".format(Path(missing[0]).name),
        }
    waivers = [
        "-Wno-PINMISSING",
        "-Wno-WIDTHTRUNC",
        "-Wno-WIDTHEXPAND",
        "-Wno-CASEINCOMPLETE",
        "-Wno-LATCH",
        "-Wno-ASCRANGE",
        "-Wno-MULTIDRIVEN",
        "-Wno-CMPCONST",
        "-Wno-UNUSEDGENVAR",
        "-Wno-CONSTRAINTIGN",
        "-Wno-UNUSEDSIGNAL",
        "-Wno-UNOPTFLAT",
        "-Wno-SYNCASYNCNET",
        "-Wno-PINCONNECTEMPTY",
        "-Wno-TIMESCALEMOD",
        "+define+E1_ROT_INSTANTIATE_IBEX",
        "+define+SYNTHESIS",
        *incdirs,
    ]
    cmd = [
        verilator,
        "--lint-only",
        "-Wno-fatal",
        "-Wall",
        *waivers,
        *ibex_src,
        *[str(ROOT / s) for s in SPINE_SOURCES],
        "--top-module",
        "e1_rot_top",
    ]
    proc = subprocess.run(cmd, capture_output=True, text=True, cwd=ROOT)
    bad = [ln for ln in proc.stderr.splitlines() if "%Error" in ln]
    if proc.returncode == 0 and not bad:
        return {
            "id": "elaborate_ibex",
            "status": "pass",
            "detail": f"e1_rot_top + real Ibex ({len(ibex_src)} src) "
            "elaborates clean (upstream lint waivers applied)",
        }
    return {
        "id": "elaborate_ibex",
        "status": "fail",
        "detail": "Ibex-build elaboration failed: " + "\n".join(bad[:6]),
    }


def _gen_block_flist(vlnv: str) -> tuple[Path | None, str]:
    """Generate a block's Verilator filelist via scripts/gen_ot_flist.py."""
    proc = subprocess.run(
        [sys.executable, str(GEN_FLIST), vlnv], capture_output=True, text=True, cwd=ROOT
    )
    name = vlnv.split(":")[2]
    flist = FLIST_DIR / f"{name}.f"
    if proc.returncode != 0 or not flist.is_file():
        return None, (proc.stderr.strip() or proc.stdout.strip())[:200]
    return flist, ""


def _lint_block(verilator: str, flist: Path, top: str, extra_src: list[str]) -> tuple[bool, str]:
    cmd = [
        verilator,
        "--lint-only",
        "-Wno-fatal",
        *OT_WAIVERS,
        "-sv",
        "-f",
        str(flist),
        *extra_src,
        "--top-module",
        top,
    ]
    proc = subprocess.run(cmd, capture_output=True, text=True, cwd=ROOT)
    diags = [ln for ln in proc.stderr.splitlines() if "%Error" in ln or "%Warning" in ln]
    return (proc.returncode == 0 and not diags), "\n".join(diags[:6])


def check_elaborate_crypto(verilator: str) -> tuple[list[dict], dict]:
    """Elaborate each OpenTitan crypto block's real RTL via its harness.

    Returns (per_block_status, integrated_top_check). A block is REAL iff its
    e1_rot_ot_<harness> wrapper (real vendored IP + sideband tie-offs, TL device
    port exposed) lints clean from the generated filelist. The integrated check
    additionally elaborates e1_rot_top with every passing block's
    E1_ROT_INSTANTIATE_<DEFINE> set.
    """
    if not OT_BLOCKS_RTL.is_file():
        miss = {
            "id": "elaborate_crypto_integrated",
            "status": "blocked",
            "detail": f"{OT_BLOCKS_RTL.relative_to(ROOT)} missing",
        }
        return (
            [{"name": b["name"], "real": False, "missing": MISSING_OT_DEP} for b in CRYPTO_BLOCKS],
            miss,
        )

    FLIST_DIR.mkdir(parents=True, exist_ok=True)
    per_block: list[dict] = []
    real_defines: list[str] = []
    for blk in CRYPTO_BLOCKS:
        flist, err = _gen_block_flist(blk["vlnv"])
        if flist is None:
            per_block.append(
                {
                    "name": blk["name"],
                    "real": False,
                    "missing": f"filelist generation failed: {err}",
                }
            )
            continue
        ok, msg = _lint_block(verilator, flist, blk["harness"], [str(OT_BLOCKS_RTL)])
        if ok:
            per_block.append(
                {
                    "name": blk["name"],
                    "real": True,
                    "detail": f"vendored OpenTitan {blk['name']} elaborates clean "
                    f"via {blk['harness']} (def {blk['define']}); "
                    "filelist scripts/gen_ot_flist.py "
                    f"{blk['vlnv']}",
                }
            )
            real_defines.append(blk["define"])
        else:
            per_block.append(
                {"name": blk["name"], "real": False, "missing": f"{MISSING_OT_DEP}: {msg}"}
            )

    # Integrated check: e1_rot_top with all real blocks instantiated, against the
    # union of every real block's filelist (deduped).
    integrated = _integrated_top_check(verilator, real_defines)
    return per_block, integrated


def _integrated_top_check(verilator: str, defines: list[str]) -> dict:
    if not defines:
        return {
            "id": "elaborate_crypto_integrated",
            "status": "fail",
            "detail": "no crypto block elaborated; e1_rot_top would be all-shim",
        }
    incdirs: list[str] = []
    srcs: list[str] = []
    for blk in CRYPTO_BLOCKS:
        if blk["define"] not in defines:
            continue
        flist = FLIST_DIR / f"{blk['name']}.f"
        for ln in flist.read_text().splitlines():
            ln = ln.strip()
            if not ln:
                continue
            (incdirs if ln.startswith("+incdir+") else srcs).append(ln)
    incdirs = list(dict.fromkeys(incdirs))
    srcs = list(dict.fromkeys(srcs))
    cmd = [
        verilator,
        "--lint-only",
        "-Wno-fatal",
        *OT_WAIVERS,
        *[f"+define+{d}" for d in defines],
        "-sv",
        *incdirs,
        *srcs,
        str(OT_BLOCKS_RTL),
        *[str(ROOT / s) for s in SPINE_SOURCES],
        "--top-module",
        "e1_rot_top",
    ]
    proc = subprocess.run(cmd, capture_output=True, text=True, cwd=ROOT)
    bad = [ln for ln in proc.stderr.splitlines() if "%Error" in ln]
    if proc.returncode == 0 and not bad:
        return {
            "id": "elaborate_crypto_integrated",
            "status": "pass",
            "detail": f"e1_rot_top + {len(defines)} real OpenTitan crypto "
            f"block(s) ({len(srcs)} OT src) elaborates clean "
            "(upstream waivers applied)",
        }
    return {
        "id": "elaborate_crypto_integrated",
        "status": "fail",
        "detail": "integrated e1_rot_top elaboration failed: " + "\n".join(bad[:6]),
    }


def check_cocotb() -> dict:
    rc = subprocess.run(
        ["make", "-C", str(ROOT / "verify/cocotb/rot")], capture_output=True, text=True, cwd=ROOT
    )
    if not COCOTB_RESULTS.is_file():
        return {
            "id": "cocotb_reset_release_mailbox",
            "status": "blocked",
            "detail": "no results.xml; cocotb/verilator unavailable. " + rc.stderr.splitlines()[-1]
            if rc.stderr
            else "",
        }
    tree = ET.parse(COCOTB_RESULTS)
    seen, failed = set(), []
    for tc in tree.iter("testcase"):
        name = tc.get("name", "")
        seen.add(name)
        if tc.find("failure") is not None or tc.find("error") is not None:
            failed.append(name)
    missing = [t for t in EXPECTED_COCOTB_TESTS if t not in seen]
    if failed or missing:
        return {
            "id": "cocotb_reset_release_mailbox",
            "status": "fail",
            "detail": f"failed={failed} missing={missing}",
        }
    return {
        "id": "cocotb_reset_release_mailbox",
        "status": "pass",
        "detail": f"{len(EXPECTED_COCOTB_TESTS)} reset-release + mailbox tests passed",
    }


# The remaining blocker after all crypto blocks elaborate as real RTL: their
# TL-UL device ports are tied idle, not yet wired to the Ibex register crossbar.
# No functional crypto / secure-boot data path exists until that adapter lands.
MISSING_DATAPATH = (
    "RoT crossbar adapter (e1_rot_tlul_pkg <-> tlul_pkg) routing Ibex MMIO "
    "accesses into the now-real OpenTitan block TL-UL device ports, plus the "
    "block sideband data path (EDN entropy stack, keymgr sideload, rom_ctrl "
    "image). The blocks elaborate as real RTL with idle-tied TL/sideband ports; "
    "no functional crypto or secure-boot result is produced yet."
)


def main() -> int:
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    checks = [check_pin()]

    verilator = _verilator()
    crypto_blocks: list[dict] = []
    if verilator is None:
        checks.append(
            {
                "id": "elaborate_spine",
                "status": "blocked",
                "detail": "verilator not found; install oss-cad-suite",
            }
        )
        checks.append(
            {"id": "elaborate_ibex", "status": "blocked", "detail": "verilator not found"}
        )
        checks.append(
            {
                "id": "elaborate_crypto_integrated",
                "status": "blocked",
                "detail": "verilator not found",
            }
        )
        crypto_blocks = [
            {"name": b["name"], "real": False, "missing": "verilator not found"}
            for b in CRYPTO_BLOCKS
        ]
    else:
        checks.append(check_elaborate_spine(verilator))
        checks.append(check_elaborate_ibex(verilator))
        crypto_blocks, integrated = check_elaborate_crypto(verilator)
        checks.append(integrated)
    checks.append(check_cocotb())

    real_blocks = [b["name"] for b in SPINE_BLOCKS]
    real_blocks += [b["name"] for b in crypto_blocks if b["real"]]
    shimmed = [
        {"block": b["name"], "missing_dependency": b["missing"]}
        for b in crypto_blocks
        if not b["real"]
    ]
    all_crypto_real = bool(crypto_blocks) and not shimmed

    # Gate verdict. Fail-closed law:
    #   * any FAIL check -> FAIL.
    #   * any BLOCKED check (missing tool/checkout) -> BLOCKED.
    #   * any shimmed crypto block -> BLOCKED (named missing elaboration dep).
    #   * all crypto blocks elaborate real, but TL/sideband data path not wired
    #     -> still BLOCKED on rot_crypto_datapath_unwired. The blocks are REAL
    #     RTL (15 real / 0 shim) but produce no functional crypto result yet;
    #     no secure-boot/key/attestation claim is permitted.
    has_fail = any(c["status"] == "fail" for c in checks)
    has_block = any(c["status"] == "blocked" for c in checks)

    if has_fail:
        status, blocker_id, blocker_reason = (
            "FAIL",
            "rot_check_failure",
            "; ".join(f"{c['id']}: {c['detail']}" for c in checks if c["status"] == "fail"),
        )
    elif has_block:
        status, blocker_id = "BLOCKED", "rot_dependency_missing"
        blocker_reason = "; ".join(
            f"{c['id']}: {c['detail']}" for c in checks if c["status"] == "blocked"
        )
    elif shimmed:
        status, blocker_id = "BLOCKED", "rot_crypto_blocks_shimmed"
        blocker_reason = (
            "Integration spine (Ibex + OTP + lifecycle + mailbox + reset "
            "sequencer) is REAL and elaborates/tests clean, but the following "
            "OpenTitan crypto/security blocks are fail-closed SHIMS, not "
            "integrated: "
            + ", ".join(s["block"] for s in shimmed)
            + ". Missing dependency: "
            + MISSING_OT_DEP
        )
    elif all_crypto_real:
        status, blocker_id = "BLOCKED", "rot_crypto_datapath_unwired"
        blocker_reason = (
            "All 9 OpenTitan crypto/security blocks now elaborate as REAL RTL "
            "in the RoT flow (no shims remain), but their TL-UL device ports "
            "are tied idle. Missing dependency: " + MISSING_DATAPATH
        )
    else:
        status, blocker_id, blocker_reason = "PASS", None, None

    boundary_crypto = (
        "All 9 OpenTitan crypto/security blocks (rom_ctrl/keymgr/kmac/hmac/aes/"
        "csrng/edn/entropy_src/alert_handler) elaborate as REAL vendored RTL "
        "in e1_rot_top via the e1_rot_ot_<block> harnesses, but with TL-UL and "
        "sideband ports tied idle: NO functional crypto or secure-boot result "
        "is produced. No secure-boot / hardware-key / attestation claim is "
        "permitted from this tree."
        if all_crypto_real
        else "The OpenTitan crypto/security blocks that remain shimmed are bound via "
        "fail-closed E1 integration shims, NOT integrated -- reported BLOCKED "
        "with the named missing dependency. No secure-boot / hardware-key / "
        "attestation claim is permitted from this tree."
    )

    report = {
        "schema": "eliza.gate_status.v1",
        "gate": "rot-integration-check",
        "status": status,
        "blocker_id": blocker_id,
        "blocker_reason": blocker_reason,
        "evidence_paths": [
            "rtl/security/rot/e1_rot_top.sv",
            "rtl/security/rot/e1_rot_ot_blocks.sv",
            "rtl/security/rot/e1_rot_mailbox.sv",
            "rtl/security/rot/e1_rot_reset_seq.sv",
            "rtl/security/rot/e1_rot_crypto_shim.sv",
            "rtl/security/rot/e1_rot_tlul_pkg.sv",
            "scripts/gen_ot_flist.py",
            "verify/cocotb/test_e1_rot_top.py",
            "verify/cocotb/rot/e1_rot_top_tb.sv",
            "external/opentitan/pin-manifest.json",
            "scripts/bootstrap_opentitan.sh",
        ],
        "as_of": _now(),
        "subsystem": "security",
        "claim_boundary": (
            "The RoT INTEGRATION SPINE is real: the Ibex RV32IMC RoT core, the "
            "W4 OTP controller, the W5 lifecycle binding, the AP<->RoT TL-UL "
            "mailbox, and the fail-closed reset sequencer elaborate clean under "
            "Verilator and the reset-release + mailbox contracts pass in cocotb. " + boundary_crypto
        ),
        "block_inventory": {
            "real": real_blocks,
            "shimmed": shimmed,
            "real_count": len(real_blocks),
            "shimmed_count": len(shimmed),
        },
        "summary": {
            "check_count": len(checks),
            "passing_check_count": sum(1 for c in checks if c["status"] == "pass"),
            "failures": [c["id"] for c in checks if c["status"] != "pass"],
        },
        "checks": checks,
    }
    REPORT.write_text(json.dumps(report, indent=2) + "\n")

    print(f"STATUS: {status} rot-integration-check -> {REPORT.relative_to(ROOT)}")
    for c in checks:
        print(f"  [{c['status'].upper():7}] {c['id']}: {c['detail']}")
    print(f"  real blocks   ({len(real_blocks)}): {', '.join(real_blocks)}")
    print(f"  shimmed blocks({len(shimmed)}): {', '.join(s['block'] for s in shimmed)}")
    if blocker_reason:
        print(f"  blocker: {blocker_reason}")

    # Exit code: PASS -> 0; BLOCKED -> 2 (fail-closed, non-zero); FAIL -> 1.
    return {"PASS": 0, "BLOCKED": 2, "FAIL": 1}[status]


if __name__ == "__main__":
    sys.exit(main())
