/**
 * Defines the immutable job and checkpoint contracts for validating a canary
 * restore on an isolated, never-routed runtime. Every identity is generated by
 * the control plane and replayed exactly across worker crashes.
 */

import { ValidationError } from "../api/cloud-worker-errors";
import { assertSha256Digest, assertUuid } from "./admin-canary-image";

const SHA256_HEX_PATTERN = /^[0-9a-f]{64}$/;
const NON_EMPTY_MAX_256 = /^[^\u0000-\u001f\u007f]{1,256}$/;

export interface AdminCanaryRestoreValidationJobData {
  restoreValidationId: string;
  backupId: string;
  captureNonce: string;
  sourceJobId: string;
  rolloutId: string;
  standbyGeneration: string;
  actorUserId: string;
  agentId: string;
  organizationId: string;
  targetOwnerUserId: string;
  sourceEnvironmentRevision: number;
  sourceImageDigest: string;
  sourceSandboxId: string;
  targetImage: string;
  targetDigest: string;
  primaryNodeId: string;
  rollbackStandbyNodeId: string;
  plannedAt: string;
}

export interface AdminCanaryRestoreValidationCheckpoint {
  phase: "restore_committed";
  restoreValidationId: string;
  backupId: string;
  aggregateSha256: string;
  candidateProviderSandboxId: string;
  candidateReplacementAttemptId: string;
  candidateNodeId: string;
  candidateContainerName: string;
  candidateVolumePath: string;
  candidateVpnNodeId: string;
  receiptState: "committed";
  receiptSchemaVersion: 2;
  receiptTransfer: "chunked-v1";
  receiptFileCount: number;
  receiptTotalBytes: number;
  receiptRequiresRestart: true;
  receiptSuccess: true;
  receiptCommittedAt: string;
}

export interface AdminCanaryRestoreValidationJobResult {
  success: true;
  restoreValidationId: string;
  backupId: string;
  aggregateSha256: string;
  candidateProviderSandboxId: string;
  candidateReplacementAttemptId: string;
  receiptCommittedAt: string;
  candidateContainerAbsentAt: string;
  candidateVpnAbsentAt: string;
  candidateVolumeAbsentAt: string;
  candidateRetiredAt: string;
}

function assertSha256Hex(value: string, field: string): void {
  if (!SHA256_HEX_PATTERN.test(value)) {
    throw ValidationError(`${field} must be 64 lowercase hexadecimal characters`);
  }
}

function assertBoundedString(value: string, field: string): void {
  if (!NON_EMPTY_MAX_256.test(value)) {
    throw ValidationError(`${field} must be a non-empty bounded string`);
  }
}

function assertTimestamp(value: string, field: string): void {
  if (!Number.isFinite(Date.parse(value))) {
    throw ValidationError(`${field} must be an ISO timestamp`);
  }
}

export function assertAdminCanaryRestoreValidationJobData(
  data: AdminCanaryRestoreValidationJobData,
): void {
  for (const [field, value] of [
    ["restoreValidationId", data.restoreValidationId],
    ["backupId", data.backupId],
    ["sourceJobId", data.sourceJobId],
    ["rolloutId", data.rolloutId],
    ["standbyGeneration", data.standbyGeneration],
    ["actorUserId", data.actorUserId],
    ["agentId", data.agentId],
    ["organizationId", data.organizationId],
    ["targetOwnerUserId", data.targetOwnerUserId],
    ["sourceSandboxId", data.sourceSandboxId],
  ] as const) {
    assertUuid(value, field);
  }
  assertSha256Hex(data.captureNonce, "captureNonce");
  if (!Number.isSafeInteger(data.sourceEnvironmentRevision) || data.sourceEnvironmentRevision < 0) {
    throw ValidationError("sourceEnvironmentRevision must be a non-negative safe integer");
  }
  assertSha256Digest(data.sourceImageDigest, "sourceImageDigest");
  assertSha256Digest(data.targetDigest, "targetDigest");
  assertBoundedString(data.targetImage, "targetImage");
  assertBoundedString(data.primaryNodeId, "primaryNodeId");
  assertBoundedString(data.rollbackStandbyNodeId, "rollbackStandbyNodeId");
  if (data.primaryNodeId === data.rollbackStandbyNodeId) {
    throw ValidationError("restore validation requires distinct primary and standby nodes");
  }
  if (data.sourceImageDigest !== data.targetDigest) {
    throw ValidationError("sourceImageDigest must equal the running canary targetDigest");
  }
  assertTimestamp(data.plannedAt, "plannedAt");
}

export function isAdminCanaryRestoreValidationJobData(
  value: unknown,
): value is AdminCanaryRestoreValidationJobData {
  if (!value || typeof value !== "object" || Array.isArray(value)) return false;
  const data = value as Record<string, unknown>;
  const strings = [
    "restoreValidationId",
    "backupId",
    "captureNonce",
    "sourceJobId",
    "rolloutId",
    "standbyGeneration",
    "actorUserId",
    "agentId",
    "organizationId",
    "targetOwnerUserId",
    "sourceImageDigest",
    "sourceSandboxId",
    "targetImage",
    "targetDigest",
    "primaryNodeId",
    "rollbackStandbyNodeId",
    "plannedAt",
  ] as const;
  return (
    strings.every((field) => typeof data[field] === "string") &&
    typeof data.sourceEnvironmentRevision === "number"
  );
}

export function assertAdminCanaryRestoreValidationCheckpoint(
  checkpoint: AdminCanaryRestoreValidationCheckpoint,
): void {
  if (checkpoint.phase !== "restore_committed") {
    throw ValidationError("restore validation checkpoint phase is invalid");
  }
  assertUuid(checkpoint.restoreValidationId, "restoreValidationId");
  assertUuid(checkpoint.backupId, "backupId");
  assertUuid(checkpoint.candidateReplacementAttemptId, "candidateReplacementAttemptId");
  assertSha256Hex(checkpoint.aggregateSha256, "aggregateSha256");
  for (const [field, value] of [
    ["candidateProviderSandboxId", checkpoint.candidateProviderSandboxId],
    ["candidateNodeId", checkpoint.candidateNodeId],
    ["candidateContainerName", checkpoint.candidateContainerName],
    ["candidateVolumePath", checkpoint.candidateVolumePath],
    ["candidateVpnNodeId", checkpoint.candidateVpnNodeId],
  ] as const) {
    assertBoundedString(value, field);
  }
  if (
    checkpoint.receiptState !== "committed" ||
    checkpoint.receiptSchemaVersion !== 2 ||
    checkpoint.receiptTransfer !== "chunked-v1" ||
    !Number.isSafeInteger(checkpoint.receiptFileCount) ||
    checkpoint.receiptFileCount < 0 ||
    !Number.isSafeInteger(checkpoint.receiptTotalBytes) ||
    checkpoint.receiptTotalBytes < 0 ||
    checkpoint.receiptRequiresRestart !== true ||
    checkpoint.receiptSuccess !== true
  ) {
    throw ValidationError("restore validation checkpoint receipt is invalid");
  }
  assertTimestamp(checkpoint.receiptCommittedAt, "receiptCommittedAt");
}

export function isAdminCanaryRestoreValidationCheckpoint(
  value: unknown,
): value is AdminCanaryRestoreValidationCheckpoint {
  if (!value || typeof value !== "object" || Array.isArray(value)) return false;
  const checkpoint = value as Record<string, unknown>;
  return (
    checkpoint.phase === "restore_committed" &&
    typeof checkpoint.restoreValidationId === "string" &&
    typeof checkpoint.backupId === "string" &&
    typeof checkpoint.aggregateSha256 === "string" &&
    typeof checkpoint.candidateProviderSandboxId === "string" &&
    typeof checkpoint.candidateReplacementAttemptId === "string" &&
    typeof checkpoint.candidateNodeId === "string" &&
    typeof checkpoint.candidateContainerName === "string" &&
    typeof checkpoint.candidateVolumePath === "string" &&
    typeof checkpoint.candidateVpnNodeId === "string" &&
    checkpoint.receiptState === "committed" &&
    checkpoint.receiptSchemaVersion === 2 &&
    checkpoint.receiptTransfer === "chunked-v1" &&
    typeof checkpoint.receiptFileCount === "number" &&
    typeof checkpoint.receiptTotalBytes === "number" &&
    checkpoint.receiptRequiresRestart === true &&
    checkpoint.receiptSuccess === true &&
    typeof checkpoint.receiptCommittedAt === "string"
  );
}
