/**
 * Native-transcript contract (v1): the versioned, JSON-serializable projection
 * of a chat transcript that platform-native renderers (iOS SwiftUI, Android
 * Compose, desktop AppKit hosts) consume through the NativeTranscript bridge.
 *
 * The DOM renderer and every native renderer share ONE source of truth — the
 * message parser's segments (`parseSegments`) and the string-action protocol
 * (`sendActionMessage`) — so a native renderer never re-implements widget
 * *behavior*, only widget *drawing*. This module is the seam: it serializes
 * ShellMessage-shaped turns into `NativeTranscriptFrame` JSON, and native
 * decoders are conformance-tested against the committed golden fixture
 * (`__fixtures__/transcript-golden.json`, regenerated by the spec test).
 * Additive changes only within v1; anything breaking bumps `schema`.
 */
import type { ConversationSecretRequest } from "../../api/client-types-chat";
import type { NativeToolCallEvent } from "../../api/client-types-cloud";
import {
  parseSegments,
  type Segment,
} from "../../components/chat/message-parser-helpers";

export const NATIVE_TRANSCRIPT_SCHEMA = "eliza.native-transcript/v1";

/** JSON-safe segment union — `analysis-xml` is display-stripped, `ui-spec`
 *  carries the raw JSON (native re-validates), everything else mirrors the
 *  DOM parser's `Segment` 1:1 so the two renderers can never disagree. */
export type NativeSegment =
  | { kind: "text"; text: string }
  | { kind: "code"; code: string; lang?: string; inline: boolean }
  | { kind: "widget"; widgetKind: string; data: unknown }
  | { kind: "permission"; payload: unknown }
  | { kind: "ui-spec"; raw: string }
  | { kind: "config"; pluginId: string };

export interface NativeTranscriptMessage {
  id: string;
  role: "user" | "assistant";
  segments: NativeSegment[];
  /** Collapsed reasoning side-channel (ThinkingBlock parity). */
  reasoning?: string;
  /** Live tool-call rows (ToolCallEventLog parity). */
  toolEvents?: NativeToolCallEvent[];
  /** Failed-turn marker (retry affordance parity). */
  failureKind?: string;
  /** Pending secret/OAuth request (SensitiveRequestBlock parity). */
  secretRequest?: ConversationSecretRequest;
  /** True while this assistant turn is still streaming. */
  streaming?: boolean;
}

export interface NativeTranscriptFrame {
  schema: typeof NATIVE_TRANSCRIPT_SCHEMA;
  messages: NativeTranscriptMessage[];
  /** Rich turn status for the in-flight indicator (thinking/tool/…). */
  turnStatus?: { kind: string; label?: string } | null;
}

/** The minimal message shape the serializer needs — structurally satisfied by
 *  both ShellMessage (overlay) and ConversationMessage-derived rows. */
export interface TranscriptSourceMessage {
  id: string;
  role: "user" | "assistant";
  content: string;
  reasoning?: string;
  toolEvents?: NativeToolCallEvent[];
  failureKind?: string;
  secretRequest?: ConversationSecretRequest;
}

function toNativeSegment(segment: Segment): NativeSegment | null {
  switch (segment.kind) {
    case "text":
      return segment.text.trim().length > 0
        ? { kind: "text", text: segment.text }
        : null;
    case "code":
      return {
        kind: "code",
        code: segment.code,
        ...(segment.lang ? { lang: segment.lang } : {}),
        inline: segment.inline,
      };
    case "widget":
      return {
        kind: "widget",
        widgetKind: segment.widgetKind,
        data: segment.data,
      };
    case "permission":
      return { kind: "permission", payload: segment.payload };
    case "ui-spec":
      return { kind: "ui-spec", raw: segment.raw };
    case "config":
      return { kind: "config", pluginId: segment.pluginId };
    // Hidden reasoning/tool tags never reach a display surface.
    case "analysis-xml":
      return null;
    default:
      return null;
  }
}

/** Serialize one turn through the SAME parser the DOM renderer uses. */
export function serializeTranscriptMessage(
  message: TranscriptSourceMessage,
  options: { streaming?: boolean } = {},
): NativeTranscriptMessage {
  // User turns are raw text by contract (the DOM side renders them without
  // widget parsing too) — a user pasting `[CHOICE]` must see their literal
  // text, not an interactive widget.
  const segments: NativeSegment[] =
    message.role === "user"
      ? message.content.trim()
        ? [{ kind: "text", text: message.content }]
        : []
      : parseSegments(message.content, false)
          .map(toNativeSegment)
          .filter((s): s is NativeSegment => s !== null);
  return {
    id: message.id,
    role: message.role,
    segments,
    ...(message.reasoning?.trim() ? { reasoning: message.reasoning } : {}),
    ...(message.toolEvents?.length ? { toolEvents: message.toolEvents } : {}),
    ...(message.failureKind ? { failureKind: message.failureKind } : {}),
    ...(message.secretRequest ? { secretRequest: message.secretRequest } : {}),
    ...(options.streaming ? { streaming: true } : {}),
  };
}

export function serializeTranscript(
  messages: readonly TranscriptSourceMessage[],
  options: {
    turnStatus?: { kind: string; label?: string } | null;
    streamingMessageId?: string;
  } = {},
): NativeTranscriptFrame {
  return {
    schema: NATIVE_TRANSCRIPT_SCHEMA,
    messages: messages.map((m) =>
      serializeTranscriptMessage(m, {
        streaming: options.streamingMessageId === m.id,
      }),
    ),
    ...(options.turnStatus !== undefined
      ? { turnStatus: options.turnStatus }
      : {}),
  };
}

/**
 * The action-string protocol a native renderer emits back — identical to what
 * the DOM widgets pass to `sendActionMessage`, so the app-side handler cannot
 * tell which renderer produced it. Documented here as the single reference
 * for the Swift/Kotlin sides:
 *   - choice tap        → the option's value string (or `__first_run__:…`)
 *   - followup tap      → `reply:`-style payloads already encoded in data
 *   - form submit       → `[form:submit <formId>] {json}`
 *   - permission fallback → `__permission_card__:use_fallback feature=… permission=…`
 *   - permission granted  → `__permission_card__:granted feature=… permission=…`
 * Free-typed composer text goes through the same channel unchanged.
 */
export type NativeTranscriptAction = { message: string };
