/**
 * Chat callbacks — extracted from AppContext.
 *
 * Assembler hook: composes useChatLifecycle + useChatSend and owns the
 * greeting / conversation-management callbacks that depend on both.
 */
import { type MutableRefObject } from "react";
import type { CodingAgentSession, Conversation, OnboardingOptions } from "../api";
import { type AgentStatus, type ConversationMessage, type ImageAttachment } from "../api";
import { type Tab } from "../navigation";
import type { AppState, LifecycleAction, UiShellMode } from "./internal";
import { type LoadConversationMessagesResult } from "./internal";
import type { OnboardingMode, OnboardingStep } from "./types";
export interface UseChatCallbacksDeps {
    t: (key: string) => string;
    uiLanguage: string;
    uiShellMode: UiShellMode;
    tab: Tab;
    agentStatus: AgentStatus | null;
    chatInput: string;
    conversations: Conversation[];
    activeConversationId: string | null;
    companionMessageCutoffTs: number;
    conversationMessages: ConversationMessage[];
    ptySessions: CodingAgentSession[];
    setChatInput: (v: string) => void;
    setChatSending: (v: boolean) => void;
    setChatFirstTokenReceived: (v: boolean) => void;
    setChatLastUsage: (v: {
        promptTokens: number;
        completionTokens: number;
        totalTokens: number;
        model: string | undefined;
        updatedAt: number;
    }) => void;
    setChatPendingImages: (v: ImageAttachment[]) => void;
    setConversations: (v: Conversation[] | ((prev: Conversation[]) => Conversation[])) => void;
    setActiveConversationId: (v: string | null) => void;
    setCompanionMessageCutoffTs: (v: number) => void;
    setConversationMessages: (v: ConversationMessage[] | ((prev: ConversationMessage[]) => ConversationMessage[])) => void;
    setUnreadConversations: (v: Set<string> | ((prev: Set<string>) => Set<string>)) => void;
    resetConversationDraftState: () => void;
    activeConversationIdRef: MutableRefObject<string | null>;
    chatInputRef: MutableRefObject<string>;
    chatPendingImagesRef: MutableRefObject<ImageAttachment[]>;
    conversationsRef: MutableRefObject<Conversation[]>;
    conversationMessagesRef: MutableRefObject<ConversationMessage[]>;
    conversationHydrationEpochRef: MutableRefObject<number>;
    chatAbortRef: MutableRefObject<AbortController | null>;
    chatSendBusyRef: MutableRefObject<boolean>;
    chatSendNonceRef: MutableRefObject<number>;
    greetingFiredRef: MutableRefObject<boolean>;
    greetingInFlightConversationRef: MutableRefObject<string | null>;
    companionStaleConversationRefreshRef: MutableRefObject<string | null>;
    lifecycleAction: LifecycleAction | null;
    beginLifecycleAction: (action: LifecycleAction) => boolean;
    finishLifecycleAction: () => void;
    lifecycleBusyRef: MutableRefObject<boolean>;
    lifecycleActionRef: MutableRefObject<LifecycleAction | null>;
    setAgentStatus: (s: AgentStatus | null) => void;
    setActionNotice: (text: string, tone: "success" | "error" | "info", ttlMs?: number, once?: boolean, busy?: boolean) => void;
    pendingRestart: boolean;
    pendingRestartReasons: string[];
    setPendingRestart: (v: boolean) => void;
    setPendingRestartReasons: (v: string[] | ((prev: string[]) => string[])) => void;
    setBackendDisconnectedBannerDismissed: (v: boolean) => void;
    resetBackendConnection: () => void;
    loadConversations: () => Promise<Conversation[] | null>;
    loadConversationMessages: (convId: string) => Promise<LoadConversationMessagesResult>;
    loadPlugins: () => Promise<unknown>;
    elizaCloudEnabled: boolean;
    elizaCloudConnected: boolean;
    pollCloudCredits: () => Promise<boolean>;
    elizaCloudPreferDisconnectedUntilLoginRef: MutableRefObject<boolean>;
    setElizaCloudEnabled: (v: boolean) => void;
    setElizaCloudConnected: (v: boolean) => void;
    setElizaCloudVoiceProxyAvailable: (v: boolean) => void;
    setElizaCloudHasPersistedKey: (v: boolean) => void;
    setElizaCloudCredits: (v: number | null) => void;
    setElizaCloudCreditsLow: (v: boolean) => void;
    setElizaCloudCreditsCritical: (v: boolean) => void;
    setElizaCloudAuthRejected: (v: boolean) => void;
    setElizaCloudCreditsError: (v: string | null) => void;
    setElizaCloudTopUpUrl: (v: string) => void;
    setElizaCloudUserId: (v: string | null) => void;
    setElizaCloudStatusReason: (v: string | null) => void;
    setElizaCloudLoginError: (v: string | null) => void;
    onboardingCompletionCommittedRef: MutableRefObject<boolean>;
    setOnboardingUiRevealNonce: (fn: (n: number) => number) => void;
    setOnboardingLoading: (v: boolean) => void;
    setOnboardingComplete: (v: boolean) => void;
    setOnboardingStep: (v: OnboardingStep) => void;
    setOnboardingMode: (v: OnboardingMode) => void;
    setOnboardingActiveGuide: (v: string | null) => void;
    setOnboardingDeferredTasks: (v: string[]) => void;
    setPostOnboardingChecklistDismissed: (v: boolean) => void;
    setOnboardingName: (v: string) => void;
    setOnboardingStyle: (v: string) => void;
    setOnboardingServerTarget: (v: AppState["onboardingServerTarget"]) => void;
    setOnboardingProvider: (v: string) => void;
    setOnboardingApiKey: (v: string) => void;
    setOnboardingVoiceProvider: (v: string) => void;
    setOnboardingVoiceApiKey: (v: string) => void;
    setOnboardingPrimaryModel: (v: string) => void;
    setOnboardingOpenRouterModel: (v: string) => void;
    setOnboardingRemoteConnected: (v: boolean) => void;
    setOnboardingRemoteApiBase: (v: string) => void;
    setOnboardingRemoteToken: (v: string) => void;
    setOnboardingSmallModel: (v: string) => void;
    setOnboardingLargeModel: (v: string) => void;
    setOnboardingOptions: (v: OnboardingOptions | null) => void;
    setSelectedVrmIndex: (v: number) => void;
    setCustomVrmUrl: (v: string) => void;
    setCustomBackgroundUrl: (v: string) => void;
    setPlugins: (v: never[]) => void;
    setSkills: (v: never[]) => void;
    setLogs: (v: never[]) => void;
    coordinatorResetRef: MutableRefObject<(() => void) | null>;
}
export declare function useChatCallbacks(deps: UseChatCallbacksDeps): {
    chatSendQueueRef: import("react").RefObject<import("./useChatSend").QueuedChatSend[]>;
    interruptActiveChatPipeline: () => void;
    appendLocalCommandTurn: (userText: string, assistantText: string) => void;
    tryHandlePrefixedChatCommand: (rawText: string) => Promise<{
        handled: boolean;
        rewrittenText?: string;
    }>;
    sendChatText: (rawInput: string, options?: {
        channelType?: import("..").ConversationChannelType;
        conversationId?: string | null;
        images?: ImageAttachment[];
        metadata?: Record<string, unknown>;
    }) => Promise<void>;
    handleChatSend: (channelType?: import("..").ConversationChannelType, options?: {
        metadata?: Record<string, unknown>;
    }) => Promise<void>;
    sendActionMessage: (text: string) => Promise<void>;
    handleChatStop: () => void;
    handleChatRetry: (assistantMsgId: string) => void;
    handleChatEdit: (messageId: string, text: string) => Promise<boolean>;
    handleChatClear: () => Promise<void>;
    handleStartDraftConversation: () => Promise<void>;
    handleStart: () => Promise<void>;
    handleStop: () => Promise<void>;
    handleRestart: () => Promise<void>;
    triggerRestart: () => Promise<void>;
    retryBackendConnection: () => void;
    restartBackend: () => Promise<void>;
    relaunchDesktop: () => Promise<void>;
    showDesktopNotification: (options: {
        title: string;
        body?: string;
        urgency?: "normal" | "critical" | "low";
        silent?: boolean;
    }) => Promise<void>;
    notifyAssistantEvent: (event: import("..").StreamEventEnvelope) => void;
    notifyHeartbeatEvent: (event: import("..").StreamEventEnvelope) => void;
    completeResetLocalStateAfterServerWipe: (postResetAgentStatus: AgentStatus | null) => Promise<void>;
    handleResetAppliedFromMain: (payload: unknown) => Promise<void>;
    handleReset: () => Promise<void>;
    fetchGreeting: (convId: string) => Promise<boolean>;
    requestGreetingWhenRunning: (convId: string | null) => Promise<void>;
    hydrateInitialConversationState: () => Promise<string | null>;
    handleNewConversation: (title?: string) => Promise<void>;
    handleSelectConversation: (id: string) => Promise<void>;
    handleDeleteConversation: (id: string) => Promise<void>;
    handleRenameConversation: (id: string, title: string) => Promise<void>;
    suggestConversationTitle: (id: string) => Promise<string | null>;
};
//# sourceMappingURL=useChatCallbacks.d.ts.map