/**
 * Exercises the public-language boundary for deterministic Computer Use
 * routing without starting a driver or dispatching host input.
 */
import { describe, expect, it } from "vitest";
import {
  createComputerUseDirectRoutingRule,
  looksLikeExplicitComputerUseRequest,
} from "./direct-routing.js";

describe("Computer Use direct routing", () => {
  it.each([
    "can u use computer use to open telegram",
    "Use Computer-Use to take a screenshot",
    "please use my computer to open Finder",
    "use the computer and show me the desktop",
    "Hey, can you use computer use to open Telegram?",
    "I need you to use computer use to take a screenshot",
    "I want u to use my computer to open Finder",
    "please, use computer use to open Telegram",
    "I would like you to use computer use to open Telegram",
    "hey please can you use computer use to open Telegram",
    "use computer use to open Telegram, but do not close it",
    "use computer use to open Telegram, but don't type anything",
    "use computer use to open Telegram. Actually, do not close it",
    "use computer use to open Telegram. On second thought, do not close it",
    "use computer use to open Telegram, actually do not close it",
    "use computer use to open Telegram, but do not open Signal",
    "use computer use to click Telegram, but do not click Send",
    "use computer use to open Telegram, but do not open it full-screen",
    "use computer use and open Telegram. Actually, do not close it",
    "use the computer and show me the desktop. Actually, do not close Finder",
    "use computer use to click Stop",
    "use computer use to press stop",
    "use computer use to select Cancel",
    "use computer use to type never mind",
    "use computer use to type forget it",
    "use computer use to click Never Mind",
    "use computer use to select Forget It",
    "use computer use to click the Stop",
    "use computer use to click Emergency Stop",
    "use computer use to select the Cancel",
    "use computer use to type hello never mind",
    "use computer use to click the Never Mind",
    "use computer use to select blue Forget It",
  ])("recognizes an explicit host-control request: %s", (text) => {
    expect(looksLikeExplicitComputerUseRequest(text)).toBe(true);
  });

  it.each([
    "open telegram",
    "open telegram in the browser",
    "tell me what computer use means",
    "do not use the computer",
    "do not use computer use to open Telegram",
    "never ever use computer use to take a screenshot",
    "do not, under any circumstances, use computer use to open Telegram",
    "don’t use computer use to open Telegram",
    "use computer use to not open Telegram",
    "use computer use, but do not open Telegram",
    "use computer use? Actually, do not open Telegram",
    "use computer use. On second thought, cancel that request",
    "use computer use but do not open Telegram",
    "use computer use — but do not do that",
    "use computer use to open Telegram but do not actually do it",
    "use computer use; cancel that",
    "use computer use. cancel that",
    "use computer use, stop",
    "use computer use but cancel that",
    "use computer use to open Telegram but cancel that",
    "use computer use to open Telegram cancel that",
    "use computer use to open Telegram and then cancel that",
    "use computer use but actually do not do it",
    "use computer use to open Telegram but actually do not do it",
    "use computer use to open Telegram but do not use computer use",
    "use computer use to open Telegram but do not use the computer",
    "use computer use but don't",
    "use computer use to open Telegram actually don't do it",
    "use computer use to open Telegram and actually don't do it",
    "use computer use to open Telegram, don't",
    "use computer use to open Telegram never mind",
    "use computer use to open Telegram, never mind",
    "use computer use to open Telegram forget it",
    "use computer use to open Telegram. Actually, do not open it",
    "use computer use to click Telegram. On second thought, don't click that",
    "use computer use to open Telegram and don't",
    "use computer use to open Telegram and don't do it",
    "use computer use to open Telegram just don't",
    "use computer use to open Telegram don't do that",
    "use computer use to open Telegram actually cancel",
    "use computer use to open Telegram please cancel",
    "use computer use to open Telegram stop",
    "use computer use to open Telegram never-mind",
    "use computer use to open Telegram nevermind",
    "use computer use to open Telegram forget-it",
    "use computer use to open Telegram forget about it",
    "use computer use to open Telegram. Actually, do not open this",
    "use computer use to open Telegram. Actually, do not open it anymore",
    "use computer use to open Telegram. Actually, do not open that window",
    "use computer use to click Telegram. Actually, don't click it please",
    "use computer use to open Telegram, but do not open Telegram please",
    "use computer use to open Telegram and then don't open it",
    "use computer use to open Telegram don't open it",
    "use computer use and then open Telegram. Actually, don't open it",
    "use computer use and please open Telegram. Actually, don't open it",
    "use computer use to close both windows. Actually, don't close them",
    "use computer use to close those windows. Actually, don't close those",
    "use computer use to open Telegram. Actually, don't do so",
    "use computer use to open Telegram please, but do not open Telegram",
    "use computer use to open Telegram, but do not open the Telegram app",
    "use computer use to click Send, but do not click the Send button",
    "use computer use to open Telegram never—mind",
    "use computer use to open Telegram forget ’bout it",
    'please explain why "use computer use to take a screenshot" is unsafe',
    "please explain why `use computer use to open Telegram` is unsafe",
  ])("does not hijack an adjacent request: %s", (text) => {
    expect(looksLikeExplicitComputerUseRequest(text)).toBe(false);
  });

  it("owns the exact browser and automation fallbacks from the live failure", () => {
    expect(createComputerUseDirectRoutingRule()).toMatchObject({
      id: "computer-use.explicit-host-control",
      actionNames: ["COMPUTER_USE"],
      replacesActionNames: expect.arrayContaining([
        "BROWSER_NAVIGATE",
        "AUTOMATION_TRIGGER",
      ]),
      requiredActionTags: [
        "domain:computer-use",
        "capability:desktop-control",
        "effect:host-action",
      ],
      contexts: ["automation", "admin"],
      unavailable: {
        code: "COMPUTER_USE_UNAVAILABLE",
        reply: expect.stringContaining("restart the app session"),
      },
    });
  });
});
