{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gateway-discord.serviceAccountName" . }}
  namespace: {{ include "gateway-discord.namespace" . }}
  labels:
    {{- include "gateway-discord.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "gateway-discord.fullname" . }}-wake-servers
  labels:
    {{- include "gateway-discord.labels" . | nindent 4 }}
rules:
  - apiGroups: ["apps"]
    resources: ["deployments/scale"]
    verbs: ["patch"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "gateway-discord.fullname" . }}-wake-servers
  labels:
    {{- include "gateway-discord.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "gateway-discord.fullname" . }}-wake-servers
subjects:
  - kind: ServiceAccount
    name: {{ include "gateway-discord.serviceAccountName" . }}
    namespace: {{ include "gateway-discord.namespace" . }}
{{- end }}
