#!/usr/bin/env bun
// Orchestrator: runs every refactor phase in dependency order.
// Each phase is dry-run by default; pass --apply to actually mutate.

import { execFileSync } from "node:child_process";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { dirname } from "node:path";
import { gitCommit, makeLogger, parseFlags, preflight, REPO_ROOT } from "./lib/util.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));

const PHASES = [
  { id: "p0", file: "p0-break-cycles.mjs", title: "Break circular dependencies" },
  { id: "p1a", file: "p1-move-app-core-files.mjs", title: "Move app-core files to ui/shared" },
  { id: "p1b", file: "p1-rewrite-app-core-imports.mjs", title: "Rewrite consumer imports" },
  { id: "p1c", file: "p1-collapse-app-core-exports.mjs", title: "Collapse app-core subpath exports" },
  { id: "p2", file: "p2-standardize-plugin-builds.mjs", title: "Standardize plugin builds" },
  { id: "p3", file: "p3-flip-package-main.mjs", title: "Flip main/types/exports → dist" },
  { id: "p4", file: "p4-publish-pipeline.mjs", title: "Publish pipeline" },
  { id: "p5", file: "p5-tsconfig-paths.mjs", title: "tsconfig paths" },
  { id: "p6", file: "p6-turbo-json.mjs", title: "turbo.json" },
];

const COMMIT_MESSAGES = {
  p0: "refactor(p0): break agent ↔ plugin-elizacloud and app-core cycle",
  p1a: "refactor(p1a): move app-core React + types into @elizaos/ui and @elizaos/shared",
  p1b: "refactor(p1b): rewrite consumer imports of @elizaos/app-core/<subpath>",
  p1c: "refactor(p1c): collapse @elizaos/app-core to single barrel export",
  p2: "refactor(p2): emit .d.ts from all plugin builds",
  p3: "refactor(p3): point package.json main/types/exports at dist/",
  p4: "refactor(p4): publish pipeline reads dist/package.json",
  p5: "refactor(p5): rename workspace-paths to dist-paths and add dist-contract typecheck",
  p6: "refactor(p6): refresh turbo.json build graph",
};

async function main() {
  const flags = parseFlags();
  const log = makeLogger(flags);
  preflight("run-all", flags, log);

  if (!flags.apply) {
    log.note("Running ALL phases in dry-run mode. No files will change.");
    log.note("Re-run with --apply to mutate the worktree.");
    if (flags.commitPerPhase) {
      log.note("(--commit-per-phase requires --apply; ignored in dry-run.)");
    }
  } else if (flags.commitPerPhase) {
    log.note("Running ALL phases in APPLY mode with per-phase commits.");
  } else {
    log.note("Running ALL phases in APPLY mode as a single change set.");
    log.note("Pass --commit-per-phase to commit each phase separately.");
  }

  let failed = 0;
  for (const phase of PHASES) {
    log.section(`${phase.id.toUpperCase()}: ${phase.title}`);
    const ok = runPhase(phase, flags, log);
    if (!ok) {
      log.error(`${phase.id} failed; aborting.`);
      failed++;
      break;
    }
    if (flags.apply && flags.commitPerPhase) {
      gitCommit(
        `${COMMIT_MESSAGES[phase.id]}\n\nGenerated by scripts/refactor/${phase.file}\n\nCo-Authored-By: Claude Opus 4.7 (1M context) <noreply@anthropic.com>`,
        flags,
        log,
      );
    }
  }

  log.section("DONE");
  if (failed) {
    log.error(`Aborted with ${failed} failure(s).`);
    process.exit(1);
  }
  log.info("All phases completed.");
  if (!flags.apply) {
    log.note("This was a dry-run. Nothing changed.");
  } else {
    log.note("Now run: bun scripts/refactor/verify.mjs");
  }
}

function runPhase(phase, flags, log) {
  const script = join(HERE, phase.file);
  const args = [];
  if (flags.apply) args.push("--apply");
  if (flags.quiet) args.push("--quiet");
  if (flags.verbose) args.push("--verbose");
  if (!flags.color) args.push("--no-color");
  if (flags.force) args.push("--force");
  // Don't propagate --commit-per-phase; that's our concern, not the phase's.

  try {
    execFileSync("bun", [script, ...args], {
      cwd: REPO_ROOT,
      stdio: "inherit",
    });
    return true;
  } catch (err) {
    return false;
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
