name: Eliza CLI Tests

on:
  push:
    branches: [v2-develop]
    paths:
      - 'packages/cli/**'
  pull_request:
    branches: [v2-develop]
    paths:
      - 'packages/cli/**'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Setup Turbo Cache
        uses: actions/cache@v3
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Build all packages
        run: bun turbo run build --filter=!@elizaos/docs

      - name: Install Bats (bats-core)
        run: |
          sudo apt-get update
          sudo apt-get install -y bats

      - name: Run CLI tests
        working-directory: packages/cli/__test_scripts__
        run: |
          bash ./run_all_bats.sh
          echo "Exit code: $?"
