name: Eliza CLI Tests

# Cancel previous runs for the same PR/branch
concurrency:
  group: cli-tests-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  ELIZA_NONINTERACTIVE: true

on:
  push:
    branches:
      - 'main'
      - 'develop'
  pull_request:
    branches:
      - 'main'
      - 'develop'

jobs:
  test:
    # Skip duplicate runs: run on push to main/develop, or on pull_request events only
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && contains(fromJson('["main", "develop"]'), github.ref_name))
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23

      # Windows-specific setup optimizations
      - name: Configure Windows environment
        if: matrix.os == 'windows-latest'
        shell: powershell
        run: |
          # Increase virtual memory and optimize for CI
          echo "Configuring Windows environment for CI..."
          
          # Set environment variables for better performance
          echo "BUN_INSTALL_CACHE_DIR=$env:RUNNER_TEMP\bun-cache" >> $env:GITHUB_ENV
          echo "NODE_OPTIONS=--max-old-space-size=6144" >> $env:GITHUB_ENV
          echo "FORCE_COLOR=0" >> $env:GITHUB_ENV
          
          # Create necessary directories
          New-Item -ItemType Directory -Force -Path "$env:RUNNER_TEMP\bun-cache"
          
          # Configure Windows Defender exclusions to speed up CI
          try {
            Add-MpPreference -ExclusionPath "$env:GITHUB_WORKSPACE" -ErrorAction SilentlyContinue
            Add-MpPreference -ExclusionPath "$env:RUNNER_TEMP" -ErrorAction SilentlyContinue
          } catch {
            Write-Host "Could not configure Windows Defender exclusions (this is normal in CI)"
          }

      - name: Set up Bun (with Windows optimizations)
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.15
        env:
          # Windows-specific Bun optimizations
          BUN_INSTALL_BIN_DIR: ${{ runner.os == 'Windows' && format('{0}\bun-bin', runner.temp) || '' }}

      - name: Fix and verify Bun installation (Windows-specific)
        if: matrix.os == 'windows-latest'
        shell: powershell
        run: |
          # Use the Bun fixer script
          & powershell -ExecutionPolicy Bypass -File "packages/cli/tests/fix-bun-windows.ps1" -Verbose
          
          if ($LASTEXITCODE -ne 0) {
            Write-Host "Bun fixer failed, attempting fallback solutions..."
            
            # Fallback: Try to add common Bun paths to PATH
            $bunPaths = @(
              "$env:USERPROFILE\.bun\bin",
              "$env:LOCALAPPDATA\bun\bin"
            )
            
            foreach ($path in $bunPaths) {
              if (Test-Path "$path\bun.exe") {
                Write-Host "Found Bun at $path, adding to PATH"
                $env:PATH = "$path;$env:PATH"
                break
              }
            }
            
            # Final test
            $bunTest = Get-Command bun -ErrorAction SilentlyContinue
            if (-not $bunTest) {
              Write-Host "FATAL: Could not fix Bun installation"
              exit 1
            }
          }
          
          Write-Host "✓ Bun is ready for use"

      - name: Mention Bun version
        run: bun --version

      - name: Debug Bun Setup
        shell: bash
        run: |
          echo "PATH: $PATH"
          echo "which bun: $(which bun 2>/dev/null || echo 'which not found')"
          echo "command -v bun: $(command -v bun 2>/dev/null || echo 'command not found')"
          if command -v bun &> /dev/null; then
            BUN_PATH=$(which bun 2>/dev/null || command -v bun)
            echo "Bun found at: $BUN_PATH"
            ls -la "$BUN_PATH" 2>/dev/null || echo "Failed to ls bun"
            file "$BUN_PATH" 2>/dev/null || echo "Failed to get bun file info"
          else
            echo "Bun not found in PATH"
          fi

      - name: Install dependencies (with Windows retry logic)
        shell: bash
        run: |
          echo "Installing dependencies..."
          
          # Function to install with retries
          install_with_retry() {
            local max_attempts=3
            local attempt=1
            
            while [ $attempt -le $max_attempts ]; do
              echo "Installation attempt $attempt of $max_attempts..."
              
              if bun install --frozen-lockfile --no-progress; then
                echo "✓ Dependencies installed successfully"
                return 0
              else
                echo "✗ Installation attempt $attempt failed"
                
                if [ $attempt -lt $max_attempts ]; then
                  echo "Cleaning up and retrying..."
                  rm -rf node_modules 2>/dev/null || true
                  rm -rf ~/.bun/install/cache 2>/dev/null || true
                  sleep 5
                fi
                
                ((attempt++))
              fi
            done
            
            echo "All installation attempts failed"
            return 1
          }
          
          install_with_retry

      - name: Build all packages
        shell: bash
        run: |
          echo "Building all packages..."
          
          # Set memory limits for Windows
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            export NODE_OPTIONS="--max-old-space-size=6144"
          fi
          
          bun run build

      - name: Verify CLI build artifacts
        shell: bash
        run: |
          echo "Checking CLI build artifacts..."
          echo "CLI dist contents:"
          ls -la packages/cli/dist/ || echo "ERROR: No dist directory"
          echo ""
          echo "CLI templates in dist:"
          ls -la packages/cli/dist/templates/ || echo "ERROR: No templates in dist"
          echo ""
          echo "CLI executable:"
          test -f packages/cli/dist/index.js && echo "✓ CLI index.js exists" || echo "ERROR: CLI index.js missing"

      - name: Clean eliza projects cache
        shell: bash
        run: rm -rf ~/.eliza/projects

      - name: Create .env file for tests
        shell: bash
        run: |
          echo "OPENAI_API_KEY=$OPENAI_API_KEY" > .env
          echo "LOG_LEVEL=info" >> .env

      - name: Download models
        shell: bash
        run: |
          MODEL_DIR="$HOME/.eliza/models"
          mkdir -p "$MODEL_DIR"
          declare -a models=(
            "DeepHermes-3-Llama-3-3B-Preview-q4.gguf https://huggingface.co/NousResearch/DeepHermes-3-Llama-3-3B-Preview-GGUF/resolve/main/DeepHermes-3-Llama-3-3B-Preview-q4.gguf"
            "bge-small-en-v1.5.Q4_K_M.gguf https://huggingface.co/ChristianAzinn/bge-small-en-v1.5-gguf/resolve/main/bge-small-en-v1.5.Q4_K_M.gguf"
          )
          for entry in "${models[@]}"; do
            name="${entry%% *}"
            url="${entry#* }"
            path="$MODEL_DIR/$name"
            if [ ! -f "$path" ]; then
              echo "Downloading $name..."
              start=$(date +%s)
              curl -L -f -sS -o "$path" "$url"
              status=$?
              end=$(date +%s)
              duration=$((end - start))
              if [ $status -eq 0 ]; then
                echo "Downloaded $name in ${duration}s."
              else
                echo "Failed to download $name after ${duration}s."
                exit 1
              fi
            else
              echo "$name already exists, skipping."
            fi
          done

      - name: Install cross-env globally
        run: npm install -g cross-env

      - name: Install BATS on macOS
        if: matrix.os == 'macos-latest'
        run: npm install -g bats

      - name: Run CLI TypeScript tests (macOS optimized)
        if: matrix.os == 'macos-latest'
        timeout-minutes: 15
        run: cross-env NODE_OPTIONS="--max-old-space-size=8192" bun test tests/commands/ --timeout 240000
        working-directory: packages/cli
        env:
          ELIZA_TEST_MODE: true

      - name: Cleanup test processes (macOS)
        if: always() && matrix.os == 'macos-latest'
        shell: bash
        run: |
          pkill -f "bun.*dist/index.js" || true
          lsof -ti:3000 | xargs kill -9 2>/dev/null || true
          lsof -ti:3100 | xargs kill -9 2>/dev/null || true
          echo "Cleanup complete"

      - name: Run CLI TypeScript tests (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        timeout-minutes: 15
        run: cross-env NODE_OPTIONS="--max-old-space-size=4096" bun test tests/commands/ --timeout 240000; EXIT_CODE=$?; bash tests/cleanup-processes.sh; exit $EXIT_CODE
        working-directory: packages/cli
        env:
          ELIZA_TEST_MODE: true

      - name: Cleanup test processes (Ubuntu)
        if: always() && matrix.os == 'ubuntu-latest'
        shell: bash
        run: |
          pkill -f "bun.*dist/index.js" || true
          lsof -ti:3000 | xargs kill -9 2>/dev/null || true
          lsof -ti:3100 | xargs kill -9 2>/dev/null || true
          echo "Cleanup complete"

      - name: Run CLI TypeScript tests (Windows - Enhanced)
        if: matrix.os == 'windows-latest'
        timeout-minutes: 25
        shell: powershell
        run: |
          # Change to CLI directory first
          Set-Location packages/cli
          
          # Use the Windows test helper script
          $testCommand = 'cross-env NODE_OPTIONS="--max-old-space-size=6144" bun test tests/commands/ --timeout 300000'
          
          # Execute using the helper script
          & powershell -ExecutionPolicy Bypass -File "tests/windows-test-helper.ps1" -TestCommand $testCommand -MaxRetries 2 -TimeoutMinutes 20
          
          if ($LASTEXITCODE -ne 0) {
            Write-Host "Windows test helper reported failure"
            exit 1
          }
        working-directory: .

      - name: Cleanup test processes (Windows - Enhanced)
        if: always() && matrix.os == 'windows-latest'
        shell: powershell
        run: |
          # Change to CLI directory
          Set-Location packages/cli
          
          # Use the dedicated cleanup script
          & powershell -ExecutionPolicy Bypass -File "tests/cleanup-processes.ps1"

      # Add a final verification step for Windows
      - name: Verify Windows cleanup
        if: always() && matrix.os == 'windows-latest'
        shell: powershell
        run: |
          echo "Verifying cleanup was successful..."
          
          # Check for any remaining test processes
          $remainingProcesses = Get-Process | Where-Object { 
            ($_.ProcessName -like "*bun*" -or $_.ProcessName -like "*node*") -and 
            ($_.Path -like "*dist*index.js*" -or $_.Path -like "*eliza*")
          }
          
          if ($remainingProcesses) {
            echo "Warning: Found $($remainingProcesses.Count) remaining processes:"
            $remainingProcesses | Format-Table ProcessName, Id, Path -AutoSize
          } else {
            echo "✓ No remaining test processes found"
          }
          
          # Check for any remaining port usage
          $testPorts = @(3000, 3100)
          foreach ($port in $testPorts) {
            $connections = Get-NetTCPConnection -LocalPort $port -ErrorAction SilentlyContinue
            if ($connections) {
              echo "Warning: Port $port still has $($connections.Count) active connections"
            }
          }
          
          echo "Verification complete"
