name: Docker Image CI

on:
    push:
        branches: ["main"]

jobs:
    build-and-push:
        runs-on: ubuntu-latest

        permissions:
            packages: write # Required to push images to ghcr.io
            contents: read

        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and Push Docker Image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  tags: ghcr.io/${{ github.repository_owner }}/bino:latest
