name: Deploy Documentation

on:
  push:
    branches:
      - main
      - v2-develop
    paths:
      - 'packages/docs/**'
  pull_request:
    branches:
      - main
      - v2-develop
    paths:
      - 'packages/docs/**'

jobs:
  deploy-docs:
    name: Deploy Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'
          cache: 'npm'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        working-directory: packages/docs
        run: bun install

      - name: Deploy Documentation
        working-directory: packages/docs
        run: bun run deploy
        env:
          USE_SSH: true
