name: Integration Tests
on:
  push:
    branches:
      - "*"
  pull_request_target:
    branches:
      - "*"

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      TURBO_REMOTE_ONLY: true
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - uses: actions/setup-node@v4
        with:
          node-version: "23"
          cache: "bun"

      - name: Install dependencies
        run: bun install

      - name: Build packages
        run: bun run build

      - name: Check for API key
        run: |
          if [ -z "$OPENAI_API_KEY" ]; then
              echo "Error: OPENAI_API_KEY is not set."
              exit 1
          fi

      - name: Run integration tests
        run: bun run integrationTests
