name: smoke-test
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  smoke-tests:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      TURBO_REMOTE_ONLY: true
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - uses: actions/setup-node@v4
        with:
          node-version: "23"
          cache: "bun"

      - name: Run smoke tests
        run: bun run smokeTests
